#!/usr/bin/env python3
# GREP_SUMMARY: security-updates unattended-upgrades 20auto-upgrades 50unattended-upgrades security-only origins reboot-0430 content-match atomic APT_TIMEOUT DevPlan-134
# STRUCTURE: ▶ ensure ┌pkg installed?┐ → ◇ no → install_apt_packages(unattended-upgrades) → ◇ write 20auto-upgrades (content-match no-op) → ◇ write 50unattended-upgrades (origins security-only, reboot policy) → ⎋ bool
# region MODULE_CONTRACT
## @purpose  Автоматические security-обновления ОС через unattended-upgrades (DevPlan 134 L1):
##           декларативная генерация /etc/apt/apt.conf.d/20auto-upgrades + 50unattended-upgrades
##           (security-only origins), идемпотентность через content-match no-op (канон install_cron_metrics),
##           атомарная запись через shared/atomic_writer. Вызывается из φ1 system_bootstrap (шаг 5.5)
##           и φ12 deploy_update (пропагация политики при node-update).
## @scope    CLI: ensure --auto-reboot true|false. Запускается как root (apt-операции, запись в /etc).
##           Импортирует lifecycle.helpers.system (install_apt_packages) — PYTHONPATH экспортирует фасад.
## @invariants
##   - ТОЛЬКО security-источники: origins = ${distro_codename}-security / esm-infra-security (не updates)
##   - Content-match no-op: существующий файл с идентичным содержимым → SKIP (0 записей на диск)
##   - Атомарная запись: shared/atomic_writer (temp + fsync + os.replace)
##   - Reboot-политика: Automatic-Reboot true + 04:30 + WithUsers (live-restore переживает рестарт демона);
##     --auto-reboot false → reboot отключён (env SECURITY_AUTO_REBOOT=false)
##   - Пакет unattended-upgrades: install_apt_packages (is_pkg_installed gate, APT_TIMEOUT=300 канон)
##   - Файлы помечены «Generated — DO NOT EDIT MANUALLY» (политика управления — файлы перезаписываются)
## @rationale L1 security-гэпа (DevPlan 134): apt использовался только в bootstrap-цепочке,
##            автопатчинг отсутствовал (0 упоминаний unattended-upgrades в репозитории до волны).
##            unattended-upgrades — Debian/Ubuntu канон: origins-фильтр, dpkg-lock aware, apt-daily.timer.
## @changes 2026-08-04 | DevPlan 134 W1 — Created
# endregion MODULE_CONTRACT

from __future__ import annotations

import argparse
import logging
import sys
from pathlib import Path

from core.internal.bootstrap.lifecycle.helpers import system as helpers_system
from core.internal.shared.atomic_writer import atomic_write_text

logger = logging.getLogger(__name__)

# Константы путей — модульные (тесты переопределяют через monkeypatch)
AUTO_UPDATES_FILE = "/etc/apt/apt.conf.d/20auto-upgrades"
UNATTENDED_FILE = "/etc/apt/apt.conf.d/50unattended-upgrades"
SECURITY_PACKAGE = "unattended-upgrades"
REBOOT_TIME = "04:30"

# Generated-маркер: файлы управляются платформой, ручная правка будет перезаписана
_GENERATED_HEADER = "// Generated by ai-platform security_updates.py (DevPlan 134) — DO NOT EDIT MANUALLY\n"


# region FUNC_desired_auto_upgrades_config
## @purpose  Желаемое содержимое /etc/apt/apt.conf.d/20auto-upgrades (APT::Periodic).
## @io       ⇥ — → ⎋ str — apt-конфиг (APT::Periodic директивы)
## @complexity O(1)
## @invariants  Unattended-Upgrade "1" — обязательная директива (S1 в security_posture читает её)
def desired_auto_upgrades_config() -> str:
    """20auto-upgrades: APT::Periodic — daily index refresh + unattended-upgrade включён."""
    return (
        _GENERATED_HEADER
        + 'APT::Periodic::Update-Package-Lists "1";\n'
        + 'APT::Periodic::Download-Upgradeable-Packages "1";\n'
        + 'APT::Periodic::AutocleanInterval "7";\n'
        + 'APT::Periodic::Unattended-Upgrade "1";\n'
    )


# endregion FUNC_desired_auto_upgrades_config


# region FUNC_desired_unattended_config
## @purpose  Желаемое содержимое /etc/apt/apt.conf.d/50unattended-upgrades (security-only + reboot-политика).
## @io       ⇥ auto_reboot: bool → ⎋ str — apt-конфиг
## @complexity O(1)
## @invariants  Origins-Pattern — ТОЛЬКО security-источники (${distro_codename}-security, esm-infra/apps-security);
##              НЕ включает ${distro_codename}-updates (не-security обновления остаются ручными)
##              AutoRemove true — autoremove неиспользуемых пакетов после апгрейда
## @rationale  Kernel-CVE требуют ребута; без Automatic-Reboot фиксы ядра висят до ручной перезагрузки.
##             WithUsers=true + live-restore (docker_daemon.py) делают ночной ребут безопасным.
def desired_unattended_config(auto_reboot: bool) -> str:
    """50unattended-upgrades: security-only origins + reboot-политика (04:30, WithUsers)."""
    if auto_reboot:
        reboot_block = (
            'Unattended-Upgrade::Automatic-Reboot "true";\n'
            + f'Unattended-Upgrade::Automatic-Reboot-Time "{REBOOT_TIME}";\n'
            + 'Unattended-Upgrade::Automatic-Reboot-WithUsers "true";\n'
        )
    else:
        reboot_block = (
            "// Automatic-Reboot disabled via SECURITY_AUTO_REBOOT=false\n"
            + 'Unattended-Upgrade::Automatic-Reboot "false";\n'
        )
    return (
        _GENERATED_HEADER
        + "Unattended-Upgrade::Origins-Pattern {\n"
        + '        "origin=Ubuntu,archive=${distro_codename}-security";\n'
        + '        "origin=Ubuntu,suite=${distro_codename}-security";\n'
        + '        "origin=UbuntuESMApps,archive=${distro_codename}-apps-security";\n'
        + '        "origin=UbuntuESM,archive=${distro_codename}-infra-security";\n'
        + "};\n"
        + 'Unattended-Upgrade::AutoRemove "true";\n'
        + 'Unattended-Upgrade::Remove-Unused-Dependencies "true";\n'
        + reboot_block
    )


# endregion FUNC_desired_unattended_config


# region FUNC__write_if_changed
## @purpose  Content-match idempotent write: существующий файл с идентичным содержимым → no-op.
## @io       ⇥ path: Path, desired: str → ⎋ bool (True = записано/уже актуально, False = ошибка записи)
## @complexity O(1) — одно чтение + при необходимости атомарная запись
## @invariants  НИКОГДА не пишет на диск при совпадении содержимого (инвариант 6: строгая идемпотентность)
##              Атомарная запись через shared/atomic_writer (temp + fsync + os.replace, 0644)
def _write_if_changed(path: Path, desired: str) -> bool:
    """Write file only when content differs. Returns True on no-op/write, False on OSError."""
    try:
        existing = path.read_text(encoding="utf-8")
    except FileNotFoundError:
        existing = ""
    if existing == desired:
        logger.info("[IMP:8][security_updates][noop] %s unchanged — no-op (idempotent)", path)
        return True
    try:
        atomic_write_text(str(path), desired, mode=0o644)
        logger.info("[IMP:9][security_updates][write] %s %s", path, "updated" if existing else "created")
        return True
    except OSError as e:
        logger.error("[IMP:10][security_updates][write] Cannot write %s: %s", path, e)
        return False


# endregion FUNC__write_if_changed


# region FUNC_ensure
## @purpose  Полный цикл L1: пакет + 20auto-upgrades + 50unattended-upgrades (идемпотентно).
## @io       ⇥ auto_reboot: bool → ⎋ bool (True = готово, False = non-fatal сбой)
## @complexity O(1) + apt-операции (install_apt_packages, APT_TIMEOUT=300)
## @invariants  Установка пакета — через helpers install_apt_packages (is_pkg_installed gate)
##              Отсутствие пакета в репозитории/невозможность apt → PlatformError → False (φ1 non-fatal)
## @raises   PlatformError от install_apt_packages — вызывающий (фаза) решает fatal/non-fatal
def ensure(auto_reboot: bool) -> bool:
    """Ensure unattended-upgrades security policy: package + both configs. Idempotent."""
    if not helpers_system.is_pkg_installed(SECURITY_PACKAGE):
        logger.info("[IMP:9][security_updates][pkg] Installing %s", SECURITY_PACKAGE)
        helpers_system.install_apt_packages([SECURITY_PACKAGE])
    else:
        logger.info("[IMP:8][security_updates][pkg] %s already installed", SECURITY_PACKAGE)

    ok = True
    ok = _write_if_changed(Path(AUTO_UPDATES_FILE), desired_auto_upgrades_config()) and ok
    ok = _write_if_changed(Path(UNATTENDED_FILE), desired_unattended_config(auto_reboot)) and ok
    if ok:
        logger.info("[IMP:9][security_updates][ensure] Security auto-updates policy applied (reboot=%s)", auto_reboot)
    return ok


# endregion FUNC_ensure


# region FUNC_main
## @purpose  CLI: security_updates.py ensure --auto-reboot true|false (default true).
## @io       ⇥ argv → ⎋ exit code int (0 = ok, 1 = ошибка)
## @complexity O(1) — dispatch-only
def main(argv: list[str] | None = None) -> int:
    """CLI entrypoint. Returns exit code — sys.exit handled by __main__."""
    logging.basicConfig(level=logging.INFO, format="%(message)s", stream=sys.stderr)
    parser = argparse.ArgumentParser(description="Ensure unattended-upgrades security policy (DevPlan 134 L1)")
    parser.add_argument(
        "--auto-reboot",
        choices=("true", "false"),
        default="true",
        help="Enable Automatic-Reboot at 04:30 (default true; SECURITY_AUTO_REBOOT=false disables)",
    )
    args = parser.parse_args(argv)
    try:
        # Гейт bool_string_literals (DevPlan 123 T6): сравнение только через .lower()-нормализацию
        return 0 if ensure((args.auto_reboot or "").lower() == "true") else 1
    except Exception as e:  # noqa: EXC — top-level CLI handler: любой сбой → exit 1 с диагностикой
        logger.error("[IMP:10][security_updates][fatal] Security updates setup failed: %s", e)
        return 1


# endregion FUNC_main


if __name__ == "__main__":
    sys.exit(main())
