#!/usr/bin/env python3
# GREP_SUMMARY: security-updates unattended-upgrades 20auto-upgrades 50unattended-upgrades security-only origins reboot-0430 content-match atomic APT_TIMEOUT DevPlan-134
# STRUCTURE: ▶ ensure ┌pkg installed?┐ → ◇ no → install_apt_packages(unattended-upgrades) → ◇ write 20auto-upgrades (content-match no-op) → ◇ write 50unattended-upgrades (origins security-only, reboot policy) → ⎋ bool
# region MODULE_CONTRACT
## @purpose  Автоматические security-обновления ОС через unattended-upgrades (DevPlan 134 L1):
##           декларативная генерация /etc/apt/apt.conf.d/20auto-upgrades + 50unattended-upgrades
##           (security-only origins), идемпотентность через content-match no-op (канон install_cron_metrics),
##           атомарная запись через shared/atomic_writer. Вызывается из φ1 system_bootstrap (шаг 5.5)
##           и φ12 deploy_update (пропагация политики при node-update).
## @scope    CLI: ensure --auto-reboot true|false. Запускается как root (apt-операции, запись в /etc).
##           Импортирует lifecycle.helpers.system (install_apt_packages) — PYTHONPATH экспортирует фасад.
## @invariants
##   - ТОЛЬКО security-источники: origins = ${distro_codename}-security / esm-infra-security (не updates)
##   - Content-match no-op: существующий файл с идентичным содержимым → SKIP (0 записей на диск)
##   - Атомарная запись: shared/atomic_writer (temp + fsync + os.replace)
##   - Reboot-политика (канон, DevPlan 164 W1): Automatic-Reboot "false" ПО УМОЛЧАНИЮ —
##     единственный ребут-канал платформы — platform-reboot.timer (04:30, Persistent=true,
##     reboot_policy.py check --execute: активная SSH-сессия → «отложен», idle → ребут + TG).
##     --auto-reboot true — только ручной override (SECURITY_AUTO_REBOOT=true)
##   - reboot-required/cert-expiry алерты НЕ в этом модуле: канал — platform-reboot.service
##     (cert_expiry_check.py check первым ExecStart, reboot_policy.py — вторым)
##   - Пакет unattended-upgrades: install_apt_packages (is_pkg_installed gate, APT_TIMEOUT=300 канон)
##   - Файлы помечены «Generated — DO NOT EDIT MANUALLY» (политика управления — файлы перезаписываются)
## @rationale L1 security-гэпа (DevPlan 134): apt использовался только в bootstrap-цепочке,
##            автопатчинг отсутствовал (0 упоминаний unattended-upgrades в репозитории до волны).
##            unattended-upgrades — Debian/Ubuntu канон: origins-фильтр, dpkg-lock aware, apt-daily.timer.
##            DevPlan 164 W1 (вариант A): unattended-reboot заменён платформенным таймером —
##            оператор отверг WithUsers=true (ребут обрывает активную SSH-сессию).
## @changes 2026-08-04 | DevPlan 134 W1 — Created
## @changes 2026-08-13 | DevPlan 162 W6-2 — +telegram failure notification (_notify_config_failure)
## @changes 2026-08-13 | DevPlan 164 W1-3 — deferred-TRAP (reboot-required/cert-expiry) закрыт:
##            политика — в reboot_policy.py + cert_expiry_check.py (platform-reboot.timer);
##            Automatic-Reboot "false" — канон (φ1/φ12 передают auto_reboot=False по умолчанию)
# endregion MODULE_CONTRACT

from __future__ import annotations

import argparse
import logging
import sys
from collections.abc import Callable
from pathlib import Path

from core.internal.bootstrap.lifecycle.helpers import system as helpers_system
from core.internal.shared.atomic_writer import atomic_write_text

logger = logging.getLogger(__name__)

# Константы путей — модульные (тесты переопределяют через monkeypatch)
AUTO_UPDATES_FILE = "/etc/apt/apt.conf.d/20auto-upgrades"
UNATTENDED_FILE = "/etc/apt/apt.conf.d/50unattended-upgrades"
SECURITY_PACKAGE = "unattended-upgrades"
REBOOT_TIME = "04:30"

# Generated-маркер: файлы управляются платформой, ручная правка будет перезаписана
_GENERATED_HEADER = "// Generated by ai-platform security_updates.py (DevPlan 134) — DO NOT EDIT MANUALLY\n"


# region FUNC_desired_auto_upgrades_config
## @purpose  Желаемое содержимое /etc/apt/apt.conf.d/20auto-upgrades (APT::Periodic).
## @io       ⇥ — → ⎋ str — apt-конфиг (APT::Periodic директивы)
## @complexity O(1)
## @invariants  Unattended-Upgrade "1" — обязательная директива (S1 в security_posture читает её)
def desired_auto_upgrades_config() -> str:
    """20auto-upgrades: APT::Periodic — daily index refresh + unattended-upgrade включён."""
    return (
        _GENERATED_HEADER
        + 'APT::Periodic::Update-Package-Lists "1";\n'
        + 'APT::Periodic::Download-Upgradeable-Packages "1";\n'
        + 'APT::Periodic::AutocleanInterval "7";\n'
        + 'APT::Periodic::Unattended-Upgrade "1";\n'
    )


# endregion FUNC_desired_auto_upgrades_config


# region FUNC_desired_unattended_config
## @purpose  Желаемое содержимое /etc/apt/apt.conf.d/50unattended-upgrades (security-only + reboot-политика).
## @io       ⇥ auto_reboot: bool → ⎋ str — apt-конфиг
## @complexity O(1)
## @invariants  Origins-Pattern — ТОЛЬКО security-источники (${distro_codename}-security, esm-infra/apps-security);
##              НЕ включает ${distro_codename}-updates (не-security обновления остаются ручными)
##              AutoRemove true — autoremove неиспользуемых пакетов после апгрейда
## @rationale  Kernel-CVE требуют ребута; без Automatic-Reboot фиксы ядра висят до ручной перезагрузки.
##             WithUsers=true + live-restore (docker_daemon.py) делают ночной ребут безопасным.
def desired_unattended_config(auto_reboot: bool) -> str:
    """50unattended-upgrades: security-only origins + reboot-политика (04:30, WithUsers)."""
    if auto_reboot:
        reboot_block = (
            'Unattended-Upgrade::Automatic-Reboot "true";\n'
            f'Unattended-Upgrade::Automatic-Reboot-Time "{REBOOT_TIME}";\n'
            'Unattended-Upgrade::Automatic-Reboot-WithUsers "true";\n'
        )
    else:
        reboot_block = (
            "// Automatic-Reboot disabled via SECURITY_AUTO_REBOOT=false\n"
            'Unattended-Upgrade::Automatic-Reboot "false";\n'
        )
    return (
        _GENERATED_HEADER
        + "Unattended-Upgrade::Origins-Pattern {\n"
        + '        "origin=Ubuntu,archive=${distro_codename}-security";\n'
        + '        "origin=Ubuntu,suite=${distro_codename}-security";\n'
        + '        "origin=UbuntuESMApps,archive=${distro_codename}-apps-security";\n'
        + '        "origin=UbuntuESM,archive=${distro_codename}-infra-security";\n'
        + "};\n"
        + 'Unattended-Upgrade::AutoRemove "true";\n'
        + 'Unattended-Upgrade::Remove-Unused-Dependencies "true";\n'
        + reboot_block
    )


# endregion FUNC_desired_unattended_config


# region FUNC__write_if_changed
## @purpose  Content-match idempotent write: существующий файл с идентичным содержимым → no-op.
## @io       ⇥ path: Path, desired: str → ⎋ bool (True = записано/уже актуально, False = ошибка записи)
## @complexity O(1) — одно чтение + при необходимости атомарная запись
## @invariants  НИКОГДА не пишет на диск при совпадении содержимого (инвариант 6: строгая идемпотентность)
##              Атомарная запись через shared/atomic_writer (temp + fsync + os.replace, 0644)
def _write_if_changed(path: Path, desired: str) -> bool:
    """Write file only when content differs. Returns True on no-op/write, False on OSError."""
    try:
        existing = path.read_text(encoding="utf-8")
    except FileNotFoundError:
        existing = ""
    if existing == desired:
        logger.info("[IMP:8][security_updates][noop] %s unchanged — no-op (idempotent)", path)
        return True
    try:
        atomic_write_text(str(path), desired, mode=0o644)
        logger.info("[IMP:9][security_updates][write] %s %s", path, "updated" if existing else "created")
    except OSError as e:
        logger.error("[IMP:10][security_updates][write] Cannot write %s: %s", path, e)
        return False
    else:
        return True


# endregion FUNC__write_if_changed


# region FUNC_ensure
## @purpose  Полный цикл L1: пакет + 20auto-upgrades + 50unattended-upgrades (идемпотентно).
## @io       ⇥ auto_reboot: bool, auto_updates_file: str | None = None (DI, W-H DevPlan 163:
##              путь 20auto-upgrades; None = канонический /etc/apt/apt.conf.d/20auto-upgrades),
##              unattended_file: str | None = None (DI: путь 50unattended-upgrades; None = канон),
##              pkg_installed_fn: Callable[[str], bool] | None = None (DI: dpkg-гейт; None = helpers),
##              install_pkgs_fn: Callable[[list[str]], None] | None = None (DI: apt-инсталлер; None = helpers)
##              → ⎋ bool (True = готово, False = non-fatal сбой)
## @complexity O(1) + apt-операции (install_apt_packages, APT_TIMEOUT=300)
## @invariants  Установка пакета — через helpers install_apt_packages (is_pkg_installed gate)
##              Отсутствие пакета в репозитории/невозможность apt → PlatformError → False (φ1 non-fatal)
##              DI-параметры не меняют поведение по умолчанию (None → канонические константы/helpers);
##              тесты передают пути tmp_path и callable-хелперы вместо monkeypatch.setattr (W-H)
## @raises   PlatformError от install_apt_packages — вызывающий (фаза) решает fatal/non-fatal
def ensure(
    auto_reboot: bool,
    auto_updates_file: str | None = None,
    unattended_file: str | None = None,
    pkg_installed_fn: Callable[[str], bool] | None = None,
    install_pkgs_fn: Callable[[list[str]], None] | None = None,
) -> bool:
    """Ensure unattended-upgrades security policy: package + both configs. Idempotent."""
    pkg_installed = helpers_system.is_pkg_installed if pkg_installed_fn is None else pkg_installed_fn
    install_pkgs = helpers_system.install_apt_packages if install_pkgs_fn is None else install_pkgs_fn
    target_auto = AUTO_UPDATES_FILE if auto_updates_file is None else auto_updates_file
    target_unattended = UNATTENDED_FILE if unattended_file is None else unattended_file
    if not pkg_installed(SECURITY_PACKAGE):
        logger.info("[IMP:9][security_updates][pkg] Installing %s", SECURITY_PACKAGE)
        install_pkgs([SECURITY_PACKAGE])
    else:
        logger.info("[IMP:8][security_updates][pkg] %s already installed", SECURITY_PACKAGE)

    ok = True
    ok = _write_if_changed(Path(target_auto), desired_auto_upgrades_config()) and ok
    ok = _write_if_changed(Path(target_unattended), desired_unattended_config(auto_reboot)) and ok
    if ok:
        logger.info("[IMP:9][security_updates][ensure] Security auto-updates policy applied (reboot=%s)", auto_reboot)
    return ok


# endregion FUNC_ensure


# region FUNC__notify_config_failure
## @purpose  Telegram-хук OnError (DevPlan 162 W6-2): silent-failure unattended-upgrades
##           устраняется — отказ конфигурации не молчит. Non-fatal по контракту
##           shared/telegram_notifier (send_telegram никогда не raise'ит).
## @io       ⇥ reason: str — причина провала (вставляется в сообщение) → ⎋ None
## @complexity O(1) + 1 HTTP POST (best-effort)
## @invariants
##   - Только failure-путь: вызывается при ensure() → False или исключении в main()
##   - send_telegram: token/chat из env (TELEGRAM_BOT_TOKEN/TELEGRAM_CHAT_ID) — отсутствие →
##     False (WARN, non-fatal) — не блокирует exit-код
##   - Lazy import: shared.telegram_notifier импортируется в момент вызова (unit-тесты
##     monkeypatch-ят без импорта на module-level)
##   - Любое исключение в хуке → WARN + continue (хук никогда не маскирует основной сбой)
## @rationale DevPlan 162 W6-2: отказ unattended-upgrades молчалив (нет Mail/MailOnlyOnError,
##            нет telegram-хука). OnError → telegram_notifier — оператор узнаёт о провале
##            security-политики в реальном времени.
def _notify_config_failure(reason: str) -> None:
    """Send Telegram failure notification (DevPlan 162 W6-2). Non-fatal, best-effort."""
    try:
        from core.internal.shared.telegram_notifier import send_telegram

        ok = send_telegram(f"[platform] unattended-upgrades config FAILED: {reason}", parse_mode="HTML")
        if not ok:
            logger.warning("[IMP:7][security_updates][telegram] Failure notification not delivered (non-fatal)")
    # ruff: ignore[BLE001] — telegram best-effort — не маскирует сбой security-политики (162 W6-2)
    except Exception as e:  # noqa: EXC — best-effort: notification must never mask the config failure (162 W6-2, DEPLOY_BEST_EFFORT)
        logger.warning("[IMP:7][security_updates][telegram] Notification failed (non-fatal): %s", e)


# endregion FUNC__notify_config_failure


# region FUNC_main
## @purpose  CLI: security_updates.py ensure --auto-reboot true|false (default false —
##           канон DevPlan 164 W1: платформенный таймер — единственный ребут-канал).
##           DevPlan 162 W6-2: отказ (ensure False ИЛИ исключение) → telegram-хук OnError.
##           DI (W-H DevPlan 163): ensure_fn/notify_fn — injectable callables для тестов
##           (0 monkeypatch.setattr; None = канонические ensure/_notify_config_failure).
## @io       ⇥ argv → ⎋ exit code int (0 = ok, 1 = ошибка)
## @complexity O(1) — dispatch-only
def main(
    argv: list[str] | None = None,
    *,
    ensure_fn: Callable[[bool], bool] | None = None,
    notify_fn: Callable[[str], None] | None = None,
) -> int:
    """CLI entrypoint. Returns exit code — sys.exit handled by __main__."""
    logging.basicConfig(level=logging.INFO, format="%(message)s", stream=sys.stderr)
    parser = argparse.ArgumentParser(description="Ensure unattended-upgrades security policy (DevPlan 134 L1)")
    parser.add_argument(
        "--auto-reboot",
        choices=("true", "false"),
        default="false",
        help="Enable unattended Automatic-Reboot (default false — platform-reboot.timer is the reboot channel, 164 W1)",
    )

    class _CliArgs(argparse.Namespace):
        """Типизированный argparse-Namespace (W11-G3)."""

        def __init__(self) -> None:
            super().__init__()
            self.auto_reboot: str

    args = parser.parse_args(argv, namespace=_CliArgs())
    ensure_impl = ensure if ensure_fn is None else ensure_fn
    notify = _notify_config_failure if notify_fn is None else notify_fn
    try:
        # Гейт bool_string_literals (DevPlan 123 T6): сравнение только через .lower()-нормализацию
        ok = ensure_impl((args.auto_reboot or "").lower() == "true")
        if not ok:
            # 162 W6-2: silent-failure — ensure вернул False (write/apt сбой) → telegram-хук
            notify("ensure returned False (apt/write failure)")
    # ruff: ignore[BLE001] — top-level CLI handler: любой сбой → exit 1 с диагностикой
    except Exception as e:  # noqa: EXC — top-level CLI handler: любой сбой → exit 1 с диагностикой
        logger.error("[IMP:10][security_updates][fatal] Security updates setup failed: %s", e)
        # 162 W6-2: OnError → telegram_notifier (failure-only; exit-код сохраняется)
        notify(f"{e}")
        return 1
    else:
        return 0 if ok else 1


# endregion FUNC_main


if __name__ == "__main__":
    sys.exit(main())
