#!/usr/bin/env bash
# GREP_SUMMARY: setup-node sudoers visudo atomic node platform node-lifecycle
# STRUCTURE: ┌NODE_NAME┐ → ⚡ generate_sudoers (visudo -c + atomic mv) → ⎋ exit 0|1
# region MODULE_CONTRACT
## @purpose  Generate sudoers for the platform node safely — temp file → visudo -c → atomic mv (lockout-safe).
##           ТОЛЬКО sudoers. Пользователи (platform/ci-deploy) и SSH-ключи создаются Python-фазой φ2
##           (lifecycle/helpers/users.py) — setup-node.sh НЕ дублирует их (волна 117 D1).
##           DevPlan 136 W10 T10.1: sudoers СУЖЕН — docker/rsync NOPASSWD удалены (PRIVESC, S-1/S-2/S-3).
##           DevPlan 145 W3 D-136-W10: nginx systemctl sudoers УДАЛЕНЫ — все ноды Docker
##           (nginx в контейнере, systemctl unit not found). Rev-нота «вернуть при non-Docker ноде».
## @scope    Called from lifecycle phases.py φ3 (phase_platform_setup) via subprocess.
## @invariants
##   - sudoers generated via temp file → visudo -c → atomic mv (lockout-safe, SC5)
##   - On visudo -c failure: original sudoers untouched, bootstrap aborted
##   - NODE_NAME validated `^[a-zA-Z0-9_-]+$` ДО генерации sudoers-фрагмента (S-9, T10.7) —
##     sudoers-файл /etc/sudoers.d/platform-${NODE_NAME} не должен принимать инъекцию пути
##   - platform/ci-deploy in docker group (φ2, phases/system.py:262-287) → docker-операции БЕЗ sudo;
##     НИКАКИХ sudo docker compose/exec/ps/logs/restart/stats (S-1/S-2 PRIVESC — удалены, T10.1)
##   - НИКАКОГО sudo rsync (S-3 PRIVESC — root-запись в любые файлы; доставка core идёт как root
##     по SSH через core_deliverer.py, sudo rsync не используется нигде — верификация W10 на test-VPS)
##   - НИКАКИХ sudo systemctl nginx (D-136-W10, DevPlan 145 W3) — обе ноды Docker
##     (nginx — контейнер, systemctl unit not found на test-VPS); вернуть при появлении non-Docker ноды
##   - ci-deploy role is SEPARATE from ci role — different scope and sudoers entries (06 §4.2)
##   - audit-путь в sudoers — /var/log/platform/audit.jsonl (ЕДИНЫЙ файл audit_logger.py D1;
##     audit.log мёртв, T10.9/S-11)
## @rationale visudo -c guard: sudoers syntax error = root lockout; temp+validate+mv prevents this (00 §12)
##            Волна 117 D1: create_user/add_owner_key/add_ci_deploy_command удалены — дубли φ2
##            (users.py). Единственный писатель ci-deploy authorized_keys — Python lifecycle φ2.
##            DevPlan 145 W3 D-136-W10: nginx sudoers удалены — обе ноды (tronyx-vps, test-e2e) Docker,
##            nginx работает в контейнере (systemctl unit not found на test-VPS, verификация W10 2026-08-05).
## ⚠️ TRAP[DECISION] · 2026-08-05 · HI · sudoers сужение platform: docker/rsync NOPASSWD удалены (T10.1)
## · Rejected: оставить docker compose */exec */rsync * (риск: любой docker compose run/exec = root-escape;
## ·   rsync * = root-запись в /etc/passwd / authorized_keys — эскалационная цепочка S-1/S-2/S-3)
## · Reason: верификация W10 на test-VPS (103.88.243.151, test-e2e): (а) core_deliverer.py rsync идёт
## ·   user=root по SSH БЕЗ sudo (grep: 0 вызовов sudo docker / sudo rsync в core/); (б) platform и
## ·   ci-deploy в docker group (φ2 phases/system.py:262-287) → docker-команды доступны напрямую,
## ·   sudo не нужен; (в) deploy-modules/DeployOrchestrator исполняются как root (bootstrap) —
## ·   sudo не задействован. Оставлено: node-lifecycle.sh (контролируемый операционный скрипт,
## ·   /opt/platform root-owned — не symlink-вектор), диагностика (ufw/ss/iptables), cat audit.jsonl.
## · Rev: если появится реальный потребитель sudo docker/rsync (платформенный, не user-проект) —
## ·   добавить точечные записи с конкретными флагами + gate-тест; консенсус-пересмотр 2026-10-21.
# endregion MODULE_CONTRACT

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../audit/audit.sh" 2>/dev/null || true

__LOG_PREFIX="setup-node"
source "${SCRIPT_DIR}/../../lib/logging.sh"
# shellcheck source=core/lib/paths.sh
source "${SCRIPT_DIR}/../../lib/paths.sh"

# region GENERATE_SUDOERS
# Канон имени ноды (S-9, DevPlan 136 W10 T10.7): sudoers-файл получает имя из NODE_NAME —
# инъекция пути (/, .., пробел) в имя = запись в произвольный файл /etc/sudoers.d/….
# Валидируем ДО генерации sudoers-фрагмента.
_NODE_NAME_RE='^[a-zA-Z0-9_-]+$'

generate_sudoers() {
    local node_name="$1"

    if ! [[ "${node_name}" =~ ${_NODE_NAME_RE} ]]; then
        echo "[IMP:10][setup-node][sudoers] ERROR: NODE_NAME '${node_name}' invalid — must match ^[a-zA-Z0-9_-]+$ (S-9, T10.7)" >&2
        exit 1
    fi

    log_step "sudoers" "START" "Generating sudoers for platform node: ${node_name}"

    local sudoers_file="/etc/sudoers.d/platform-${node_name}"
    local tmp_sudoers
    tmp_sudoers="$(mktemp /tmp/platform-sudoers-XXXXXX)"
    chmod 0440 "$tmp_sudoers"

    # Write sudoers content
    cat > "$tmp_sudoers" <<EOF
# core sudoers — ${node_name}
# Generated by setup-node.sh at $(date -u '+%Y-%m-%dT%H:%M:%SZ')
# DO NOT edit manually — managed by core bootstrap
#
# DevPlan 136 W10 T10.1 (S-1/S-2/S-3): sudoers СУЖЕН — docker compose/exec/ps/logs/restart/stats
# и rsync NOPASSWD УДАЛЕНЫ (PRIVESC root-escape). platform/ci-deploy в docker group (φ2) →
# docker-операции выполняются напрямую, sudo не нужен. Доставка core — rsync user=root (SSH),
# sudo rsync не используется (верификация W10 на test-VPS). Gate: tests/gates/test_gate_sudoers_hardening.py.
# DevPlan 145 W3 D-136-W10: nginx systemctl sudoers УДАЛЕНЫ — обе ноды Docker (nginx в контейнере,
# systemctl unit not found на test-VPS). Rev: вернуть при появлении non-Docker ноды.

# platform user: platform operations (контролируемый операционный скрипт, /opt/platform root-owned)
platform ALL=(root) NOPASSWD: ${PLATFORM_ROOT}/core/internal/bootstrap/node-lifecycle.sh

# platform user: diagnostic commands
platform ALL=(root) NOPASSWD: /usr/sbin/ufw status verbose
platform ALL=(root) NOPASSWD: /usr/bin/cat /var/log/platform/audit.jsonl
platform ALL=(root) NOPASSWD: /usr/sbin/ss -tlnp
platform ALL=(root) NOPASSWD: /usr/sbin/iptables -t nat -L -n

# ci-deploy user: NO docker/nginx commands via sudo
# ci-deploy is in docker group → direct docker socket access (no sudo needed)
# /usr/bin/docker compose * intentionally NOT granted — principle of least privilege (06 §4.2)
# Role ci-deploy is SEPARATE from role ci — different scope, different sudoers entries
# DevPlan 145 W3: nginx systemctl reload/status removed (nginx — Docker module, systemctl unit not found)
EOF

    # [IMP:10][setup-node][sudoers] CRITICAL: validate before atomic replace — lockout-safe
    if ! visudo -c -f "$tmp_sudoers" &>/dev/null 2>&1; then
        local visudo_err
        visudo_err="$(visudo -c -f "$tmp_sudoers" 2>&1 || true)"
        log_step "sudoers" "FAIL" "visudo -c FAILED: ${visudo_err} — original sudoers NOT touched"
        rm -f "$tmp_sudoers"
        exit 1
    fi

    mv "$tmp_sudoers" "$sudoers_file"
    log_step "sudoers" "DONE" "sudoers generated and validated: ${sudoers_file}"
}
# endregion GENERATE_SUDOERS

main() {
    if [[ "$(id -u)" -ne 0 ]]; then
        echo "[IMP:10][setup-node][main] ERROR: must run as root" >&2
        exit 1
    fi

    local node_name="${NODE_NAME:-$(hostname)}"

    # Волна 117 D1: create_user/add_owner_key/add_ci_deploy_command удалены — дубли φ2 (users.py).
    # Единственный писатель ci-deploy authorized_keys — Python lifecycle φ2 (phases.py:256).
    # Сюда осталось ТОЛЬКО генерация sudoers (уникальная реализация).
    # W10 T10.7: валидация NODE_NAME (regex) выполняется внутри generate_sudoers ДО записи файла.
    generate_sudoers "$node_name"

    log_step "main" "DONE" "Node setup complete: sudoers generated for node=${node_name}"
}

main "$@"
