#!/usr/bin/env bash
# GREP_SUMMARY: setup-node sudoers visudo atomic node platform
# STRUCTURE: ┌NODE_NAME┐ → ⚡ generate_sudoers (visudo -c + atomic mv) → ⎋ exit 0|1
# region MODULE_CONTRACT
## @purpose  Generate sudoers for the platform node safely — temp file → visudo -c → atomic mv (lockout-safe).
##           ТОЛЬКО sudoers. Пользователи (platform/ci-deploy) и SSH-ключи создаются Python-фазой φ2
##           (lifecycle/helpers/users.py) — setup-node.sh НЕ дублирует их (волна 117 D1).
## @scope    Called from lifecycle phases.py φ3 (phase_platform_setup) via subprocess.
## @invariants
##   - sudoers generated via temp file → visudo -c → atomic mv (lockout-safe, SC5)
##   - On visudo -c failure: original sudoers untouched, bootstrap aborted
##   - ci-deploy in docker group → no sudo for docker; sudoers only: nginx reload/status
##   - ci-deploy role is SEPARATE from ci role — different scope and sudoers entries (06 §4.2)
## @rationale visudo -c guard: sudoers syntax error = root lockout; temp+validate+mv prevents this (00 §12)
##            Волна 117 D1: create_user/add_owner_key/add_ci_deploy_command удалены — дубли φ2
##            (users.py). Единственный писатель ci-deploy authorized_keys — Python lifecycle φ2.
# endregion MODULE_CONTRACT

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../audit/audit.sh" 2>/dev/null || true

__LOG_PREFIX="setup-node"
source "${SCRIPT_DIR}/../../lib/logging.sh"
# shellcheck source=core/lib/paths.sh
source "${SCRIPT_DIR}/../../lib/paths.sh"

# region GENERATE_SUDOERS
generate_sudoers() {
    local node_name="$1"

    log_step "sudoers" "START" "Generating sudoers for platform node: ${node_name}"

    local sudoers_file="/etc/sudoers.d/platform-${node_name}"
    local tmp_sudoers
    tmp_sudoers="$(mktemp /tmp/platform-sudoers-XXXXXX)"
    chmod 0440 "$tmp_sudoers"

    # Write sudoers content
    cat > "$tmp_sudoers" <<EOF
# core sudoers — ${node_name}
# Generated by setup-node.sh at $(date -u '+%Y-%m-%dT%H:%M:%SZ')
# DO NOT edit manually — managed by core bootstrap

# platform user: nginx management
platform ALL=(root) NOPASSWD: /bin/systemctl start nginx
platform ALL=(root) NOPASSWD: /bin/systemctl stop nginx
platform ALL=(root) NOPASSWD: /bin/systemctl restart nginx
platform ALL=(root) NOPASSWD: /bin/systemctl reload nginx
platform ALL=(root) NOPASSWD: /bin/systemctl status nginx
platform ALL=(root) NOPASSWD: /usr/sbin/nginx -t

# platform user: docker management
platform ALL=(root) NOPASSWD: /usr/bin/docker compose *
platform ALL=(root) NOPASSWD: /usr/bin/docker ps *
platform ALL=(root) NOPASSWD: /usr/bin/docker logs *
platform ALL=(root) NOPASSWD: /usr/bin/docker restart *
platform ALL=(root) NOPASSWD: /usr/bin/docker exec *
platform ALL=(root) NOPASSWD: /usr/bin/docker stats *

# platform user: platform operations
platform ALL=(root) NOPASSWD: ${PLATFORM_ROOT}/core/internal/bootstrap/node-lifecycle.sh
platform ALL=(root) NOPASSWD: /usr/bin/rsync *

# platform user: diagnostic commands
platform ALL=(root) NOPASSWD: /usr/sbin/ufw status verbose
platform ALL=(root) NOPASSWD: /usr/bin/cat /var/log/platform/audit.log
platform ALL=(root) NOPASSWD: /usr/sbin/ss -tlnp
platform ALL=(root) NOPASSWD: /usr/sbin/iptables -t nat -L -n

# ci-deploy user: nginx reload only — NO docker commands via sudo
# ci-deploy is in docker group → direct docker socket access (no sudo needed)
# /usr/bin/docker compose * intentionally NOT granted — principle of least privilege (06 §4.2)
# Role ci-deploy is SEPARATE from role ci — different scope, different sudoers entries
ci-deploy ALL=(root) NOPASSWD: /bin/systemctl reload nginx
ci-deploy ALL=(root) NOPASSWD: /bin/systemctl status nginx
EOF

    # [IMP:10][setup-node][sudoers] CRITICAL: validate before atomic replace — lockout-safe
    if ! visudo -c -f "$tmp_sudoers" &>/dev/null 2>&1; then
        local visudo_err
        visudo_err="$(visudo -c -f "$tmp_sudoers" 2>&1 || true)"
        log_step "sudoers" "FAIL" "visudo -c FAILED: ${visudo_err} — original sudoers NOT touched"
        rm -f "$tmp_sudoers"
        exit 1
    fi

    mv "$tmp_sudoers" "$sudoers_file"
    log_step "sudoers" "DONE" "sudoers generated and validated: ${sudoers_file}"
}
# endregion GENERATE_SUDOERS

main() {
    if [[ "$(id -u)" -ne 0 ]]; then
        echo "[IMP:10][setup-node][main] ERROR: must run as root" >&2
        exit 1
    fi

    local node_name="${NODE_NAME:-$(hostname)}"

    # Волна 117 D1: create_user/add_owner_key/add_ci_deploy_command удалены — дубли φ2 (users.py).
    # Единственный писатель ci-deploy authorized_keys — Python lifecycle φ2 (phases.py:256).
    # Сюда осталось ТОЛЬКО генерация sudoers (уникальная реализация).
    generate_sudoers "$node_name"

    log_step "main" "DONE" "Node setup complete: sudoers generated for node=${node_name}"
}

main "$@"
