# GREP_SUMMARY: gate security clickhouse users.xml literal-passwords open-networks access-management dev-prod heuristic
# STRUCTURE: ┌glob core/modules/clickhouse/config/users.d/*.xml┐ → ◇ xml.etree.ElementTree parse → ◇ scan <password> → ◇ scan <networks>/<ip> → ◇ scan <access_management> → ⊕ assert
# region MODULE_CONTRACT
## @purpose — Gate test A6: validate ClickHouse users.d/*.xml security configuration:
##            1. No literal passwords (dev/test placeholders allowed with CDATA heuristic)
##            2. No open networks (::/0, 0.0.0.0/0)
##            3. No access_management=1 in production configs
## @scope — Scans core/modules/clickhouse/config/users.d/*.xml using xml.etree.ElementTree.
##          Dev/test placeholders (CDATA containing "test-*-not-for-prod") are tolerated.
## @invariants
##   - Empty password tag (no text, no CDATA) = FAIL (no-password auth)
##   - Literal non-placeholder password = FAIL
##   - CDATA with "test-*-not-for-prod" or "CHANGE_ME" = IMP:7 warning, not FAIL
##   - ::/0 or 0.0.0.0/0 in <ip> elements = FAIL
##   - <access_management>1</access_management> = FAIL (bypasses password auth)
## @rationale — Post-refactoring audit C1: prevent committing production passwords to repo
## @changes — 2026-07-12 | Created per 004-automation-plan TASK-4
# endregion MODULE_CONTRACT

import logging
import pathlib
import xml.etree.ElementTree as ET

import pytest

from tests.conftest import ldd_trajectory

_PROJECT_ROOT: pathlib.Path = pathlib.Path(__file__).resolve().parent.parent.parent
_USERS_D_DIR: pathlib.Path = _PROJECT_ROOT / "core" / "modules" / "clickhouse" / "config" / "users.d"

logger = logging.getLogger(__name__)

# Dev/test password patterns that are acceptable
_DEV_PASSWORD_PATTERNS = ["test-", "not-for-prod", "CHANGE_ME", "placeholder"]

# Files in users.d/ that are auto-generated by ClickHouse Docker entrypoint
# from CLICKHOUSE_PASSWORD env var — protected by .gitignore, not security-reviewed.
_AUTO_GENERATED_USERS_XML = {"default-user.xml"}


def _find_users_xmls() -> list[pathlib.Path]:
    """Find all users XML files in ClickHouse users.d directory,
    excluding auto-generated files (created by Docker entrypoint from env vars).

    ## @purpose — Glob core/modules/clickhouse/config/users.d/*.xml,
    ##            skip files that are auto-generated from CLICKHOUSE_PASSWORD.
    ## @io — ⎋ list[pathlib.Path] of XML files found (non-auto-generated)
    ## @complexity — O(N) where N = files in users.d directory
    ## @rationale — default-user.xml is created by ClickHouse Docker entrypoint
    ##              from CLICKHOUSE_PASSWORD env var. It contains ::/0 and
    ##              access_management=1 by design (local dev). Protected by .gitignore.
    ##              Security scanning should only apply to committed config files.
    """
    if not _USERS_D_DIR.is_dir():
        logger.warning("[IMP:7][_find_users_xmls] users.d directory not found: %s", _USERS_D_DIR)
        return []

    xml_files = sorted(_USERS_D_DIR.glob("*.xml"))
    # Filter out auto-generated files
    filtered = [f for f in xml_files if f.name not in _AUTO_GENERATED_USERS_XML]
    skipped = len(xml_files) - len(filtered)
    if skipped:
        logger.info(
            "[IMP:8][_find_users_xmls] Skipped %d auto-generated file(s): %s",
            skipped,
            [f.name for f in xml_files if f.name in _AUTO_GENERATED_USERS_XML],
        )
    logger.info("[IMP:8][_find_users_xmls] Found %d XML file(s) in %s (after exclusions)", len(filtered), _USERS_D_DIR)
    return filtered


def _is_dev_password(password_text: str) -> bool:
    """Check if a password text is a dev/test placeholder.

    ## @purpose — Heuristic: if password contains "test-" or "not-for-prod" or "CHANGE_ME"
    ##            it's considered a dev placeholder (warning, not fail).
    ## @io — ⇥ password_text → ⎋ bool: True if dev placeholder
    ## @complexity — O(1)
    """
    lower = password_text.lower()
    return any(pattern.lower() in lower for pattern in _DEV_PASSWORD_PATTERNS)


def _parse_xml_safe(xml_path: pathlib.Path) -> ET.Element | None:
    """Parse an XML file safely, returning root element or None on failure.

    ## @purpose — Wrapper around ET.parse with error handling.
    ## @io — ⇥ xml_path → ⎋ ET.Element | None
    ## @complexity — O(N) where N = XML file size
    """
    try:
        tree = ET.parse(xml_path)
        return tree.getroot()
    except ET.ParseError as e:
        logger.warning("[IMP:7][_parse_xml_safe] XML parse error in %s: %s", xml_path, e)
        return None


# ─── Tests ───────────────────────────────────────────────────────────────────


@pytest.mark.gate
@ldd_trajectory
def test_clickhouse_no_literal_passwords(caplog) -> None:
    """Verify no literal passwords in ClickHouse users XML.

    ## @purpose — Scan all <password> elements in users.d/*.xml for literal passwords.
    ##            Empty password tags (no text) = FAIL (no-password auth).
    ##            CDATA with dev/test placeholders = IMP:7 warning, not FAIL.
    ##            Any other literal password = FAIL.
    ## @io — ⎋ None (assert side-effect)
    ## @complexity — O(N * U) where N = XML files, U = users per file
    """
    logger.info("[IMP:8][test_clickhouse_no_literal_passwords] === Password audit ===")

    xml_files = _find_users_xmls()
    if not xml_files:
        pytest.skip("No ClickHouse users XML files found")

    violations: list[str] = []
    dev_warnings: list[str] = []

    for xml_path in xml_files:
        root = _parse_xml_safe(xml_path)
        if root is None:
            continue

        # Find all <password> elements
        for pwd_elem in root.iter("password"):
            # Get file context: parent <user> name
            user_name = "unknown"
            parent = None
            for candidate_parent in root.iter():
                for child in candidate_parent:
                    if child is pwd_elem:
                        parent = candidate_parent
                        break
                if parent is not None:
                    break
            if parent is not None:
                # Look for <name_of_user> element (the tag name itself is the username)
                # In ClickHouse XML: <default><password>...</password></default>
                # So the parent tag is the username
                user_name = parent.tag

            password_text = (pwd_elem.text or "").strip()
            # Check CDATA
            cdata = ""
            if pwd_elem.text is None and len(pwd_elem) == 0:
                # Empty password tag — no text, no children
                violations.append(
                    f"{xml_path}: user '{user_name}' has empty <password> — no-password authentication (security hole)"
                )
                logger.warning("[IMP:7] %s", violations[-1])
                continue

            if pwd_elem.text is None:
                # May have CDATA — check tail or children
                cdata = "".join(pwd_elem.itertext()).strip()
            else:
                cdata = password_text

            if not cdata:
                violations.append(
                    f"{xml_path}: user '{user_name}' has empty <password> (no text/CDATA) — "
                    "no-password authentication (security hole)"
                )
                logger.warning("[IMP:7] %s", violations[-1])
                continue

            if _is_dev_password(cdata):
                dev_warnings.append(f"{xml_path}: user '{user_name}' has dev/test password placeholder")
                logger.info(
                    "[IMP:7][test_clickhouse_no_literal_passwords] Dev password in %s user '%s': %s",
                    xml_path.name,
                    user_name,
                    cdata,
                )
            else:
                violations.append(
                    f"{xml_path}: user '{user_name}' has literal password "
                    f"'{cdata[:20]}{'...' if len(cdata) > 20 else ''}' — "
                    "use secrets/env vars instead"
                )
                logger.warning("[IMP:7] %s", violations[-1])

    if dev_warnings:
        logger.info(
            "[IMP:7][test_clickhouse_no_literal_passwords] %d dev/test password(s) found (acceptable):",
            len(dev_warnings),
        )
        for w in dev_warnings:
            logger.info("[IMP:7]  %s", w)

    if violations:
        logger.critical(
            "[IMP:9][test_clickhouse_no_literal_passwords] FAIL — %d security violation(s)",
            len(violations),
        )
        pytest.fail("\n".join(violations))

    logger.critical(
        "[IMP:9][test_clickhouse_no_literal_passwords] PASS — no literal passwords in ClickHouse users XML "
        "(%d file(s), %d dev placeholder(s) tolerated)",
        len(xml_files),
        len(dev_warnings),
    )


@pytest.mark.gate
@ldd_trajectory
def test_clickhouse_no_open_networks(caplog) -> None:
    """Verify no open networks (::/0, 0.0.0.0/0) in ClickHouse users XML.

    ## @purpose — Scan <networks>/<ip> elements for unrestricted network access.
    ##            Open networks bypass Docker network isolation.
    ## @io — ⎋ None (assert side-effect)
    ## @complexity — O(N * U * I) where I = IP entries per user
    """
    logger.info("[IMP:8][test_clickhouse_no_open_networks] === Networks audit ===")

    xml_files = _find_users_xmls()
    if not xml_files:
        pytest.skip("No ClickHouse users XML files found")

    violations: list[str] = []
    open_ips = {"::/0", "0.0.0.0/0"}

    for xml_path in xml_files:
        root = _parse_xml_safe(xml_path)
        if root is None:
            continue

        for ip_elem in root.iter("ip"):
            ip_value = (ip_elem.text or "").strip()
            if ip_value in open_ips:
                # Find parent user context via parent-map walk-up
                user_name = "unknown"
                parent_map = {c: p for p in root.iter() for c in p}
                elem = ip_elem
                while elem in parent_map:
                    elem = parent_map[elem]
                    if elem.tag not in ("ip", "networks", "users", "clickhouse"):
                        user_name = elem.tag
                        break

                violations.append(
                    f"{xml_path}: user '{user_name}' has open network '{ip_value}' — "
                    "restrict to specific IP/subnet or Docker network"
                )
                logger.warning("[IMP:7] %s", violations[-1])

    if violations:
        logger.critical(
            "[IMP:9][test_clickhouse_no_open_networks] FAIL — %d open network(s) detected",
            len(violations),
        )
        pytest.fail("\n".join(violations))

    logger.critical(
        "[IMP:9][test_clickhouse_no_open_networks] PASS — no open networks in ClickHouse users XML "
        "(%d file(s) checked)",
        len(xml_files),
    )


@pytest.mark.gate
@ldd_trajectory
def test_clickhouse_access_management_not_1(caplog) -> None:
    """Verify access_management is not set to 1 in ClickHouse users XML.

    ## @purpose — Scan <access_management> elements. Value 1 means SQL-driven user management,
    ##            which bypasses users.xml password enforcement (user can change own password).
    ##            In production, this should be 0 (users.xml-driven auth).
    ##            Exception: default-user.xml with remove="remove" is tolerated (explicit disable).
    ## @io — ⎋ None (assert side-effect)
    ## @complexity — O(N * U) where U = users per file
    """
    logger.info("[IMP:8][test_clickhouse_access_management_not_1] === Access management audit ===")

    xml_files = _find_users_xmls()
    if not xml_files:
        pytest.skip("No ClickHouse users XML files found")

    violations: list[str] = []

    for xml_path in xml_files:
        root = _parse_xml_safe(xml_path)
        if root is None:
            continue

        for am_elem in root.iter("access_management"):
            am_value = (am_elem.text or "").strip()

            # Find user context via parent-map walk-up
            user_name = "unknown"
            parent_map = {c: p for p in root.iter() for c in p}
            elem = am_elem
            while elem in parent_map:
                elem = parent_map[elem]
                if elem.tag not in ("access_management", "users", "clickhouse"):
                    user_name = elem.tag
                    break

            if am_value == "1":
                # Check if XML element has remove="remove" attribute (explicit disable)
                if am_elem.get("remove") == "remove":
                    logger.info(
                        "[IMP:7][test_clickhouse_access_management_not_1] %s user '%s': "
                        "access_management=1 but remove='remove' — explicit disable, tolerated",
                        xml_path.name,
                        user_name,
                    )
                    continue

                violations.append(
                    f"{xml_path}: user '{user_name}' has <access_management>1</access_management> — "
                    "this bypasses users.xml password enforcement (SQL-driven auth)"
                )
                logger.warning("[IMP:7] %s", violations[-1])
            else:
                logger.info(
                    "[IMP:8][test_clickhouse_access_management_not_1] %s user '%s': access_management=%s ✓",
                    xml_path.name,
                    user_name,
                    am_value,
                )

    if violations:
        logger.critical(
            "[IMP:9][test_clickhouse_access_management_not_1] FAIL — %d access_management=1 violation(s)",
            len(violations),
        )
        pytest.fail("\n".join(violations))

    logger.critical(
        "[IMP:9][test_clickhouse_access_management_not_1] PASS — no access_management=1 in production config",
    )
