# GREP_SUMMARY: test clickhouse config default-user xml auto-generated gitignore env
# STRUCTURE: test_default_user_xml_auto_generated_and_ignored → assert file exists + valid XML + .gitignore pattern
# region MODULE_CONTRACT
## @purpose  Validates ClickHouse default-user.xml is auto-generated by Docker entrypoint
##           from CLICKHOUSE_PASSWORD env var, is valid XML, and is git-ignored.
## @scope    Verifies the env-var-based auth mechanism works: entrypoint creates the file,
##           it's valid XML, and it's protected by .gitignore (never committed).
## @invariants
##   - Test parses XML directly (no Docker/ClickHouse required for XML validation)
##   - When CLICKHOUSE_PASSWORD is set: file must exist and be valid XML with 2 <default> blocks
##   - When CLICKHOUSE_PASSWORD is not set: test skips (file won't be generated)
##   - Always: .gitignore must contain the pattern for this auto-generated file
## @rationale default-user.xml is auto-generated by ClickHouse Docker entrypoint from
##           CLICKHOUSE_PASSWORD env var (see: hub.docker.com/r/clickhouse/clickhouse-server).
##           The entrypoint writes this file to users.d/ which is bind-mounted to host,
##           so it appears in the working tree. .gitignore prevents it from being committed.
##           This is the root cause of the cyclic security regression (3x fix-reintroduce cycle).
## @changes 2026-07-15 — Wave T5.4: repurposed test for env-var + .gitignore strategy
# endregion MODULE_CONTRACT

import logging
import os
import xml.etree.ElementTree as ET
from pathlib import Path

import pytest

logger = logging.getLogger(__name__)

# Paths
_PROJECT_ROOT = Path(__file__).resolve().parent.parent
_GITIGNORE_PATH = _PROJECT_ROOT / ".gitignore"
_DEFAULT_USER_XML = _PROJECT_ROOT / "core" / "modules" / "clickhouse" / "config" / "users.d" / "default-user.xml"

# The gitignore pattern for auto-generated default-user.xml
_GITIGNORE_PATTERN = "core/modules/clickhouse/config/users.d/default-user.xml"


@pytest.mark.static_audit
def test_default_user_xml_auto_generated_and_ignored(caplog) -> None:
    """Assert default-user.xml is auto-generated, valid XML, and git-ignored.

    When CLICKHOUSE_PASSWORD is not set (e.g., CI without .env), the entrypoint
    skips file generation — test skips gracefully.
    """
    caplog.set_level(logging.DEBUG)

    # ── Check 1: .gitignore contains the pattern ─────────────────────────
    assert _GITIGNORE_PATH.is_file(), f".gitignore not found: {_GITIGNORE_PATH}"
    gitignore_content = _GITIGNORE_PATH.read_text()
    has_pattern = _GITIGNORE_PATTERN in gitignore_content
    logger.critical(
        "[IMP:9][test_clickhouse][gitignore] .gitignore contains '%s': %s",
        _GITIGNORE_PATTERN,
        has_pattern,
    )
    assert has_pattern, (
        f".gitignore is missing pattern '{_GITIGNORE_PATTERN}'. "
        f"Without it, auto-generated default-user.xml may be accidentally committed."
    )
    logger.info("[IMP:8][test_clickhouse][gitignore] .gitignore guard present")

    # ── Check 2: file exists when CLICKHOUSE_PASSWORD is set ──────────────
    # ⚠️ TRAP[BUG] · 2026-07-16 · HI · Static-test depends on runtime artifact
    # · Symptom: CI failure — CLICKHOUSE_PASSWORD env var set (test value) but
    #   default-user.xml absent (generated by Docker entrypoint at container start,
    #   not present in fresh git checkout; file is gitignored)
    # · Root: Contract mismatch — static_audit test expected file whenever env var
    #   is set, but file is a Docker runtime artifact, not a git-tracked file
    # · Fix: Split invariants — .gitignore guard always checked; file existence
    #   checked only when present; skip gracefully when absent (CI/fresh checkout)
    # · Prevention: static tests must not assert existence of Docker runtime
    #   artifacts. File-generation tests belong in smoke/component scope.
    using_pw = os.environ.get("CLICKHOUSE_PASSWORD")
    if using_pw and _DEFAULT_USER_XML.is_file():
        logger.info("[IMP:8][test_clickhouse][file] default-user.xml exists (entrypoint generated)")

        # ── Check 3: Valid XML ───────────────────────────────────────────
        tree = ET.parse(str(_DEFAULT_USER_XML))
        root = tree.getroot()
        users_elem = root.find("users")
        assert users_elem is not None, "Expected <users> element in default-user.xml"

        default_elements = users_elem.findall("default")
        logger.critical(
            "[IMP:9][test_clickhouse][xml] Found %d <default> elements — "
            "first=remove, second=env-var-password (expected ≥1 for env-var mechanism)",
            len(default_elements),
        )
        assert len(default_elements) >= 1, (
            f"Expected at least 1 <default> element (generated by entrypoint), got {len(default_elements)}"
        )

        # First block should be <default remove="remove"> (removes old config)
        first_default = default_elements[0]
        if first_default.attrib.get("remove") == "remove":
            logger.info("[IMP:8][test_clickhouse][xml] First <default> block is 'remove' — correct")
        else:
            logger.info(
                "[IMP:8][test_clickhouse][xml] First <default> block has no 'remove' — entrypoint may have different config"
            )

        logger.critical("[IMP:9][test_clickhouse][ok] default-user.xml is valid XML generated by entrypoint")
    elif using_pw and not _DEFAULT_USER_XML.is_file():
        # CLICKHOUSE_PASSWORD is set but file not generated yet — fresh checkout / CI
        # This is a Docker runtime artifact; skip file-existence checks gracefully.
        logger.critical(
            "[IMP:9][test_clickhouse][skip] CLICKHOUSE_PASSWORD set but %s not found — "
            "file is a Docker entrypoint runtime artifact, absent in fresh checkout (CI)",
            _DEFAULT_USER_XML.name,
        )
        pytest.skip(f"{_DEFAULT_USER_XML.name} not generated — runtime artifact of "
                     "Docker entrypoint, absent in fresh checkout")
    else:
        # CLICKHOUSE_PASSWORD not set — entrypoint doesn't generate the file
        logger.info(
            "[IMP:7][test_clickhouse][skip] CLICKHOUSE_PASSWORD not set — "
            "entrypoint won't generate default-user.xml, skipping file checks"
        )
        if _DEFAULT_USER_XML.is_file():
            logger.warning(
                "[IMP:8][test_clickhouse][skip] default-user.xml exists despite "
                "CLICKHOUSE_PASSWORD not being set — may be stale from previous run"
            )

    # LDD trajectory
    found_imp9 = False
    print("--- LDD TRAJECTORY (IMP:7-10) ---")
    for record in caplog.records:
        if "[IMP:" in record.message:
            imp_level = int(record.message.split("[IMP:")[1].split("]")[0])
            if imp_level >= 7:
                print(record.message)
            if imp_level >= 9:
                found_imp9 = True
    print("--- END LDD TRAJECTORY ---")
    assert found_imp9, "Critical LDD Error: No IMP:9 business logic log found"
