# GREP_SUMMARY: clickhouse static-tests xml-validity healthcheck-contract module-yaml makefile-template config-integrity user-security
# STRUCTURE: ▶ platform_root → ∋ core/modules/clickhouse/** → ◇ test_config_xml_valid ⊕ test_healthcheck_sources_lib ⊕ test_module_yaml_structure ⊕ test_makefile_template ⊕ test_users_xml_no_empty_password → ⎋ pass|fail
# @file test_clickhouse_static.py
# @purpose  Static validation tests for ClickHouse module: XML config well-formedness,
#           healthcheck.sh contract, module.yaml structure, Makefile template inclusion,
#           and user security (no empty password in users.d).
# @scope    Pure file I/O — no Docker, no subprocess, no external dependencies.
#           Tests are lightweight and runnable in any environment (local, CI, pre-commit).
# @invariants
#   - All tests are marked @pytest.mark.static_audit
#   - XML parsing via xml.etree.ElementTree (stdlib only)
#   - Healthcheck validation via text content analysis (sources lib/healthcheck.sh, has exit 0/1)
#   - Module.yaml validation via yaml.safe_load()
#   - IMP:9 logging for all pass/fail assertions (LDD trajectory)
# @rationale  ClickHouse is a new module in the observability stack — static validation
#             catches regressions early (malformed XML, broken healthcheck contract,
#             security misconfiguration) without requiring Docker.
# @changes    CREATED: 2026-07-12 | ClickHouse integration testing

# region MODULE_CONTRACT
## @purpose  Static validation for ClickHouse module: XML well-formedness, healthcheck contract,
##           module.yaml structure, Makefile template, user security.
## @scope    5 tests — all pure file I/O, no Docker or subprocess.
## @invariants
##   - Test 1: All config.d/*.xml and users.d/*.xml files parse without XML errors
##   - Test 2: healthcheck.sh sources ../../lib/healthcheck.sh — contract enforcement
##   - Test 3: module.yaml has D4 required fields: name, install_type, description, depends_on
##   - Test 4: Makefile includes ../../templates/module.mk
##   - Test 5: users.d/10-users.xml (non-auto-generated) does NOT contain hardcoded passwords
##   - All tests use @ldd_trajectory decorator for IMP:9 verification
## @rationale — Catches config regressions before Docker-dependent tests. Lightweight,
##              parallel-safe in CI. Follows pattern established by test_healthcheck_contract.py.
def _module_contract():
    pass


# endregion MODULE_CONTRACT

import logging
import os
import re
import xml.etree.ElementTree as ET

import pytest
import yaml
from conftest import ldd_trajectory

logger = logging.getLogger(__name__)

# ── Paths ────────────────────────────────────────────────────────────────────
CLICKHOUSE_MODULE_DIR = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "core",
    "modules",
    "clickhouse",
)

CONFIG_D_DIR = os.path.join(CLICKHOUSE_MODULE_DIR, "config", "config.d")
USERS_D_DIR = os.path.join(CLICKHOUSE_MODULE_DIR, "config", "users.d")
HEALTHCHECK_PATH = os.path.join(CLICKHOUSE_MODULE_DIR, "healthcheck.sh")
MODULE_YAML_PATH = os.path.join(CLICKHOUSE_MODULE_DIR, "module.yaml")
MAKEFILE_PATH = os.path.join(CLICKHOUSE_MODULE_DIR, "Makefile")


# ── Helpers ──────────────────────────────────────────────────────────────────

# Files in users.d/ that are auto-generated by ClickHouse Docker entrypoint
# and protected by .gitignore — should NOT be scanned for hardcoded passwords
# because they contain the env-var-derived password by design.
_AUTO_GENERATED_USERS_XML = {"default-user.xml"}


def _collect_xml_files(directory: str, exclude: set[str] | None = None) -> list[str]:
    """Collect all .xml files in a directory, sorted by name.

    ## @purpose — Find all XML config files for batch validation.
    ## @io — ⇥ directory: str, exclude: set[str] | None → ⎋ list[str] (absolute paths to .xml files)
    ## @complexity — O(N) where N = entries in directory
    """
    if not os.path.isdir(directory):
        return []
    exclude = exclude or set()
    return sorted(
        os.path.join(directory, f)
        for f in os.listdir(directory)
        if f.endswith(".xml") and os.path.isfile(os.path.join(directory, f)) and f not in exclude
    )


# ═══════════════════════════════════════════════════════════════════════════════
# Test 1: XML config well-formedness
# ═══════════════════════════════════════════════════════════════════════════════


@pytest.mark.static_audit
@ldd_trajectory
def test_clickhouse_config_xml_valid(caplog: pytest.LogCaptureFixture) -> None:
    """Verify all ClickHouse config XML files (config.d/*.xml, users.d/*.xml) are well-formed.

    ## @purpose — Malformed XML in config.d or users.d causes ClickHouse to fail
    ##            silently (skips the fragment) or crash at startup. This test catches
    ##            XML syntax errors before Docker deployment.
    ## @io — ⇥ caplog → ⎋ None (asserts no XML parse errors)
    ## @complexity — O(N) where N = total XML files
    ## @scenario — AC-1: All XML configs parse without errors
    """
    xml_files = _collect_xml_files(CONFIG_D_DIR) + _collect_xml_files(USERS_D_DIR)

    if not xml_files:
        logger.warning("[IMP:7][clickhouse-xml] No XML config files found in config.d/ or users.d/")
        pytest.fail("No ClickHouse XML config files found — expected config.d/*.xml and users.d/*.xml")

    logger.info("[IMP:7][clickhouse-xml] Found %d XML config file(s)", len(xml_files))

    for xml_path in xml_files:
        try:
            ET.parse(xml_path)
            logger.info("[IMP:8][clickhouse-xml] Valid XML: %s", os.path.basename(xml_path))
        except ET.ParseError as exc:
            logger.error("[IMP:9][clickhouse-xml] FAIL: %s — XML parse error: %s", os.path.basename(xml_path), exc)
            pytest.fail(f"Malformed XML in {os.path.basename(xml_path)}: {exc}")

    logger.info("[IMP:9][clickhouse-xml] PASS: All %d XML config(s) well-formed", len(xml_files))


# ═══════════════════════════════════════════════════════════════════════════════
# Test 2: Healthcheck contract — sources lib/healthcheck.sh
# ═══════════════════════════════════════════════════════════════════════════════


@pytest.mark.static_audit
@ldd_trajectory
def test_clickhouse_healthcheck_contract(caplog: pytest.LogCaptureFixture) -> None:
    """Verify clickhouse/healthcheck.sh follows the module healthcheck contract.

    ## @purpose — Per core/modules/AGENTS.md: every healthcheck.sh must source
    ##            ../../lib/healthcheck.sh (shared library) and have proper exit codes
    ##            (exit 0 = healthy, exit 1 = unhealthy).
    ## @io — ⇥ caplog → ⎋ None (asserts contract compliance)
    ## @complexity — O(1) — single file content check
    ## @invariants
    ##   - Must contain: source ... ../../lib/healthcheck.sh
    ##   - Must contain: exit 0 (healthy path)
    ##   - Must contain: exit 1 (unhealthy path)
    ##   - Must have: set -euo pipefail (strict bash mode)
    ## @scenario — AC-2: Healthcheck script follows module contract
    """
    if not os.path.isfile(HEALTHCHECK_PATH):
        logger.error("[IMP:9][clickhouse-healthcheck] FAIL: healthcheck.sh not found at %s", HEALTHCHECK_PATH)
        pytest.fail(f"ClickHouse healthcheck.sh not found at {HEALTHCHECK_PATH}")

    with open(HEALTHCHECK_PATH, encoding="utf-8") as fh:
        content = fh.read()

    # ── Check: sources lib/healthcheck.sh ──
    sources_lib = "../../lib/healthcheck.sh" in content
    logger.info("[IMP:7][clickhouse-healthcheck] Sources lib/healthcheck.sh: %s", sources_lib)
    assert sources_lib, (
        "[IMP:9][clickhouse-healthcheck] FAIL: healthcheck.sh does not source ../../lib/healthcheck.sh — "
        "module contract violation (core/modules/AGENTS.md §Healthcheck-контракт)"
    )

    # ── Check: exit 0 (healthy path) ──
    has_exit_0 = "exit 0" in content
    logger.info("[IMP:7][clickhouse-healthcheck] Has exit 0 (healthy): %s", has_exit_0)
    assert has_exit_0, (
        "[IMP:9][clickhouse-healthcheck] FAIL: healthcheck.sh missing 'exit 0' — healthy path not defined"
    )

    # ── Check: exit 1 (unhealthy path) ──
    has_exit_1 = "exit 1" in content
    logger.info("[IMP:7][clickhouse-healthcheck] Has exit 1 (unhealthy): %s", has_exit_1)
    assert has_exit_1, (
        "[IMP:9][clickhouse-healthcheck] FAIL: healthcheck.sh missing 'exit 1' — unhealthy path not defined"
    )

    # ── Check: strict mode ──
    has_strict = "set -euo pipefail" in content
    logger.info("[IMP:7][clickhouse-healthcheck] Has 'set -euo pipefail': %s", has_strict)
    # Strict mode is recommended but not mandatory — log warning only
    if not has_strict:
        logger.warning("[IMP:8][clickhouse-healthcheck] WARN: healthcheck.sh missing 'set -euo pipefail'")

    # ── Check: docker exec based healthcheck (not systemctl — macOS compatible) ──
    has_docker_exec = "docker exec" in content
    logger.info("[IMP:7][clickhouse-healthcheck] Has 'docker exec': %s", has_docker_exec)
    assert has_docker_exec, (
        "[IMP:9][clickhouse-healthcheck] FAIL: healthcheck.sh missing 'docker exec' — "
        "must use docker exec for container healthcheck (macOS-compatible, no systemctl)"
    )

    logger.info("[IMP:9][clickhouse-healthcheck] PASS: Healthcheck contract satisfied")


# ═══════════════════════════════════════════════════════════════════════════════
# Test 3: module.yaml structure
# ═══════════════════════════════════════════════════════════════════════════════


@pytest.mark.static_audit
@ldd_trajectory
def test_clickhouse_module_yaml_structure(caplog: pytest.LogCaptureFixture) -> None:
    """Verify clickhouse/module.yaml has required fields and valid structure.

    ## @purpose — module.yaml is the machine-readable registry of module metadata.
    ##            deploy-modules.sh and CI gates read module.yaml to determine
    ##            install_type, dependencies, and network configuration.
    ##            Missing fields cause deploy failures.
    ## @io — ⇥ caplog → ⎋ None (asserts YAML structure)
    ## @complexity — O(1)
    ## @invariants
    ##   - D4 required keys: name, install_type, description, depends_on (core/modules/AGENTS.md)
    ##   - name must be 'clickhouse'
    ##   - install_type must be 'docker'
    ##   - depends_on must be a list (may be empty)
    ##   - spool_dir/spool_volume recommended (deploy-modules.sh)
    ##   - env_requires recommended (pre-deploy validation)
    ## @scenario — AC-3: Module YAML has complete and valid structure
    """
    if not os.path.isfile(MODULE_YAML_PATH):
        logger.error("[IMP:9][clickhouse-module-yaml] FAIL: module.yaml not found at %s", MODULE_YAML_PATH)
        pytest.fail(f"ClickHouse module.yaml not found at {MODULE_YAML_PATH}")

    with open(MODULE_YAML_PATH, encoding="utf-8") as fh:
        data = yaml.safe_load(fh)

    # version and config were removed from D4 contract per core/modules/AGENTS.md
    # D4 fields: name, install_type, description, depends_on, spool_dir, spool_volume,
    #            resources, env_shared, env_requires
    required_keys = {
        "name": str,
        "install_type": str,
        "description": str,
        "depends_on": list,
    }

    for key, expected_type in required_keys.items():
        assert key in data, f"[IMP:9][clickhouse-module-yaml] FAIL: module.yaml missing required key '{key}'"
        assert isinstance(data[key], expected_type), (
            f"[IMP:9][clickhouse-module-yaml] FAIL: module.yaml '{key}' expected {expected_type.__name__}, "
            f"got {type(data[key]).__name__}"
        )
        logger.info("[IMP:8][clickhouse-module-yaml] Key '%s' present with correct type", key)

    # ── Semantic assertions ──
    assert data["name"] == "clickhouse", (
        f"[IMP:9][clickhouse-module-yaml] FAIL: expected name='clickhouse', got '{data['name']}'"
    )
    assert data["install_type"] == "docker", (
        f"[IMP:9][clickhouse-module-yaml] FAIL: expected install_type='docker', got '{data['install_type']}'"
    )

    # spool_dir and spool_volume are D4-required (deploy-modules.sh consumes them)
    has_spool_dir = "spool_dir" in data and isinstance(data["spool_dir"], str)
    has_spool_volume = "spool_volume" in data and isinstance(data["spool_volume"], str)
    logger.info("[IMP:7][clickhouse-module-yaml] spool_dir: %s, spool_volume: %s", has_spool_dir, has_spool_volume)
    if not has_spool_dir:
        logger.warning("[IMP:8][clickhouse-module-yaml] WARN: module.yaml missing spool_dir (recommended)")
    if not has_spool_volume:
        logger.warning("[IMP:8][clickhouse-module-yaml] WARN: module.yaml missing spool_volume (recommended)")

    # env_requires is D4-required — ensures deploy catches missing secrets
    has_env_requires = "env_requires" in data and isinstance(data["env_requires"], list)
    logger.info("[IMP:7][clickhouse-module-yaml] env_requires: %s", has_env_requires)
    if has_env_requires:
        logger.info("[IMP:8][clickhouse-module-yaml] env_requires: %s", data["env_requires"])

    logger.info("[IMP:9][clickhouse-module-yaml] PASS: module.yaml structure valid")


# ═══════════════════════════════════════════════════════════════════════════════
# Test 4: Makefile includes module.mk template
# ═══════════════════════════════════════════════════════════════════════════════


@pytest.mark.static_audit
@ldd_trajectory
def test_clickhouse_makefile_template(caplog: pytest.LogCaptureFixture) -> None:
    """Verify clickhouse/Makefile includes the standard module template.

    ## @purpose — Per core/modules/AGENTS.md §Makefile-контракт: every module
    ##            Makefile MUST include ../../templates/module.mk and define MODULE_NAME.
    ##            This ensures consistent lifecycle management (start, stop, restart,
    ##            status, logs, backup).
    ## @io — ⇥ caplog → ⎋ None (asserts Makefile structure)
    ## @complexity — O(1)
    ## @scenario — AC-4: Makefile follows module contract
    """
    if not os.path.isfile(MAKEFILE_PATH):
        logger.error("[IMP:9][clickhouse-makefile] FAIL: Makefile not found at %s", MAKEFILE_PATH)
        pytest.fail(f"ClickHouse Makefile not found at {MAKEFILE_PATH}")

    with open(MAKEFILE_PATH, encoding="utf-8") as fh:
        content = fh.read()

    # ── Check: defines MODULE_NAME ──
    has_module_name = "MODULE_NAME :=" in content or "MODULE_NAME=" in content
    logger.info("[IMP:7][clickhouse-makefile] Defines MODULE_NAME: %s", has_module_name)
    assert has_module_name, (
        "[IMP:9][clickhouse-makefile] FAIL: Makefile does not define MODULE_NAME — "
        "module contract violation (core/modules/AGENTS.md §Makefile-контракт)"
    )

    # ── Check: includes module.mk ──
    includes_template = "../../templates/module.mk" in content
    logger.info("[IMP:7][clickhouse-makefile] Includes ../../templates/module.mk: %s", includes_template)
    assert includes_template, (
        "[IMP:9][clickhouse-makefile] FAIL: Makefile does not include ../../templates/module.mk — "
        "module contract violation (core/modules/AGENTS.md §Makefile-контракт)"
    )

    logger.info("[IMP:9][clickhouse-makefile] PASS: Makefile follows module template contract")


# ═══════════════════════════════════════════════════════════════════════════════
# Test 5: No empty password in users.d (security regression guard)
# ═══════════════════════════════════════════════════════════════════════════════


@pytest.mark.static_audit
@ldd_trajectory
def test_clickhouse_users_xml_no_hardcoded_password(caplog: pytest.LogCaptureFixture) -> None:
    """Verify NO users.d/*.xml contains a hardcoded literal password.

    ## @purpose — Any literal <password>…</password> value in users.d/*.xml overrides
    ##            the CLICKHOUSE_PASSWORD env var, creating a security breach where
    ##            anyone on the Docker network can authenticate with full DDL rights.
    ##            This test scans ALL users.d/*.xml for any literal password content.
    ## @io — ⇥ caplog → ⎋ None (asserts no hardcoded password in any XML file)
    ## @complexity — O(N*M) where N = XML files, M = lines per file
    ## @invariants
    ##   - Scans ALL *.xml in USERS_D_DIR (not just 10-users.xml)
    ##   - Strips XML comments before scanning to avoid false positives from docs
    ##   - Detects ANY literal <password>…</password> content (not just empty tags)
    ##   - Also detects empty <password></password> and <password/> separately
    ## @scenario — AC-5: No hardcoded password in any users.d/*.xml
    """
    if not os.path.isdir(USERS_D_DIR):
        pytest.skip(f"Clickhouse users.d directory not found: {USERS_D_DIR}")

    # Exclude auto-generated files (default-user.xml is created by Docker entrypoint
    # from CLICKHOUSE_PASSWORD env var and is protected by .gitignore)
    xml_files = _collect_xml_files(USERS_D_DIR, exclude=_AUTO_GENERATED_USERS_XML)
    if not xml_files:
        logger.warning("[IMP:7][clickhouse-password] No trackable XML files in users.d/ (excluding auto-generated)")
        pytest.fail("No ClickHouse users.d/*.xml files found — expected at least 10-users.xml")

    logger.info(
        "[IMP:7][clickhouse-password] Scanning %d file(s) for hardcoded passwords: %s",
        len(xml_files),
        [os.path.basename(f) for f in xml_files],
    )

    # 💼 TRAP[BUSINESS] · 2026-07-12 · HI · No hardcoded password in users.d — security imperative
    # · Source: DevPlan C1 — ClickHouse security regression (post-refactoring audit)
    # · Risk: Hardcoded password overrides CLICKHOUSE_PASSWORD env var → authentication-less access

    any_violation = False

    for xml_path in xml_files:
        with open(xml_path, encoding="utf-8") as fh:
            content = fh.read()

        # Strip XML comments to avoid false positives from documentation
        xml_stripped = re.sub(r"<!--.*?-->", "", content, flags=re.DOTALL)

        # ── Check 1: empty password tag (<password></password> or <password/>) ──
        has_empty = "<password></password>" in xml_stripped or "<password/>" in xml_stripped
        if has_empty:
            any_violation = True
            logger.error(
                "[IMP:9][clickhouse-password] FAIL: %s contains empty <password> tag — "
                "this overrides CLICKHOUSE_PASSWORD env var.",
                os.path.basename(xml_path),
            )

        # ── Check 2: any literal password content in <password> element ──
        # Match <password> followed by anything that is NOT empty tag
        # Regex: <password[^>]*> followed by at least one non-whitespace char or CDATA
        has_literal = bool(re.search(r"<\s*password[^>]*>\s*(?:(?!<\s*/\s*password\s*>).)+", xml_stripped, re.DOTALL))
        if has_literal:
            any_violation = True
            # Extract the offending line for diagnostic
            for lineno, line in enumerate(content.splitlines(), 1):
                if re.search(r"<\s*password[^>]*>", line) and not re.search(r"<\s*password\s*/>", line):
                    logger.error(
                        "[IMP:9][clickhouse-password] FAIL: %s line %d — literal password content: %s",
                        os.path.basename(xml_path),
                        lineno,
                        line.strip(),
                    )

    # ── Check: does NOT restrict to 127.0.0.1 only (blocks Docker network access) ──
    # Use the sole 10-users.xml for this check
    sole_xml = os.path.join(USERS_D_DIR, "10-users.xml")
    if os.path.isfile(sole_xml):
        with open(sole_xml, encoding="utf-8") as fh:
            content_10 = fh.read()
        xml_stripped_10 = re.sub(r"<!--.*?-->", "", content_10, flags=re.DOTALL)
        has_localhost_only = all(
            ip_pat in xml_stripped_10 for ip_pat in ["<networks>", "<ip>127.0.0.1</ip>", "</networks>"]
        )
        if has_localhost_only:
            logger.warning(
                "[IMP:8][clickhouse-password] WARN: 10-users.xml restricts default user to 127.0.0.1 only. "
                "This blocks Grafana and Prometheus (on observability-net) from accessing ClickHouse. "
                "Remove <networks> restriction unless a separate user is created for Docker network access."
            )

    if any_violation:
        pytest.fail(
            "[IMP:9][clickhouse-password] FAIL: One or more users.d/*.xml files contain "
            "hardcoded passwords — see LDD log for details."
        )

    logger.info("[IMP:9][clickhouse-password] PASS: No hardcoded password in any users.d/*.xml (security guard)")
