# GREP_SUMMARY: test scaffold_helpers gen_ai_platform_yaml gen_makefile gen_agents register_in_node_yaml shared extraction
# STRUCTURE: ┌tmp_path fixture┐ → ○ 13 tests → ⊕ LDD trajectory (IMP:9) → ⚡ anti-loop counter
# region MODULE_CONTRACT
## @purpose  Unit-тесты scaffold_helpers.py: gen_ai_platform_yaml (full + minimal + all types),
##           gen_project_makefile (generate + idempotent + force), gen_project_agents (generate + idempotent),
##           register_in_node_yaml (dry-run). LDD IMP:9 + Anti-Loop + R1-R5.
## @scope    Tests under tests/ (unit, no Docker). DI over Mocks для NodeYaml CLI subprocess.
## @invariants  Все тесты используют tmp_path (R1). R1-R5 compliance: негативные тесты для overwrite protection.
## @rationale AC4: 4 unit-теста на scaffold_helpers.py (расширено до 13 для покрытия всех типов).
## ⚠️ TRAP[DECISION] · 2026-07-31 · MED · Дедупликация: unit-версия тестов удалена (import file mismatch)
## · Rejected: оставить tests/unit/test_scaffold_helpers.py (риск: pytest import file mismatch —
##   одинаковый basename с tests/test_scaffold_helpers.py ломает collection всего сьюта)
## · Reason: корневая версия каноническая (в test_inventory.yaml); уникальные ассерты из unit
##   (target_node, ai_retention absent, PLATFORM_DIR, postgres/DD13-контракты) перенесены сюда.
## · Rev: если unit-директория вернётся к полному покрытию — ресинхронизировать inventory.
## @changes 2026-07-31 · DevPlan 092 AC4 — initial implementation
## @changes 2026-07-31 · Dedup fix — уникальные ассерты перенесены из tests/unit/
# endregion MODULE_CONTRACT

from __future__ import annotations

import logging
import pathlib

import yaml

from tests.conftest import ldd_trajectory

logger = logging.getLogger(__name__)

from core.internal.scaffold.scaffold_helpers import (
    gen_ai_platform_yaml,
    gen_project_agents,
    gen_project_makefile,
    register_in_node_yaml,
)

# ── gen_ai_platform_yaml tests ────────────────────────────────────────────


@ldd_trajectory
def test_gen_yaml_backend_full(tmp_path: pathlib.Path, caplog) -> None:
    yaml_path = tmp_path / "ai-platform.yaml"
    logger.info("[IMP:9][test][helpers] test_gen_yaml_backend_full")
    result = gen_ai_platform_yaml(
        name="test-backend",
        ptype="backend",
        org="test-org",
        node="tronyx-vps",
        domain="backend.tronyx.ru",
        database="backend_db",
        mode="prod",
        output_path=yaml_path,
        minimal=False,
    )
    assert result == "generated", f"Expected 'generated', got {result}"
    assert yaml_path.exists()
    content = yaml_path.read_text()
    assert "GENERATED by scaffold_helpers.py" in content
    parsed = yaml.safe_load(content)
    assert parsed["name"] == "test-backend"
    assert parsed["type"] == "backend"
    assert parsed["target_node"] == "tronyx-vps", f"Expected target_node, got {parsed.get('target_node')}"
    mon = parsed["monitoring"]
    assert mon["metrics"] is True
    assert mon["logs_retention"] == "14d"
    assert mon["alerting"] is False
    assert "database" in parsed["needs"]


@ldd_trajectory
def test_gen_yaml_frontend_full(tmp_path: pathlib.Path, caplog) -> None:
    yaml_path = tmp_path / "ai-platform.yaml"
    logger.info("[IMP:9][test][helpers] test_gen_yaml_frontend_full")
    result = gen_ai_platform_yaml(
        name="test-frontend",
        ptype="frontend",
        org="test-org",
        domain="frontend.tronyx.ru",
        output_path=yaml_path,
        minimal=False,
    )
    assert result == "generated"
    parsed = yaml.safe_load(yaml_path.read_text())
    mon = parsed["monitoring"]
    assert mon["metrics"] is False
    assert mon["logs_retention"] == "3d"
    assert mon["alerting"] is False
    assert mon["dashboard"] is False


@ldd_trajectory
def test_gen_yaml_fullstack_full(tmp_path: pathlib.Path, caplog) -> None:
    yaml_path = tmp_path / "ai-platform.yaml"
    logger.info("[IMP:9][test][helpers] test_gen_yaml_fullstack_full")
    result = gen_ai_platform_yaml(
        name="test-fullstack",
        ptype="fullstack",
        org="test-org",
        domain="fullstack.tronyx.ru",
        output_path=yaml_path,
        minimal=False,
    )
    assert result == "generated"
    parsed = yaml.safe_load(yaml_path.read_text())
    mon = parsed["monitoring"]
    assert mon["metrics"] is True
    assert mon["ai_retention"] == "30d"
    assert mon["alerting"] is True
    assert mon["dashboard"] is True
    assert "llm" in parsed["needs"]
    assert parsed["needs"]["llm"] == "remote"


@ldd_trajectory
def test_gen_yaml_minimal_mode(tmp_path: pathlib.Path, caplog) -> None:
    yaml_path = tmp_path / "ai-platform.yaml"
    logger.info("[IMP:9][test][helpers] test_gen_yaml_minimal_mode")
    result = gen_ai_platform_yaml(
        name="test-adopted",
        ptype="backend",
        org="test-org",
        domain="adopted.tronyx.ru",
        output_path=yaml_path,
        minimal=True,
    )
    assert result == "generated"
    parsed = yaml.safe_load(yaml_path.read_text())
    mon = parsed["monitoring"]
    assert mon["metrics"] is False
    assert mon["logs_retention"] == "7d"
    assert mon["alerting"] is False
    assert mon["dashboard"] is False
    assert "ai_retention" not in mon, "minimal mode must not include ai_retention"
    assert "database" not in parsed.get("needs", {})


@ldd_trajectory
def test_gen_yaml_dev_mode(tmp_path: pathlib.Path, caplog) -> None:
    yaml_path = tmp_path / "ai-platform.yaml"
    logger.info("[IMP:9][test][helpers] test_gen_yaml_dev_mode")
    result = gen_ai_platform_yaml(
        name="test-dev", ptype="backend", org="test-org", mode="dev", output_path=yaml_path, minimal=False
    )
    assert result == "generated"
    parsed = yaml.safe_load(yaml_path.read_text())
    assert parsed.get("staging") is True, f"Expected staging=True in dev mode, got {parsed.get('staging')}"


# ── gen_project_makefile tests ────────────────────────────────────────────


@ldd_trajectory
def test_gen_makefile_new(tmp_path: pathlib.Path, caplog) -> None:
    makefile_path = tmp_path / "Makefile"
    logger.info("[IMP:9][test][helpers] test_gen_makefile_new")
    result = gen_project_makefile(name="test-project", domain="test.tronyx.ru", output_path=makefile_path, force=False)
    assert result == "generated"
    assert makefile_path.exists()
    content = makefile_path.read_text()
    assert "sync-env:" in content
    assert "project-sync-env" in content
    assert "status:" in content
    assert "project-status" in content
    assert "help:" in content
    assert "PLATFORM_DIR" in content, "Makefile must reference PLATFORM_DIR"
    assert "test-project" in content
    assert "\t@" in content


@ldd_trajectory
def test_gen_makefile_exists_no_overwrite(tmp_path: pathlib.Path, caplog) -> None:
    makefile_path = tmp_path / "Makefile"
    original = "# Custom Makefile — DO NOT OVERWRITE\n.PHONY: all\n"
    makefile_path.write_text(original)
    logger.info("[IMP:9][test][helpers] test_gen_makefile_exists_no_overwrite")
    result = gen_project_makefile(name="test-project", domain="test.tronyx.ru", output_path=makefile_path, force=False)
    assert result == "exists"
    assert makefile_path.read_text() == original


@ldd_trajectory
def test_gen_makefile_force_overwrite(tmp_path: pathlib.Path, caplog) -> None:
    makefile_path = tmp_path / "Makefile"
    makefile_path.write_text("# OLD Makefile")
    logger.info("[IMP:9][test][helpers] test_gen_makefile_force_overwrite")
    result = gen_project_makefile(name="forced-project", domain="", output_path=makefile_path, force=True)
    assert result == "generated"
    content = makefile_path.read_text()
    assert "forced-project" in content


# ── gen_project_agents tests ──────────────────────────────────────────────


@ldd_trajectory
def test_gen_agents_new(tmp_path: pathlib.Path, caplog) -> None:
    agents_path = tmp_path / "AGENTS.md"
    logger.info("[IMP:9][test][helpers] test_gen_agents_new")
    result = gen_project_agents(
        name="test-project",
        org="test-org",
        template="backend",
        node="tronyx-vps",
        domain="test.tronyx.ru",
        output_path=agents_path,
        force=False,
    )
    assert result == "generated"
    assert agents_path.exists()
    content = agents_path.read_text()
    assert "Platform provides" in content
    assert "DO NOT" in content
    assert "Commands from this directory" in content
    assert "test-project" in content
    assert "test-org" in content
    assert "tronyx-vps" in content
    assert "postgres" in content, "AGENTS.md must reference postgres service"
    assert "make sync-env" in content, "AGENTS.md must reference make sync-env"
    assert "make status" in content, "AGENTS.md must reference make status"
    line_count = content.count("\n")
    assert line_count <= 70, f"AGENTS.md exceeds 70 lines: {line_count} lines"


@ldd_trajectory
def test_gen_agents_exists_no_overwrite(tmp_path: pathlib.Path, caplog) -> None:
    agents_path = tmp_path / "AGENTS.md"
    original = "# Custom AGENTS.md — project specific"
    agents_path.write_text(original)
    logger.info("[IMP:9][test][helpers] test_gen_agents_exists_no_overwrite")
    result = gen_project_agents(name="test-project", org="test-org", output_path=agents_path, force=False)
    assert result == "exists"
    assert agents_path.read_text() == original


# ── register_in_node_yaml tests ───────────────────────────────────────────


@ldd_trajectory
def test_register_no_yaml_path(caplog) -> None:
    logger.info("[IMP:9][test][helpers] test_register_no_yaml_path")
    result = register_in_node_yaml(name="test", yaml_path="")
    assert not result, "Expected False for empty yaml_path"


@ldd_trajectory
def test_register_missing_yaml_file(tmp_path: pathlib.Path, caplog) -> None:
    yaml_path = tmp_path / "nonexistent" / "node.yaml"
    logger.info("[IMP:9][test][helpers] test_register_missing_yaml_file")
    result = register_in_node_yaml(name="test", org="test-org", yaml_path=yaml_path)
    assert not result, "Expected False for missing yaml file"


@ldd_trajectory
def test_register_dry_run(tmp_path: pathlib.Path, caplog) -> None:
    yaml_path = tmp_path / "node-configs" / "tronyx-vps" / "node.yaml"
    yaml_path.parent.mkdir(parents=True, exist_ok=True)
    yaml_path.write_text("projects: []\n")
    logger.info("[IMP:9][test][helpers] test_register_dry_run")
    result = register_in_node_yaml(
        name="test-project",
        org="test-org",
        node="tronyx-vps",
        ptype="backend",
        domain="test.tronyx.ru",
        yaml_path=yaml_path,
        dry_run=True,
    )
    assert result, "Expected dry_run=True to return True"
    content = yaml_path.read_text()
    assert "projects:" in content
