# GREP_SUMMARY: test gen-env-platform env-generator scaffold platform-env provides profiles pgbouncer dsn
# STRUCTURE: ┌platform_env_yaml fixture┐ → ○ 9 tests → ⊕ LDD trajectory IMP:7-10
# region MODULE_CONTRACT
## @purpose  Test suite for gen-env-platform.sh — validates .env.platform generation contract
## @scope    9 test functions covering: header, min vars, provides list, DSN format, pgbouncer host,
##           NO_PROXY, idempotency, missing YAML error, provides⊄profiles fail-fast
## @invariants
##   - All tests use tmp_path for fixture files (no hardcoded paths)
##   - Tests call gen-env-platform.sh via subprocess (native bash testing)
##   - Every test is decorated with @ldd_trajectory for LDD telemetry
##   - platform_env_yaml fixture provides minimal valid platform-env.yaml with 2 services
## @rationale T18 per DevPlan $TEST_SPEC — validates CI-critical gen-env-platform.sh contract
## @changes 2026-07-17 · T18 — initial implementation
# endregion MODULE_CONTRACT

import logging
import pathlib
import subprocess


import pytest
import yaml

from tests.conftest import ldd_trajectory

logger = logging.getLogger(__name__)

# ── Paths ─────────────────────────────────────────────────────────────────────
_PROJECT_ROOT: pathlib.Path = pathlib.Path(__file__).resolve().parent.parent
_GEN_ENV_SCRIPT: pathlib.Path = _PROJECT_ROOT / "core" / "internal" / "scaffold" / "gen-env-platform.sh"

# ── Fixtures ──────────────────────────────────────────────────────────────────


@pytest.fixture
def platform_env_yaml(tmp_path: pathlib.Path) -> pathlib.Path:
    """Create a minimal valid platform-env.yaml with provides and profiles.

    ## @purpose — Test fixture: provides 2 services (postgres + redis) with
    ##            matching profiles and proxy NO_PROXY.
    ## @invariants
    ##   - All provides keys are in profiles (valid state)
    ##   - postgres DSN uses pgbouncer:6432 per O5
    ##   - Returns path to YAML file in tmp_path
    """
    data = {
        "provides": {
            "postgres": {
                "host": "pgbouncer",
                "port": 6432,
                "dsn_template": "postgresql://${NAME}_user:***@pgbouncer:6432/${NAME}_db",
                "networks": ["shared-db-net"],
            },
            "redis": {
                "host": "redis",
                "port": 6379,
                "url_template": "redis://redis:6379/0",
                "networks": ["shared-cache-net"],
            },
        },
        "proxy": {
            "no_proxy_internal": "localhost,127.0.0.1,.local,postgres,pgbouncer,redis,clickhouse",
        },
        "profiles": ["postgres", "redis"],
    }
    yaml_path = tmp_path / "platform-env.yaml"
    with open(yaml_path, "w") as f:
        yaml.dump(data, f, default_flow_style=False)
    logger.info("[IMP:8][fixture][platform_env_yaml] Created: %s", yaml_path)
    return yaml_path


@pytest.fixture
def platform_env_yaml_provides_not_in_profiles(tmp_path: pathlib.Path) -> pathlib.Path:
    """Create platform-env.yaml where a provides key is NOT in profiles.

    ## @purpose — Test fixture for fail-fast validation (DD8).
    ##            redis key is in provides but NOT in profiles.
    """
    data = {
        "provides": {
            "postgres": {
                "host": "pgbouncer",
                "port": 6432,
                "dsn_template": "postgresql://${NAME}_user:***@pgbouncer:6432/${NAME}_db",
            },
            "redis": {
                "host": "redis",
                "port": 6379,
                "url_template": "redis://redis:6379/0",
            },
        },
        "profiles": ["postgres"],  # redis is missing
    }
    yaml_path = tmp_path / "platform-env-bad.yaml"
    with open(yaml_path, "w") as f:
        yaml.dump(data, f, default_flow_style=False)
    logger.info(
        "[IMP:8][fixture][platform_env_yaml_provides_not_in_profiles] Created: %s",
        yaml_path,
    )
    return yaml_path


# ═══════════════════════════════════════════════════════════════════════════════
# TESTS
# ═══════════════════════════════════════════════════════════════════════════════


@ldd_trajectory
def test_gen_env_platform_has_header(caplog, platform_env_yaml: pathlib.Path) -> None:
    """Output must start with '# GENERATED by ai-platform — DO NOT EDIT'.

    ── Scenario: Valid YAML → output header ──
    """
    logger.info("[IMP:9][test][has_header] Starting — script=%s yaml=%s", _GEN_ENV_SCRIPT, platform_env_yaml)

    result = subprocess.run(
        [
            str(_GEN_ENV_SCRIPT),
            "--yaml",
            str(platform_env_yaml),
        ],
        capture_output=True,
        text=True,
        timeout=30,
    )

    logger.info("[IMP:7][test][has_header] Exit code=%d, stdout_len=%d", result.returncode, len(result.stdout))
    assert result.returncode == 0, f"Script failed: stderr={result.stderr}"
    first_line = result.stdout.splitlines()[0]
    assert first_line.startswith("# GENERATED by ai-platform"), (
        f"Expected header starting with '# GENERATED by ai-platform', got: {first_line}"
    )
    logger.info("[IMP:9][test][has_header] Header verified: %s", first_line)


@ldd_trajectory
def test_gen_env_platform_min_vars(caplog, platform_env_yaml: pathlib.Path) -> None:
    """Output must contain ≥8 PLATFORM_* lines.

    ── Scenario: 2-service fixture generates 9+ PLATFORM_* variables ──
    """
    logger.info("[IMP:9][test][min_vars] Starting")

    result = subprocess.run(
        [str(_GEN_ENV_SCRIPT), "--yaml", str(platform_env_yaml)],
        capture_output=True,
        text=True,
        timeout=30,
    )

    assert result.returncode == 0, f"Script failed: stderr={result.stderr}"
    plat_lines = [line for line in result.stdout.splitlines() if line.startswith("PLATFORM_")]
    plat_count = len(plat_lines)
    logger.info("[IMP:7][test][min_vars] PLATFORM_* count=%d", plat_count)
    assert plat_count >= 8, f"Expected ≥8 PLATFORM_* variables, got {plat_count}. Lines: {plat_lines}"
    logger.info("[IMP:9][test][min_vars] Verified: %d PLATFORM_* variables", plat_count)


@ldd_trajectory
def test_gen_env_platform_provides_list(caplog, platform_env_yaml: pathlib.Path) -> None:
    """PLATFORM_PROVIDES must equal sorted keys from provides fixture.

    ── Scenario: Fixture has postgres,redis → PLATFORM_PROVIDES=postgres,redis ──
    """
    logger.info("[IMP:9][test][provides_list] Starting")

    result = subprocess.run(
        [str(_GEN_ENV_SCRIPT), "--yaml", str(platform_env_yaml)],
        capture_output=True,
        text=True,
        timeout=30,
    )

    assert result.returncode == 0, f"Script failed: stderr={result.stderr}"
    provides_line = ""
    for line in result.stdout.splitlines():
        if line.startswith("PLATFORM_PROVIDES="):
            provides_line = line
            break

    assert provides_line, "PLATFORM_PROVIDES not found in output"
    # Expected: sorted keys from fixture = postgres,redis
    expected = "postgres,redis"
    actual = provides_line.split("=", 1)[1]
    assert actual == expected, f"PLATFORM_PROVIDES mismatch: expected '{expected}', got '{actual}'"
    logger.info("[IMP:9][test][provides_list] PLATFORM_PROVIDES=%s", actual)


@ldd_trajectory
def test_gen_env_platform_dsn_format(caplog, platform_env_yaml: pathlib.Path) -> None:
    """DSN must match scheme://user:***@host:port/db pattern.

    ── Scenario: Postgres DSN regex check ──
    """
    import re

    logger.info("[IMP:9][test][dsn_format] Starting")

    result = subprocess.run(
        [str(_GEN_ENV_SCRIPT), "--yaml", str(platform_env_yaml), "--name", "testapp"],
        capture_output=True,
        text=True,
        timeout=30,
    )

    assert result.returncode == 0, f"Script failed: stderr={result.stderr}"

    dsn_line = ""
    for line in result.stdout.splitlines():
        if "PLATFORM_POSTGRES_DSN" in line:
            dsn_line = line
            break

    assert dsn_line, "PLATFORM_POSTGRES_DSN not found in output"
    dsn_value = dsn_line.split("=", 1)[1]

    pattern = r"^\w+://[^:]+:\*\*\*@[^:]+:\d+/\w+$"
    assert re.match(pattern, dsn_value), f"DSN format mismatch: '{dsn_value}' does not match '{pattern}'"
    logger.info("[IMP:9][test][dsn_format] DSN format valid: %s", dsn_value)


@ldd_trajectory
def test_gen_env_platform_dsn_host_is_pgbouncer(caplog, platform_env_yaml: pathlib.Path) -> None:
    """Postgres DSN must use pgbouncer:6432 (O5 regression check — F3).

    ── Scenario: Verify host=pgbouncer, port=6432 in postgres DSN ──
    """
    logger.info("[IMP:9][test][dsn_pgbouncer] Starting — regression guard F3")

    result = subprocess.run(
        [str(_GEN_ENV_SCRIPT), "--yaml", str(platform_env_yaml)],
        capture_output=True,
        text=True,
        timeout=30,
    )

    assert result.returncode == 0, f"Script failed: stderr={result.stderr}"

    host_line = ""
    port_line = ""
    dsn_line = ""
    for line in result.stdout.splitlines():
        if "PLATFORM_POSTGRES_HOST" in line:
            host_line = line
        elif "PLATFORM_POSTGRES_PORT" in line:
            port_line = line
        elif "PLATFORM_POSTGRES_DSN" in line:
            dsn_line = line

    assert host_line, "PLATFORM_POSTGRES_HOST not found"
    assert port_line, "PLATFORM_POSTGRES_PORT not found"
    assert dsn_line, "PLATFORM_POSTGRES_DSN not found"

    host_val = host_line.split("=", 1)[1]
    port_val = port_line.split("=", 1)[1]
    dsn_val = dsn_line.split("=", 1)[1]

    assert host_val == "pgbouncer", f"Expected host=pgbouncer, got {host_val}"
    assert port_val == "6432", f"Expected port=6432, got {port_val}"
    assert "pgbouncer" in dsn_val, f"DSN missing pgbouncer: {dsn_val}"
    assert "6432" in dsn_val, f"DSN missing port 6432: {dsn_val}"

    logger.info(
        "[IMP:9][test][dsn_pgbouncer] Verified: host=%s port=%s dsn=%s",
        host_val,
        port_val,
        dsn_val,
    )


@ldd_trajectory
def test_gen_env_platform_no_proxy_internal(caplog, platform_env_yaml: pathlib.Path) -> None:
    """PLATFORM_NO_PROXY must contain pgbouncer and redis.

    ── Scenario: fixture proxy.no_proxy_internal includes pgbouncer,redis ──
    """
    logger.info("[IMP:9][test][no_proxy] Starting")

    result = subprocess.run(
        [str(_GEN_ENV_SCRIPT), "--yaml", str(platform_env_yaml)],
        capture_output=True,
        text=True,
        timeout=30,
    )

    assert result.returncode == 0, f"Script failed: stderr={result.stderr}"

    no_proxy_line = ""
    for line in result.stdout.splitlines():
        if line.startswith("PLATFORM_NO_PROXY="):
            no_proxy_line = line
            break

    assert no_proxy_line, "PLATFORM_NO_PROXY not found"
    no_proxy_val = no_proxy_line.split("=", 1)[1]

    assert "pgbouncer" in no_proxy_val, f"NO_PROXY missing pgbouncer: {no_proxy_val}"
    assert "redis" in no_proxy_val, f"NO_PROXY missing redis: {no_proxy_val}"
    assert "clickhouse" in no_proxy_val, f"NO_PROXY missing clickhouse: {no_proxy_val}"

    logger.info("[IMP:9][test][no_proxy] Verified NO_PROXY contains pgbouncer,redis,clickhouse: %s", no_proxy_val)


@ldd_trajectory
def test_gen_env_platform_idempotent(caplog, platform_env_yaml: pathlib.Path) -> None:
    """Two runs with same YAML must produce identical output.

    ── Scenario: Same YAML, same env → identical stdout (excluding timestamp line) ──
    """
    logger.info("[IMP:9][test][idempotent] Starting — two runs with same YAML")

    def run_script() -> list[str]:
        result = subprocess.run(
            [str(_GEN_ENV_SCRIPT), "--yaml", str(platform_env_yaml)],
            capture_output=True,
            text=True,
            timeout=30,
        )
        assert result.returncode == 0, f"Script failed: stderr={result.stderr}"
        # Skip timestamp line (different on each run)
        return [line for line in result.stdout.splitlines() if not line.startswith("# Generated:")]

    output1 = run_script()
    output2 = run_script()

    assert output1 == output2, (
        "Idempotency violation: two runs produced different output (ignoring # Generated: timestamp)"
    )
    logger.info("[IMP:9][test][idempotent] Verified: both runs produce identical output (%d lines)", len(output1))


@ldd_trajectory
def test_gen_env_platform_missing_yaml(caplog, tmp_path: pathlib.Path) -> None:
    """Must fail with error when platform-env.yaml does not exist.

    ── Scenario: --yaml points to non-existent file → exit 1, error message ──
    """
    missing_yaml = tmp_path / "nonexistent.yaml"
    logger.info("[IMP:9][test][missing_yaml] Using: %s", missing_yaml)

    result = subprocess.run(
        [str(_GEN_ENV_SCRIPT), "--yaml", str(missing_yaml)],
        capture_output=True,
        text=True,
        timeout=30,
    )

    assert result.returncode != 0, "Expected non-zero exit for missing YAML, got 0"
    assert "not found" in result.stderr.lower() or "not found" in result.stdout.lower(), (
        f"Expected error message about missing file. stdout={result.stdout}, stderr={result.stderr}"
    )
    logger.info("[IMP:9][test][missing_yaml] Verified: exit=%d, stderr=%s", result.returncode, result.stderr.strip())


@ldd_trajectory
def test_gen_env_platform_provides_in_profiles(
    caplog,
    platform_env_yaml_provides_not_in_profiles: pathlib.Path,
) -> None:
    """Provides key NOT in profiles must cause fail-fast (DD8 regression — F8).

    ── Scenario: redis in provides but not in profiles → exit 1, error message with key name ──
    """
    bad_yaml = platform_env_yaml_provides_not_in_profiles
    logger.info("[IMP:9][test][provides_in_profiles] Using bad YAML: %s", bad_yaml)

    result = subprocess.run(
        [str(_GEN_ENV_SCRIPT), "--yaml", str(bad_yaml)],
        capture_output=True,
        text=True,
        timeout=30,
    )

    assert result.returncode != 0, "Expected non-zero exit for provides⊄profiles, got 0"
    error_text = (result.stderr + " " + result.stdout).lower()
    assert "redis" in error_text, (
        f"Expected error to mention the offending key 'redis'. stdout={result.stdout}, stderr={result.stderr}"
    )
    assert "not in profiles" in error_text or "profiles" in error_text, (
        f"Expected error about profiles. stdout={result.stdout}, stderr={result.stderr}"
    )
    logger.info("[IMP:9][test][provides_in_profiles] Verified: fail-fast on provides⊄profiles")
