#!/usr/bin/env python3
# GREP_SUMMARY: practices-generators, render-pyproject, render-precommit, render-conftest, render-test-health, render-lock, compute-generator-hash, GENERATED-header, atomic-write
# STRUCTURE: ▶ render_project_files(language, level) → ⊕ render_pyproject/precommit/conftest/test_health → ⊕ compute_generator_hash (sha256 sorted) → ▶ write_generated_files → ◇ GENERATED-шапка? → ⚡ atomic_write_text → ⊕ render_lock (maturity-снапшот) → ⎋ GENERATED-файлы проекта
# region MODULE_CONTRACT
## @purpose  Рендер GENERATED-файлов практик в каталог проекта (DevPlan 137 §2.1A/§2.1B/§3.3/§3.4):
##           pyproject.toml (ruff baseline/full + pytest), .pre-commit-config.yaml (ТОЛЬКО
##           upstream-репозитории + pre-push хук K5, §3.3), tests/conftest.py (health-фикстура
##           с skip при недоступном сервисе), tests/test_health.py (smoke /health+/ready),
##           practices.lock (version/level/state/maturity-снапшот/generator_hash). Все writes
##           через shared/atomic_writer (единый writer, DevPlan 119 E5). Каждый файл несёт
##           GENERATED-шапку «# GENERATED by ai-platform practices — DO NOT EDIT (make
##           project-sync-practices)»; существующий файл БЕЗ шапки (ручной) → skip + warning.
## @scope    Потребители: sync_practices.py (перегенерация), set_practices.py (level=full →
##           ре-рендер конфигов), project_scaffolder.py (шаг 11), check_project.py (дрейф-хэш),
##           гейт test_gate_practices_generators_deterministic (байт-сверка двойного рендера).
## @invariants
##   - Детерминизм: рендер зависит ТОЛЬКО от (project_name, language, level, pins) — никаких
##     timestamps внутри pyproject/precommit/conftest/test_health (гейт двойного рендера)
##   - GENERATED-шапка в КАЖДОМ файле (дрейф-детект + защита ручного файла)
##   - pre-commit: ТОЛЬКО upstream (pre-commit-hooks, gitleaks, conventional-pre-commit,
##     ruff-pre-commit, shellcheck-py) + local pre-push project-push-check (K5) — платформенных
##     shell-хуков НЕТ (аудит 137: hygiene.sh/commit_msg.sh отклонены)
##   - pre-push хук: entry bash -c 'make project-check PROJECT="$(pwd)"' (делегирование K1)
##   - pyproject: baseline → select=[] (ruff check выключен); full → полный набор правил
##   - Все writes через atomic_write_text (единый writer); skip ручного файла (без шапки)
##   - practices.lock — детерминированный снапшот: generator_hash по §2.1B (sorted files)
## @rationale Один канон рендера вместо копий в 3 шаблонах (дрейф). upstream-хуки — org-agnostic,
##            ноль копий платформенного кода в проекте (аудит 137). atomic_writer — единый
##            канон записи (DevPlan 119 E5).
## @changes  2026-08-05 · DevPlan 137 W1 — создан
# endregion MODULE_CONTRACT

from __future__ import annotations

import hashlib
import logging
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import yaml

from core.internal.practices.escalator import EscalatorDecision
from core.internal.practices.manifest import PracticesManifest
from core.internal.practices.maturity import Maturity
from core.internal.shared.atomic_writer import atomic_write_text

logger = logging.getLogger(__name__)

# ── GENERATED-шапка (единый маркер для дрейф-детекта и защиты ручных файлов) ──
GENERATED_HEADER = "# GENERATED by ai-platform practices — DO NOT EDIT (make project-sync-practices)"

# ── Полный набор правил ruff для FULL (единый источник — рендер pyproject И ruff-check) ──
RUFF_FULL_SELECT: tuple[str, ...] = ("E", "F", "I", "B", "UP", "S", "ANN", "D", "RET", "SIM")
# S101 — assert в тестах; D100 — docstring в __init__; S310 — urllib.urlopen в GENERATED
# health-probe (известный host, ложное срабатывание — иначе noqa в шаблоне ловит RUF100
# платформенного ruff, где S-правила не включены). Отклонение от литерального списка §3.4
# задокументировано: 2 дополнения с обоснованием.
RUFF_FULL_IGNORE: tuple[str, ...] = ("S101", "D100", "S310")

# ── Языки python-семейства (pyproject рендерится только для них) ──
_PYTHON_TYPES: frozenset[str] = frozenset({"python", "backend"})

# ── Относительные пути GENERATED-файлов (AC W1: 5 файлов; practices.lock рендерится
#    отдельно — render_lock требует maturity/decision, поэтому не входит в render_project_files) ──
GENERATED_FILE_PATHS: tuple[str, ...] = (
    "pyproject.toml",
    ".pre-commit-config.yaml",
    "tests/conftest.py",
    "tests/test_health.py",
    "practices.lock",
)


# region FUNC_render_pyproject
## @purpose  Рендер pyproject.toml (ruff + pytest конфиг). ТОЛЬКО для python-языков
##           (python|backend); иначе возвращает "" (файл не генерируется).
##           BASELINE: ruff format (стиль), ruff check отключён (select = [] — агент не
##           гоняется по правкам, §3.4). FULL: полный набор правил + strict-pytest.
## @io       ⇥ project_name: str, language: str, level: str → ⎋ str ("" если language не python)
## @complexity O(1)
## @invariants
##   - baseline: select = [] (явно пусто — детект); addopts = "-q -x --timeout=60"
##   - full: select = RUFF_FULL_SELECT; ignore = RUFF_FULL_IGNORE;
##     addopts = "-q -x --timeout=60 --strict-markers --strict-config"
##   - line-length 120, target py312, quote-style double (всегда — стиль дешёвый)
def render_pyproject(project_name: str, language: str, level: str) -> str:
    """Render pyproject.toml (ruff + pytest) for python projects; "" for non-python."""
    if language not in _PYTHON_TYPES:
        logger.info("[IMP:7][practices_gen][pyproject] language=%s — no pyproject rendered", language)
        return ""

    full = level == "full"
    select_line = (
        "select = [" + ", ".join(f'"{r}"' for r in RUFF_FULL_SELECT) + "]"
        if full
        else "select = []  # baseline: ruff check выключен (только format)"
    )
    ignore_line = (
        "ignore = [" + ", ".join(f'"{r}"' for r in RUFF_FULL_IGNORE) + "]"
        if full
        else "# (baseline: ignore не нужен — select пуст)"
    )
    addopts = "-q -x --timeout=60" if not full else "-q -x --timeout=60 --strict-markers --strict-config"
    markers = "markers = []" if not full else 'markers = ["gate", "contract", "smoke"]'

    content = f"""{GENERATED_HEADER}
# Project: {project_name}
# Source: core/internal/practices/practices_manifest.yaml (pins: ruff_pre_commit)

[tool.ruff]
line-length = 120
target-version = "py312"

[tool.ruff.format]
quote-style = "double"            # всегда (стиль — дешёвый)

[tool.ruff.lint]
# BASELINE: ruff check НИЧЕГО не делает (только format).
# FULL: полный набор правил (см. RUFF_FULL_SELECT в generators.py).
{select_line}
{ignore_line}

[tool.pytest.ini_options]
# BASELINE: -q -x --timeout=60, allow_no_tests (мок без тестов не падает)
# FULL: + strict-markers, strict-config, filterwarnings=error
addopts = "{addopts}"
{markers}
"""
    logger.info(
        "[IMP:8][practices_gen][pyproject] rendered (language=%s level=%s, %d chars)", language, level, len(content)
    )
    return content


# endregion FUNC_render_pyproject


# region FUNC_render_precommit
## @purpose  Рендер .pre-commit-config.yaml проекта: ТОЛЬКО upstream-репозитории (версии из
##           pins канона = версиям платформы) + local pre-push хук project-push-check (K5).
##           НИКАКИХ платформенных shell-хуков (аудит 137: hygiene.sh/commit_msg.sh отклонены).
##           ruff-format — только для python-языков; shellcheck — только для sh.
## @io       ⇥ level: str, language: str → ⎋ str YAML-конфиг pre-commit
## @complexity O(1)
## @invariants
##   - repos: pre-commit-hooks (6 hygiene), gitleaks (system binary), conventional-pre-commit
##     (commit-msg), ruff-pre-commit (ruff-format, python-only), shellcheck-py (sh-only)
##   - pre-push: local project-push-check → bash -c 'make project-check PROJECT="$(pwd)"'
##     (делегирование K1 через PLATFORM_DIR), stages [pre-push], always_run
##   - Версии из pins: pre_commit_hooks, gitleaks, conventional_pre_commit, ruff_pre_commit,
##     shellcheck_py (паритет корневому конфигу платформы — анти-дрейф)
def render_precommit(level: str, language: str, pins: dict[str, str]) -> str:
    """Render .pre-commit-config.yaml (upstream-only + pre-push K5 hook)."""
    pre_commit_hooks = pins.get("pre_commit_hooks", "v6.0.0")
    gitleaks = pins.get("gitleaks", "v8.30.1")
    conventional = pins.get("conventional_pre_commit", "v4.4.0")
    ruff = pins.get("ruff_pre_commit", "0.16.1")
    shellcheck = pins.get("shellcheck_py", "v0.11.0.1")

    lines: list[str] = [
        GENERATED_HEADER,
        "# Source: core/internal/practices/practices_manifest.yaml v1 (pins)",
        "# GREP_SUMMARY: pre-commit, gitleaks, ruff-format, shellcheck, conventional-pre-commit, pre-push, project-push-check, upstream",
        "# STRUCTURE: ┌upstream repos (pins)┐ → ◇ hygiene hooks → ◇ gitleaks → ◇ commit-msg → ◇ ruff-format → ◇ shellcheck → ◇ pre-push project-push-check (K5) → ⎋ project pre-commit",
        "# region MODULE_CONTRACT",
        "## @purpose  Pre-commit-конфиг проекта (GENERATED): ТОЛЬКО upstream-репозитории (версии",
        "##           из pins канона — паритет платформе) + pre-push K5 хук (make project-check).",
        "# endregion MODULE_CONTRACT",
        "repos:",
        f"  - repo: https://github.com/pre-commit/pre-commit-hooks   # rev: из pins ({pre_commit_hooks})",
        "    hooks:",
        "      - id: trailing-whitespace",
        "      - id: end-of-file-fixer",
        "      - id: check-merge-conflict",
        "      - id: detect-private-key",
        "      - id: check-toml",
        "      - id: check-json",
        f"  - repo: https://github.com/gitleaks/gitleaks             # rev: из pins ({gitleaks})",
        "    hooks:",
        "      - id: gitleaks          # language: system, entry: gitleaks git --pre-commit",
        f"  - repo: https://github.com/compilerla/conventional-pre-commit  # rev: из pins ({conventional})",
        "    hooks:",
        "      - id: conventional-pre-commit                       # stages: [commit-msg]",
    ]
    if language in _PYTHON_TYPES:
        lines.extend(
            [
                "# ─── language-specific (baseline) ───",
                f"  - repo: https://github.com/astral-sh/ruff-pre-commit    # rev: из pins ({ruff})",
                "    hooks:",
                "      - id: ruff-format          # baseline: только format; ruff-check — full-only (project-check/CI)",
            ]
        )
    if language == "sh":
        lines.extend(
            [
                "# ─── sh-only (baseline) ───",
                f"  - repo: https://github.com/shellcheck-py/shellcheck-py  # rev: из pins ({shellcheck})",
                "    hooks:",
                "      - id: shellcheck",
            ]
        )
    lines.extend(
        [
            "# ─── pre-push: maturity-проверка (K5, решение пользователя 2026-08-05) ───",
            "  - repo: local",
            "    hooks:",
            "      - id: project-push-check",
            "        name: practices maturity + level checks (project-check)",
            "        entry: bash -c 'make project-check PROJECT=\"$(pwd)\"'   # делегирование K1 (PLATFORM_DIR)",
            "        language: system",
            "        stages: [pre-push]",
            "        always_run: true",
            "",
        ]
    )
    content = "\n".join(lines)
    logger.info("[IMP:8][practices_gen][precommit] rendered (language=%s, %d lines)", language, len(lines))
    return content


# endregion FUNC_render_precommit


# region FUNC_render_conftest
## @purpose  Рендер tests/conftest.py: чтение .env.platform (без перезаписи существующих env)
##           + health-фикстура (TCP-probe до PROBE_HOST:PROBE_PORT) с pytest.skip при
##           недоступном сервисе — иначе AC1 («project-check зелёный на новом проекте»)
##           нарушается (DevPlan 137 §3.2 замечание про test_health).
## @io       ⇥ project_name: str → ⎋ str Python-код conftest.py
## @complexity O(1)
## @invariants
##   - .env.platform читается только если существует (mock без .env.platform не падает)
##   - health_url фикстура: TCP-probe 2s → OSError → pytest.skip("service not running")
##   - Не перезаписывает уже установленные переменные окружения (setdefault)
def render_conftest(project_name: str) -> str:
    """Render tests/conftest.py (env loading + health fixture with skip).

    ⚠️ Построение ПОСТРОЧНО (список строк), НЕ одним f-string-блоком: содержимое содержит
    `# region`/`# endregion`/`# GREP_SUMMARY` — строки-комментарии внутри f-string ломают
    doxygen-парсер (Found unexpanded alias). Списочная конструкция — как render_precommit.
    """
    lines: list[str] = [
        GENERATED_HEADER,
        f"# Project: {project_name}",
        "# GREP_SUMMARY: conftest, .env.platform, health-fixture, tcp-probe, skip",
        "# STRUCTURE: ┌.env.platform (setdefault)┐ → ◇ TCP-probe → ◇ OSError → skip → ⎋ health_url",
        "# region MODULE_CONTRACT",
        "# endregion MODULE_CONTRACT",
        '"""pytest conftest — платформенный health-fixture (GENERATED)."""',
        "",
        "import os",
        "import socket",
        "from pathlib import Path",
        "",
        "import pytest",
        "",
        "",
        "def _load_env_platform() -> None:",
        '    """Load .env.platform into os.environ (не перезаписывая существующие)."""',
        '    env_file = Path(__file__).resolve().parent.parent / ".env.platform"',
        "    if not env_file.is_file():",
        "        return",
        '    for line in env_file.read_text(encoding="utf-8").splitlines():',
        "        line = line.strip()",
        '        if not line or line.startswith("#") or "=" not in line:',
        "            continue",
        '        key, _, value = line.partition("=")',
        "        os.environ.setdefault(key.strip(), value.strip())",
        "",
        "",
        "_load_env_platform()",
        "",
        "",
        '@pytest.fixture(scope="session")',
        "def health_url() -> str:",
        '    """Health-URL сервиса: TCP-probe до PROBE_HOST:PROBE_PORT → skip, если сервис не запущен."""',
        '    host = os.environ.get("PROBE_HOST", "localhost")',
        '    port = int(os.environ.get("PROBE_PORT", "80"))',
        "    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:",
        "        sock.settimeout(2.0)",
        "        try:",
        "            sock.connect((host, port))",
        "        except OSError:",
        '            pytest.skip("service not running")',
        '    return f"http://{host}:{port}"',
    ]
    content = "\n".join(lines) + "\n"
    logger.info("[IMP:8][practices_gen][conftest] rendered (%d chars)", len(content))
    return content


# endregion FUNC_render_conftest


# region FUNC_render_test_health
## @purpose  Рендер tests/test_health.py: smoke-проверки /health и /ready через health_url
##           фикстуру (stdlib urllib — без внешних зависимостей; skip при недоступном сервисе).
## @io       ⎋ str Python-код test_health.py
## @complexity O(1)
## @invariants
##   - Только stdlib (urllib) — проект не тянет requests
##   - Тесты используют health_url фикстуру → на свежем моке (сервис не запущен) → skip
def render_test_health() -> str:
    """Render tests/test_health.py (smoke /health + /ready).

    ⚠️ Построение построчно (список строк) — см. render_conftest (doxygen-safe).
    """
    lines: list[str] = [
        GENERATED_HEADER,
        "# GREP_SUMMARY: smoke, health, ready, endpoint, urllib, skip",
        "# STRUCTURE: ┌health_url fixture (TCP-probe)┐ → ◇ GET /health → ◇ GET /ready → ⎋ 200 asserts",
        "# region MODULE_CONTRACT",
        "# endregion MODULE_CONTRACT",
        '"""Smoke health tests (GENERATED) — пропускаются, если сервис не запущен."""',
        "",
        "import urllib.request",
        "",
        "",
        "def _get_status(url: str, path: str) -> int:",
        '    """GET url+path → HTTP status (raises on connection error)."""',
        '    with urllib.request.urlopen(f"{url}{path}", timeout=5) as resp:',
        "        return resp.status",
        "",
        "",
        "def test_health_endpoint(health_url: str) -> None:",
        '    """GET /health → 200 (skip, если сервис не запущен)."""',
        '    assert _get_status(health_url, "/health") == 200',
        "",
        "",
        "def test_ready_endpoint(health_url: str) -> None:",
        '    """GET /ready → 200 (skip, если сервис не запущен)."""',
        '    assert _get_status(health_url, "/ready") == 200',
    ]
    content = "\n".join(lines) + "\n"
    logger.info("[IMP:8][practices_gen][test_health] rendered (%d chars)", len(content))
    return content


# endregion FUNC_render_test_health


# region FUNC_render_project_files
## @purpose  Отрендерить ВСЕ GENERATED-файлы практик для проекта: {относительный путь → текст}.
##           pyproject.toml — только python-языки; pre-commit/conftest/test_health — всегда.
##           Порядок ключей = порядок GENERATED_FILE_PATHS (детерминизм hash).
## @io       ⇥ project_name: str, language: str, level: str, pins: dict → ⎋ dict[str, str]
## @complexity O(1)
## @invariants
##   - Ключи — относительные пути (как в practices.lock files)
##   - Детерминизм: тот же вход → тот же dict (гейт байт-сверки двойного рендера)
def render_project_files(
    project_name: str,
    language: str,
    level: str,
    pins: dict[str, str],
) -> dict[str, str]:
    """Render all GENERATED practices files → {relative_path: content}."""
    files: dict[str, str] = {}
    pyproject = render_pyproject(project_name, language, level)
    if pyproject:
        files["pyproject.toml"] = pyproject
    files[".pre-commit-config.yaml"] = render_precommit(level, language, pins)
    files["tests/conftest.py"] = render_conftest(project_name)
    files["tests/test_health.py"] = render_test_health()
    # tsconfig.json/.eslintrc — static payload в template-frontend/, НЕ GENERATED (DevPlan 141).
    # Не требуют рендера из practices_manifest — проектно-специфичные конфиги
    # (eslint.config.js flat config, eslint 9+). Ручная правка не детектится drift-гейтом —
    # это осознанный выбор: конфиги принадлежат проекту, не канону практик.
    logger.info(
        "[IMP:9][practices_gen][files] rendered %d GENERATED files (language=%s level=%s)",
        len(files),
        language,
        level,
    )
    return files


# endregion FUNC_render_project_files


# region FUNC_compute_generator_hash
## @purpose  Детерминированный hash отрендеренных GENERATED-файлов (DevPlan 137 §2.1B) —
##           drift-detect: sha256("v{version}:{level}\n" + Σ sorted "path=sha256(content)\n").
## @io       ⇥ files: dict[str, str] (path → content), version: int, level: str → ⎋ str "sha256:..."
## @complexity O(N * C) где N = число файлов, C = размер контента
## @invariants
##   - sorted(files) — детерминизм (порядок итерации не важен)
##   - Уровень входит в hash (baseline vs full конфиги различны)
def compute_generator_hash(files: dict[str, str], version: int, level: str) -> str:
    """Deterministic hash of rendered GENERATED files (drift-detect)."""
    h = hashlib.sha256()
    h.update(f"v{version}:{level}\n".encode())
    for path in sorted(files):  # sorted = детерминизм
        h.update(f"{path}={hashlib.sha256(files[path].encode()).hexdigest()}\n".encode())
    result = f"sha256:{h.hexdigest()}"
    logger.info(
        "[IMP:9][practices_gen][hash] generator_hash=%s (v%d, level=%s, %d files)", result, version, level, len(files)
    )
    return result


# endregion FUNC_compute_generator_hash


# region FUNC_PracticesLock
## @purpose  Frozen-dataclass practices.lock проекта (DevPlan 137 §2.1B) — снапшот канона +
##           состояние эскалатора + maturity-снапшот (носитель для VPS, где git недоступен).
## @io       ⇥ version/level/state/language/generator_hash/maturity/files/generated_at → ⎋ PracticesLock
## @complexity O(1)
@dataclass(frozen=True)
class PracticesLock:
    """Project practices.lock snapshot (canon + escalator state + maturity)."""

    version: int
    level: str
    state: str
    language: str
    generator_hash: str
    maturity: dict[str, int]
    files: dict[str, str]
    generated_at: str


# endregion FUNC_PracticesLock


# region FUNC_render_lock
## @purpose  Рендер practices.lock (DevPlan 137 §2.1B формат): version, level, state, maturity
##           (снапшот — для VPS), generated_at (UTC ISO8601), generator_hash, language, files
##           (path → sha256 содержимого). maturity-снапшот ОБЯЗАТЕЛЕН (носитель для K3).
## @io       ⇥ manifest: PracticesManifest, level_setting: str, decision: EscalatorDecision,
##           maturity: Maturity, files: dict[str, str] (rendered content), language: str,
##           generated_at: str | None → ⎋ str YAML-контент lock
## @complexity O(N * C)
## @invariants
##   - Порядок полей фиксирован (yaml.safe_dump sort_keys=False, insertion order)
##   - files: path → sha256(rendered content) — содержимое НЕ в lock (только hash)
##   - generator_hash = compute_generator_hash(files, version, level_setting)
def render_lock(
    manifest: PracticesManifest,
    level_setting: str,
    decision: EscalatorDecision,
    maturity: Maturity,
    files: dict[str, str],
    language: str,
    generated_at: str | None = None,
) -> str:
    """Render practices.lock content (deterministic snapshot)."""
    stamp = generated_at or datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    file_hashes = {path: f"sha256:{hashlib.sha256(content.encode()).hexdigest()}" for path, content in files.items()}
    generator_hash = compute_generator_hash(files, manifest.version, level_setting)

    data: dict[str, Any] = {
        "version": manifest.version,
        "level": level_setting,
        "state": decision.state_name,
        "maturity": {"age_days": maturity.age_days, "code_files": maturity.code_files},
        "generated_at": stamp,
        "generator_hash": generator_hash,
        "language": language,
        "files": file_hashes,
    }
    body = yaml.safe_dump(data, sort_keys=False, allow_unicode=True, default_flow_style=False)
    content = (
        f"{GENERATED_HEADER}\n# GREP_SUMMARY: practices.lock, version, level, state, generator_hash, maturity\n{body}"
    )
    logger.info(
        "[IMP:9][practices_gen][lock] rendered lock (level=%s state=%s maturity=%dd/%dfiles)",
        level_setting,
        decision.state_name,
        maturity.age_days,
        maturity.code_files,
    )
    return content


# endregion FUNC_render_lock


# region FUNC_read_lock
## @purpose  Прочитать practices.lock проекта → PracticesLock | None (None при отсутствии/битом
##           файле — legacy-проект → grace-режим K3). НЕ мутирует.
## @io       ⇥ project_dir: Path → ⎋ PracticesLock | None
## @complexity O(1)
def read_lock(project_dir: Path) -> PracticesLock | None:
    """Read project practices.lock (None if missing/unparseable — legacy project)."""
    lock_path = Path(project_dir) / "practices.lock"
    if not lock_path.is_file():
        logger.info("[IMP:7][practices_gen][lock_read] practices.lock not found: %s", lock_path)
        return None
    try:
        data = yaml.safe_load(lock_path.read_text(encoding="utf-8")) or {}
    except (OSError, yaml.YAMLError) as exc:
        logger.warning("[IMP:7][practices_gen][lock_read] practices.lock unparseable (%s)", exc)
        return None
    if not isinstance(data, dict):
        logger.warning("[IMP:7][practices_gen][lock_read] practices.lock not a dict — ignored")
        return None
    maturity_raw = data.get("maturity") or {}
    files_raw = data.get("files") or {}
    lock = PracticesLock(
        version=int(data.get("version", 0)),
        level=str(data.get("level", "auto")),
        state=str(data.get("state", "baseline")),
        language=str(data.get("language", "")),
        generator_hash=str(data.get("generator_hash", "")),
        maturity={
            "age_days": int(maturity_raw.get("age_days", 0)),
            "code_files": int(maturity_raw.get("code_files", 0)),
        },
        files={str(k): str(v) for k, v in files_raw.items()},
        generated_at=str(data.get("generated_at", "")),
    )
    logger.info("[IMP:8][practices_gen][lock_read] lock read (v%d state=%s)", lock.version, lock.state)
    return lock


# endregion FUNC_read_lock


# region FUNC_write_generated_file
## @purpose  Атомарная запись GENERATED-файла через atomic_write_text (DevPlan 119 E5).
##           Существующий файл БЕЗ GENERATED-шапки (ручной, не нами сгенерированный) →
##           skip + warning «manual file detected» (риск перезаписи пользовательского,
##           DevPlan 137 §7). force=True → перезаписать в любом случае.
## @io       ⇥ path: Path, content: str, force: bool → ⎋ str — "written" | "updated" | "skipped"
## @complexity O(C) где C = len(content)
## @invariants
##   - Шапка есть в контенте (assert — fail-fast на генераторный баг)
##   - Skip не создаёт файл (если отсутствует — пишется)
def write_generated_file(path: Path, content: str, *, force: bool = False) -> str:
    """Write GENERATED file atomically; skip existing manual file (no header) unless force."""
    if GENERATED_HEADER not in content:
        # Типизированная ошибка (гейт no_bare_raise: bare ValueError запрещён в core/)
        from core.internal.shared.exceptions import ConfigValidationError

        raise ConfigValidationError(f"Generated file missing GENERATED header: {path}")
    if path.is_file():
        existing = path.read_text(encoding="utf-8")
        if GENERATED_HEADER not in existing and not force:
            logger.info(
                "[IMP:9][practices_gen][write] SKIP manual file (no GENERATED header): %s — не перезаписан",
                path,
            )
            return "skipped"
        atomic_write_text(path, content)
        logger.info("[IMP:9][practices_gen][write] Updated: %s", path)
        return "updated"
    path.parent.mkdir(parents=True, exist_ok=True)
    atomic_write_text(path, content)
    logger.info("[IMP:9][practices_gen][write] Written: %s", path)
    return "written"


# endregion FUNC_write_generated_file


# region FUNC_write_lock_file
## @purpose  Записать practices.lock через write_generated_file (GENERATED-шапка + атомарность).
## @io       ⇥ project_dir: Path, content: str, force: bool → ⎋ str — "written"|"updated"|"skipped"
## @complexity O(C)
def write_lock_file(project_dir: Path, content: str, *, force: bool = False) -> str:
    """Write practices.lock atomically (GENERATED header enforced)."""
    return write_generated_file(Path(project_dir) / "practices.lock", content, force=force)


# endregion FUNC_write_lock_file
