#!/usr/bin/env python3
# GREP_SUMMARY: practices-maturity, age, first-commit, code-files, excludes, thresholds, git-log, mtime-fallback
# STRUCTURE: ▶ compute_maturity(project_dir) → ⊕ age (git log --reverse → fallback ai-platform.yaml commit → mtime) → ⊕ code_files (walk {py,ts,tsx,js,jsx,sh} с исключениями) → ⎋ Maturity(age_days, code_files)
# region MODULE_CONTRACT
## @purpose  Зрелость проекта (DevPlan 137 §4.1): возраст (первый коммит git; fallback — первый
##           коммит, добавивший ai-platform.yaml; затем mtime файла — решение пользователя
##           «дата создания определяется скриптом по файлам платформы в этом проекте») и
##           счётчик файлов кода (НЕ библиотек, с исключениями). Вычисляется ТОЛЬКО там, где
##           есть git (локально K1/K5, CI K2); НЕ вызывается на VPS (нет git — maturity из
##           practices.lock снапшота).
## @scope    Потребители: check_project.py, sync_practices.py, escalator.py, gen_project_platform_md.py.
##           W1-скоуп: полная реализация §4.1 (нужна для render_lock maturity-снапшота и
##           [PRACTICES:PROPOSE] в check_project); W3 расширяет аудит/интеграцию.
## @invariants
##   - age_days: первый коммит (git log --reverse --format=%aI) → fallback первый коммит
##     ai-platform.yaml (git log --follow --diff-filter=A) → mtime ai-platform.yaml → 0 (нет git)
##   - code_files: расширения {py, ts, tsx, js, jsx, sh} в src/, backend/, frontend/, app/,
##     tests/, scripts/, корень; ИСКЛЮЧАЯ node_modules, .venv, dist, build, coverage, .next,
##     __pycache__, .git, *.lock, package-lock.json, .env*, *.min.js, GENERATED-файлы практик
##   - НЕ мутирует проект; read-only (git log / walk)
## @rationale Пороги 30 дней / 50 файлов (решение пользователя 2026-08-05). Автопромоута нет —
##            maturity только даёт is_propose() сигнал эскалатору.
## @changes  2026-08-05 · DevPlan 137 W1 — создан (полная §4.1 семантика)
# endregion MODULE_CONTRACT

from __future__ import annotations

import logging
import os
import subprocess
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

logger = logging.getLogger(__name__)

# ── Расширения файлов кода (НЕ библиотек) ──
_CODE_EXTENSIONS: frozenset[str] = frozenset({".py", ".ts", ".tsx", ".js", ".jsx", ".sh"})

# ── Директории, исключаемые из подсчёта (библиотеки/артефакты) ──
_EXCLUDED_DIRS: frozenset[str] = frozenset(
    {
        "node_modules",
        ".venv",
        "venv",
        "dist",
        "build",
        "coverage",
        ".next",
        "__pycache__",
        ".git",
        ".pytest_cache",
        ".ruff_cache",
        ".mypy_cache",
    }
)

# ── Файлы-исключения ──
_EXCLUDED_FILES: frozenset[str] = frozenset({"package-lock.json"})

# ── Суффиксы-исключения ──
_EXCLUDED_SUFFIXES: tuple[str, ...] = (".lock", ".min.js")

# ── GENERATED-файлы практик (не считаются кодом проекта) ──
_GENERATED_PRACTICE_FILES: frozenset[str] = frozenset(
    {"pyproject.toml", ".pre-commit-config.yaml", "practices.lock", "tests/conftest.py", "tests/test_health.py"}
)

_GENERATED_HEADER = "# GENERATED by ai-platform practices"

# git log fallback-порог: если git недоступен/репозиторий пуст → mtime fallback
_GIT_TIMEOUT_SEC = 5


# region FUNC_Maturity
## @purpose  Frozen-снапшот зрелости проекта (DevPlan 137 §2.1A): возраст + файлы кода.
## @io       ⇥ age_days: int, code_files: int → ⎋ Maturity
## @complexity O(1)
@dataclass(frozen=True)
class Maturity:
    """Maturity snapshot of a project (age_days, code_files)."""

    age_days: int
    code_files: int

    ## @purpose  Суммарная зрелость для is_propose: возраст ИЛИ файлы превысили порог.
    ## @io       ⇥ thresholds: dict[str, int] → ⎋ bool
    ## @complexity O(1)
    def is_propose(self, thresholds: dict[str, int]) -> bool:
        """True if age > age_days_propose OR code_files > code_files_propose."""
        age_propose = int(thresholds.get("age_days_propose", 30))
        files_propose = int(thresholds.get("code_files_propose", 50))
        return self.age_days > age_propose or self.code_files > files_propose

    ## @purpose  Человекочитаемая причина для [PRACTICES:PROPOSE][reason:...].
    ## @io       ⇥ thresholds: dict[str, int] → ⎋ str — "age=41d,files=87"
    ## @complexity O(1)
    def reason(self, thresholds: dict[str, int]) -> str:
        """Render maturity reason string (age=41d,files=87) for PROPOSE warnings."""
        return f"age={self.age_days}d,files={self.code_files}"


# endregion FUNC_Maturity


# region FUNC_compute_maturity
## @purpose  Вычислить зрелость проекта: age (git-цепочка с mtime fallback) + code_files (walk).
## @io       ⇥ project_dir: Path → ⎋ Maturity
## @complexity O(F) где F = число файлов в дереве проекта (walk) + O(1) git
## @invariants
##   - read-only: НЕ пишет в проект, НЕ мутирует git
##   - git недоступен / репозиторий без коммитов → mtime fallback (ai-platform.yaml) → 0
def compute_maturity(project_dir: Path) -> Maturity:
    """Compute project maturity (age_days + code_files), local/CI only (git required)."""
    project_dir = Path(project_dir)
    age_days = _compute_age_days(project_dir)
    code_files = _count_code_files(project_dir)
    maturity = Maturity(age_days=age_days, code_files=code_files)
    logger.info(
        "[IMP:9][practices_maturity][compute] maturity=%s (age=%dd, files=%d)",
        maturity.reason({}),
        maturity.age_days,
        maturity.code_files,
    )
    return maturity


# endregion FUNC_compute_maturity


# region FUNC__compute_age_days
## @purpose  Возраст проекта в днях: (1) первый коммит репозитория (git log --reverse
##           --format=%aI), (2) fallback — первый коммит, добавивший ai-platform.yaml
##           (git log --follow --diff-filter=A), (3) fallback — mtime ai-platform.yaml,
##           (4) нет git/файла → 0 (свежий проект). Решение пользователя: «дата создания
##           определяется скриптом по файлам платформы в этом проекте».
## @io       ⇥ project_dir: Path → ⎋ int — возраст в днях (>= 0)
## @complexity O(1) — 1-2 git log + stat
def _compute_age_days(project_dir: Path) -> int:
    """Compute project age in days (first commit → ai-platform.yaml commit → mtime → 0)."""
    first_commit = _git_first_commit(project_dir)
    if first_commit is None:
        first_commit = _git_first_commit(project_dir, path="ai-platform.yaml", follow=True)
    if first_commit is None:
        yaml_file = project_dir / "ai-platform.yaml"
        if yaml_file.is_file():
            try:
                first_commit = datetime.fromtimestamp(yaml_file.stat().st_mtime, tz=timezone.utc)
            except OSError:
                first_commit = None
    if first_commit is None:
        logger.info("[IMP:7][practices_maturity][age] No git / ai-platform.yaml — age=0 (fresh project)")
        return 0
    age_days = max(0, (datetime.now(timezone.utc) - first_commit).days)
    logger.info("[IMP:8][practices_maturity][age] first=%s age_days=%d", first_commit.isoformat(), age_days)
    return age_days


# endregion FUNC__compute_age_days


# region FUNC__git_first_commit
## @purpose  Первый коммит репозитория проекта (ISO8601 commit date) или None.
##           --reverse → первый (старейший); fallback для конкретного пути — --follow
##           --diff-filter=A (первый коммит, добавивший файл).
## @io       ⇥ project_dir: Path, path: str | None, follow: bool → ⎋ datetime | None
## @complexity O(1) — git log
## @invariants
##   - git недоступен / репозиторий без коммитов → None (тихий fallback, НЕ исключение)
# ⚠️ TRAP[BUG] · 2026-08-05 · P2 · --follow вставлялся до 'log' (git-global опция) → fallback-ветка
# · Symptom: git log с path возвращал None (rc=129 'unknown option: --follow') → первый коммит
# ·   ai-platform.yaml НИКОГДА не резолвился (цепочка §4.1 молча падала на mtime)
# · Root: cmd.insert(3, "--follow") ставил опцию ПОСЛЕ '-C DIR' и ДО подкоманды 'log' —
# ·   git трактует её как глобальную (валидны только -C/-c/--git-dir/...); --follow — опция log
# · Fix: вставка на индекс 4 (после 'log'): git -C dir log --reverse --follow --format=%aI ...
# · Prevention: unit-тест test_maturity_ai_platform_yaml_commit_fallback покрывает fallback-ветку
def _git_first_commit(project_dir: Path, path: str | None = None, follow: bool = False) -> datetime | None:
    """Return first commit datetime of repo (or of path) via git log, None on any failure."""
    cmd = ["git", "-C", str(project_dir), "log", "--reverse", "--format=%aI"]
    if path:
        cmd.extend(["--diff-filter=A", "--", path])
        if follow:
            cmd.insert(4, "--follow")  # после 'log' (индекс 4) — опция log, НЕ git-global
    try:
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=_GIT_TIMEOUT_SEC, check=False)
    except (OSError, subprocess.TimeoutExpired):
        logger.info("[IMP:6][practices_maturity][git] git log unavailable — age fallback")
        return None
    if result.returncode != 0:
        logger.info("[IMP:6][practices_maturity][git] git log rc=%d — age fallback", result.returncode)
        return None
    lines = [ln.strip() for ln in result.stdout.splitlines() if ln.strip()]
    if not lines:
        return None
    try:
        return datetime.fromisoformat(lines[0].replace("Z", "+00:00"))
    except ValueError:
        logger.warning("[IMP:6][practices_maturity][git] unparseable commit date: %s", lines[0])
        return None


# endregion FUNC__git_first_commit


# region FUNC__count_code_files
## @purpose  Счётчик файлов кода проекта (НЕ библиотек): расширения {py,ts,tsx,js,jsx,sh}
##           с исключениями каталогов (node_modules/.venv/dist/build/coverage/.next/...),
##           файлов (*.lock, package-lock.json, .env*, *.min.js) и GENERATED-файлов практик.
## @io       ⇥ project_dir: Path → ⎋ int — число файлов кода
## @complexity O(F) где F = число файлов в дереве (os.walk)
## @invariants
##   - Исключения из DevPlan 137 §4.1: node_modules, .venv, dist, build, coverage, .next,
##     *.lock, package-lock.json, .env*, generated-файлы практик, *.min.js
##   - Файл, начинающийся с GENERATED-шапки практик, НЕ считается кодом (дрейф-защита)
def _count_code_files(project_dir: Path) -> int:
    """Count code files (src/backend/frontend/app/tests/scripts/root), excluding deps/artifacts."""
    count = 0
    for root, dirs, files in os.walk(project_dir):
        root_path = Path(root)
        dirs[:] = [d for d in dirs if d not in _EXCLUDED_DIRS]
        for name in files:
            path = root_path / name
            if name in _EXCLUDED_FILES:
                continue
            if name.endswith(_EXCLUDED_SUFFIXES):
                continue
            if name.startswith(".env"):
                continue
            if path.suffix.lower() not in _CODE_EXTENSIONS:
                continue
            rel = path.relative_to(project_dir)
            if str(rel) in _GENERATED_PRACTICE_FILES:
                continue
            # GENERATED-заглушки практик (первая строка — GENERATED-шапка) — НЕ код проекта
            try:
                with open(path, encoding="utf-8", errors="ignore") as f:
                    first_line = f.readline()
                if first_line.startswith(_GENERATED_HEADER):
                    continue
            except OSError:
                pass
            count += 1
    logger.info("[IMP:8][practices_maturity][files] code_files=%d (%s)", count, project_dir)
    return count


# endregion FUNC__count_code_files
