# GENERATED by ai-platform practices — DO NOT EDIT (make project-sync-practices)
# Project: {{PROJECT_NAME}}
# GREP_SUMMARY: conftest, .env.platform, health-fixture, tcp-probe, skip
# STRUCTURE: ┌.env.platform (setdefault)┐ → ◇ TCP-probe → ◇ OSError → skip → ⎋ health_url
# region MODULE_CONTRACT
# endregion MODULE_CONTRACT
"""pytest conftest — платформенный health-fixture (GENERATED)."""

import os
import socket
from pathlib import Path

import pytest


def _load_env_platform() -> None:
    """Load .env.platform into os.environ (не перезаписывая существующие)."""
    env_file = Path(__file__).resolve().parent.parent / ".env.platform"
    if not env_file.is_file():
        return
    for line in env_file.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        os.environ.setdefault(key.strip(), value.strip())


_load_env_platform()


@pytest.fixture(scope="session")
def health_url() -> str:
    """Health-URL сервиса: TCP-probe до PROBE_HOST:PROBE_PORT → skip, если сервис не запущен."""
    host = os.environ.get("PROBE_HOST", "localhost")
    port = int(os.environ.get("PROBE_PORT", "80"))
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
        sock.settimeout(2.0)
        try:
            sock.connect((host, port))
        except OSError:
            pytest.skip("service not running")
    return f"http://{host}:{port}"
