# GENERATED by ai-platform practices — DO NOT EDIT (make project-sync-practices)
# GREP_SUMMARY: smoke, health, ready, endpoint, urllib, skip
# STRUCTURE: ┌health_url fixture (TCP-probe)┐ → ◇ GET /health → ◇ GET /ready → ⎋ 200 asserts
# region MODULE_CONTRACT
# endregion MODULE_CONTRACT
"""Smoke health tests (GENERATED) — пропускаются, если сервис не запущен."""

import urllib.request


def _get_status(url: str, path: str) -> int:
    """GET url+path → HTTP status (raises on connection error)."""
    with urllib.request.urlopen(f"{url}{path}", timeout=5) as resp:
        return resp.status


def test_health_endpoint(health_url: str) -> None:
    """GET /health → 200 (skip, если сервис не запущен)."""
    assert _get_status(health_url, "/health") == 200


def test_ready_endpoint(health_url: str) -> None:
    """GET /ready → 200 (skip, если сервис не запущен)."""
    assert _get_status(health_url, "/ready") == 200
