#!/usr/bin/env bash
# GREP_SUMMARY: gen-env-platform env-generator platform-env yaml-dotenv provides profiles pgbouncer
# STRUCTURE: ▶ init → parse_args → python3: read YAML → validate provides⊆profiles → generate PLATFORM_* vars → stdout
# region MODULE_CONTRACT
## @purpose  Generate .env.platform from platform-env.yaml — the canonical runtime environment
##           contract consumed by project docker-compose.yml via env_file.
## @scope    Called from scaffold.sh (project-sync-env) and add-project.sh.
## @io       stdout: .env.platform content (PLATFORM_* variables)
##           stderr: LDD logs via log_imp at IMP:7-10; fail-fast errors
## @invariants
##   - provides: keys MUST be subset of profiles (fail-fast with key name)
##   - Postgres DSN uses pgbouncer:6432 (O5), NEVER postgres:6432
##   - Output starts with "# GENERATED by ai-platform — DO NOT EDIT"
##   - Idempotent: same YAML → identical output (modulo timestamp header)
##   - ≥8 PLATFORM_* variables (gate test validates)
## @rationale Single source of truth for project environment — generated from
##            platform-env.yaml provides: section. Eliminates manual .env management
##            in 20+ projects. Uses python3+yaml for reliable YAML parsing.
## @links    USES: platform-env.yaml (canonical provides/proxy/profiles)
##           USED_BY: scaffold.sh project-sync-env, add-project.sh, project Makefile sync-env
## @changes  2026-07-17 · T7 — Initial implementation
# endregion MODULE_CONTRACT

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────────
# CONFIG
# ──────────────────────────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLATFORM_ROOT="${PLATFORM_ROOT:-$(cd "${SCRIPT_DIR}/../../.." 2>/dev/null && pwd || dirname "$(dirname "$(dirname "$SCRIPT_DIR")")")}"
DEFAULT_YAML="${PLATFORM_ROOT}/platform-env.yaml"

__LOG_PREFIX="gen-env-platform"
source "${PLATFORM_ROOT}/core/lib/logging.sh"

# ──────────────────────────────────────────────────────────────────────────────
# region FUNC_usage
## @purpose  Print usage guide for gen-env-platform.sh
## @io       stdout: usage text
## @complexity O(1)
usage() {
    cat <<'HELP'
USAGE: gen-env-platform.sh [OPTIONS]

Generate .env.platform from platform-env.yaml — the canonical runtime
environment contract for projects.

OPTIONS:
  --yaml <path>       Path to platform-env.yaml (default: <platform_root>/platform-env.yaml)
  --name <name>       Project name for DSN substitution (replaces ${NAME} placeholder)
  --domain <domain>   Override PLATFORM_DOMAIN (default: $PLATFORM_DOMAIN env or tronyx.ru)
  --output <path>     Write output to file instead of stdout
  --help              Show this help message

EXAMPLES:
  gen-env-platform.sh
  gen-env-platform.sh --name myapp --domain example.com
  gen-env-platform.sh --yaml /path/to/platform-env.yaml --output .env.platform

VALIDATION:
  - Fails fast if any provides: key is not in profiles:
  - Output ≥8 PLATFORM_* variables
  - Postgres DSN always uses pgbouncer:6432
HELP
}
# endregion FUNC_usage

# ──────────────────────────────────────────────────────────────────────────────
# region FUNC_generate
## @purpose  Core generator: read platform-env.yaml, validate, emit .env.platform
## @param $1  Path to platform-env.yaml
## @param $2  Optional project name for ${NAME} DSN substitution
## @param $3  Optional domain override
## @io       stdout: generated .env.platform content
##           stderr: LDD logs IMP:7-10
## @complexity O(n) where n = number of services in provides:
generate() {
    local yaml_path="$1"
    local project_name="${2:-}"
    local domain="${3:-}"

    log_imp 7 "-" "Generating .env.platform from: ${yaml_path}"

    if [[ ! -f "$yaml_path" ]]; then
        log_imp 10 "-" "FAIL-FAST: platform-env.yaml not found at: ${yaml_path}"
        exit 1
    fi

    log_imp 8 "-" "Validating YAML file exists: ${yaml_path}"

    # Use python3+yaml for robust YAML parsing + validation + output
    local domain_arg="${domain:-${PLATFORM_DOMAIN:-tronyx.ru}}"
    local name_arg="${project_name:-}"

    python3 -c "
import yaml, sys, os, json
from datetime import datetime

yaml_path = '${yaml_path}'
domain = '${domain_arg}'
proj_name = '${name_arg}'

try:
    with open(yaml_path) as f:
        data = yaml.safe_load(f)
except FileNotFoundError:
    print(f'FAIL-FAST: platform-env.yaml not found: {yaml_path}', file=sys.stderr)
    sys.exit(1)
except yaml.YAMLError as e:
    print(f'FAIL-FAST: YAML parse error in {yaml_path}: {e}', file=sys.stderr)
    sys.exit(1)

provides = data.get('provides', {})
profiles = data.get('profiles', [])
proxy = data.get('proxy', {})

if not provides:
    print('FAIL-FAST: no provides: section found in platform-env.yaml', file=sys.stderr)
    sys.exit(1)

# ── Validate provides ⊆ profiles (fail-fast, O6/DD8) ──
profile_set = set(profiles)
for svc_name in provides:
    if svc_name not in profile_set:
        print(f'FAIL-FAST: provides key \"{svc_name}\" is NOT in profiles list', file=sys.stderr)
        print(f'  Profiles: {profiles}', file=sys.stderr)
        sys.exit(1)

# ── Collect unique networks from all provides ──
all_networks = set()
for svc_data in provides.values():
    for net in svc_data.get('networks', []):
        all_networks.add(net)

# ── Generate .env.platform ──
lines = []
lines.append('# GENERATED by ai-platform — DO NOT EDIT')
lines.append(f'# Generated: {datetime.now().isoformat()}')

# PLATFORM_DOMAIN
lines.append(f'PLATFORM_DOMAIN={domain}')

# PLATFORM_PROVIDES — comma-separated keys
provides_keys = sorted(provides.keys())
lines.append(f'PLATFORM_PROVIDES={\",\".join(provides_keys)}')

# Per-service HOST/PORT/DSN/URL
for svc_name in sorted(provides.keys()):
    svc_upper = svc_name.upper()
    svc_data = provides[svc_name]

    host = svc_data.get('host', '')
    port = svc_data.get('port', '')
    dsn_tmpl = svc_data.get('dsn_template', '')
    url_tmpl = svc_data.get('url_template', '')

    if host:
        lines.append(f'PLATFORM_{svc_upper}_HOST={host}')
    if port:
        lines.append(f'PLATFORM_{svc_upper}_PORT={port}')

    # Substitute {NAME} placeholder in DSN/URL if project name provided
    if dsn_tmpl:
        dsn_val = dsn_tmpl.replace('\${NAME}', proj_name) if proj_name else dsn_tmpl
        lines.append(f'PLATFORM_{svc_upper}_DSN={dsn_val}')
    if url_tmpl:
        url_val = url_tmpl.replace('\${NAME}', proj_name) if proj_name else url_tmpl
        url_val = url_val.replace('\${DOMAIN}', domain)
        lines.append(f'PLATFORM_{svc_upper}_URL={url_val}')

# Networks from provides — one PLATFORM_<NET> per unique network
for net in sorted(all_networks):
    net_upper = net.upper().replace('-', '_')
    lines.append(f'PLATFORM_{net_upper}={net}')

# Proxy NO_PROXY
no_proxy = proxy.get('no_proxy_internal', '')
if no_proxy:
    lines.append(f'PLATFORM_NO_PROXY={no_proxy}')

# Output
for line in lines:
    print(line)

# ── Validation: count PLATFORM_* variables ──
plat_count = sum(1 for l in lines if l.startswith('PLATFORM_'))
if plat_count < 8:
    print(f'WARNING: Only {plat_count} PLATFORM_* variables generated (expected ≥8)', file=sys.stderr)
" || {
        local rc=$?
        log_imp 10 "-" "Python generator exited with code ${rc}"
        return $rc
    }

    log_imp 9 "-" ".env.platform generation complete"
}
# endregion FUNC_generate

# ──────────────────────────────────────────────────────────────────────────────
# MAIN
# ──────────────────────────────────────────────────────────────────────────────
# region MAIN
## @purpose  Parse CLI args, invoke generator, optionally write output file
## @io       stdout: .env.platform content (unless --output specified)
log_imp 6 "-" "Starting gen-env-platform.sh"

yaml_path="$DEFAULT_YAML"
project_name=""
domain=""
output_file=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        --yaml)
            shift
            yaml_path="$1"
            ;;
        --name)
            shift
            project_name="$1"
            ;;
        --domain)
            shift
            domain="$1"
            ;;
        --output)
            shift
            output_file="$1"
            ;;
        --help|-h)
            usage
            exit 0
            ;;
        *)
            log_imp 9 "-" "Unknown argument: $1"
            usage >&2
            exit 1
            ;;
    esac
    shift
done

log_imp 7 "-" "YAML: ${yaml_path}, name: ${project_name:-<none>}, domain: ${domain:-<default>}"

if [[ -n "$output_file" ]]; then
    log_imp 8 "-" "Writing output to: ${output_file}"
    generate "$yaml_path" "$project_name" "$domain" > "$output_file"
    log_imp 9 "-" "Written ${output_file}"
    echo "[IMP:9][gen-env-platform][main] Wrote .env.platform (${output_file})" >&2
else
    generate "$yaml_path" "$project_name" "$domain"
fi

log_imp 6 "-" "gen-env-platform.sh complete"
# endregion MAIN
