#!/usr/bin/env bash
# GREP_SUMMARY: gen-env-platform env-generator platform-env yaml-dotenv provides profiles pgbouncer
# STRUCTURE: ▶ init → parse_args → thin facade → delegate to gen_env_platform.py → stdout
# region MODULE_CONTRACT
## @purpose  Generate .env.platform from platform-env.yaml — the canonical runtime environment
##           contract consumed by project docker-compose.yml via env_file.
## @scope    Called from scaffold.sh (project-sync-env) and add-project.sh.
## @io       stdout: .env.platform content (PLATFORM_* variables)
##           stderr: LDD logs via log_imp at IMP:7-10; fail-fast errors
## @invariants
##   - provides: keys MUST be subset of profiles (fail-fast with key name)
##   - Postgres DSN uses pgbouncer:6432 (O5), NEVER postgres:6432
##   - Output starts with "# GENERATED by ai-platform — DO NOT EDIT"
##   - Idempotent: same YAML → identical output (modulo timestamp header)
##   - ≥8 PLATFORM_* variables (gate test validates)
##   - Thin shell facade — all business logic delegated to Python module (Tier 1 Strangler)
## @rationale Single source of truth for project environment — generated from
##            platform-env.yaml provides: section. Eliminates manual .env management
##            in 20+ projects. Python module extracted per DevPlan 082.
## @links    USES: platform-env.yaml (canonical provides/proxy/profiles)
##           USED_BY: scaffold.sh project-sync-env, add-project.sh, project Makefile sync-env
## @changes  2026-07-17 · T7 — Initial implementation
##           2026-07-26 · Plan 082 — Tier 1 Strangler: business logic extracted to
##                      gen_env_platform.py; shell is now thin facade
# endregion MODULE_CONTRACT

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────────
# CONFIG
# ──────────────────────────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLATFORM_ROOT="${PLATFORM_ROOT:-$(cd "${SCRIPT_DIR}/../../.." 2>/dev/null && pwd || dirname "$(dirname "$(dirname "$SCRIPT_DIR")")")}"
DEFAULT_YAML="${PLATFORM_ROOT}/platform-env.yaml"

__LOG_PREFIX="gen-env-platform"
source "${PLATFORM_ROOT}/core/lib/logging.sh"

# ──────────────────────────────────────────────────────────────────────────────
# region FUNC_usage
## @purpose  Print usage guide for gen-env-platform.sh
## @io       stdout: usage text
## @complexity O(1)
usage() {
    cat <<'HELP'
USAGE: gen-env-platform.sh [OPTIONS]

Generate .env.platform from platform-env.yaml — the canonical runtime
environment contract for projects.

OPTIONS:
  --yaml <path>       Path to platform-env.yaml (default: <platform_root>/platform-env.yaml)
  --name <name>       Project name for DSN substitution (replaces ${NAME} placeholder)
  --domain <domain>   Override PLATFORM_DOMAIN (default: $PLATFORM_DOMAIN env or ai-platform.local)
  --output <path>     Write output to file instead of stdout
  --help              Show this help message

EXAMPLES:
  gen-env-platform.sh
  gen-env-platform.sh --name myapp --domain example.com
  gen-env-platform.sh --yaml /path/to/platform-env.yaml --output .env.platform

VALIDATION:
  - Fails fast if any provides: key is not in profiles:
  - Output ≥8 PLATFORM_* variables
  - Postgres DSN always uses pgbouncer:6432
HELP
}
# endregion FUNC_usage

# ──────────────────────────────────────────────────────────────────────────────
# region FUNC_generate
## @purpose  Core generator: read platform-env.yaml, validate, emit .env.platform
## @param $1  Path to platform-env.yaml
## @param $2  Optional project name for ${NAME} DSN substitution
## @param $3  Optional domain override
## @io       stdout: generated .env.platform content
##           stderr: LDD logs IMP:7-10
## @complexity O(1) — delegates to Python module (Tier 1 Strangler)
generate() {
    local yaml_path="$1"
    local project_name="${2:-}"
    local domain="${3:-}"

    log_imp 7 "-" "Generating .env.platform from: ${yaml_path}"

    if [[ ! -f "$yaml_path" ]]; then
        log_imp 10 "-" "FAIL-FAST: platform-env.yaml not found at: ${yaml_path}"
        exit 1
    fi

    log_imp 8 "-" "Validating YAML file exists: ${yaml_path}"

    # Python module (Tier 1 Strangler extraction — DevPlan 082)
    local domain_arg="${domain:-${PLATFORM_DOMAIN:-ai-platform.local}}"
    local py_args=(--yaml "$yaml_path" --domain "$domain_arg")
    [[ -n "${project_name:-}" ]] && py_args+=(--name "$project_name")

    python3 "${PLATFORM_ROOT}/core/internal/scaffold/gen_env_platform.py" "${py_args[@]}" || {
        local rc=$?
        log_imp 10 "-" "Python generator exited with code ${rc}"
        return $rc
    }

    log_imp 9 "-" ".env.platform generation complete"
}
# endregion FUNC_generate

# ──────────────────────────────────────────────────────────────────────────────
# MAIN
# ──────────────────────────────────────────────────────────────────────────────
# region MAIN
## @purpose  Parse CLI args, invoke generator, optionally write output file
## @io       stdout: .env.platform content (unless --output specified)
log_imp 6 "-" "Starting gen-env-platform.sh"

yaml_path="$DEFAULT_YAML"
project_name=""
domain=""
output_file=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        --yaml)
            shift
            yaml_path="$1"
            ;;
        --name)
            shift
            project_name="$1"
            ;;
        --domain)
            shift
            domain="$1"
            ;;
        --output)
            shift
            output_file="$1"
            ;;
        --help|-h)
            usage
            exit 0
            ;;
        *)
            log_imp 9 "-" "Unknown argument: $1"
            usage >&2
            exit 1
            ;;
    esac
    shift
done

log_imp 7 "-" "YAML: ${yaml_path}, name: ${project_name:-<none>}, domain: ${domain:-<default>}"

if [[ -n "$output_file" ]]; then
    log_imp 8 "-" "Writing output to: ${output_file}"
    generate "$yaml_path" "$project_name" "$domain" > "$output_file"
    log_imp 9 "-" "Written ${output_file}"
    echo "[IMP:9][gen-env-platform][main] Wrote .env.platform (${output_file})" >&2
else
    generate "$yaml_path" "$project_name" "$domain"
fi

log_imp 6 "-" "gen-env-platform.sh complete"
# endregion MAIN
