#!/usr/bin/env python3
# GREP_SUMMARY: gen_env_platform, env-platform, generator, provides, profiles, pgbouncer, generate_env_platform, credentials, platform-db.env, password-injection
# STRUCTURE: ▶ generate_env_platform(load→validate→generate) → ⊕ lines list ▶ password-injection (credentials → DSN ***) ▶ CLI main(catch→sys.exit)
# region MODULE_CONTRACT
## @purpose  Generate .env.platform from platform-env.yaml. Library function + CLI wrapper.
##           Extracted from gen-env-platform.sh as Tier 1 Strangler — Python business logic,
##           shell becomes thin facade. T9a: library refactor with exception-based error handling.
## @scope    CLI utility (main()) called from gen-env-platform.sh and scaffold.sh.
##           Library function (generate_env_platform()) imported directly by reconciler.py and tests.
## @invariants
##   - provides keys MUST be subset of profiles (fail-fast via GenEnvPlatformValidationError)
##   - Postgres DSN uses pgbouncer:6432 (O5), NEVER postgres:6432
##   - Output starts with "# GENERATED by ai-platform — DO NOT EDIT"
##   - Idempotent: same YAML → identical output (modulo timestamp header)
##   - ≥8 PLATFORM_* variables (gate test validates)
##   - Library functions NEVER call sys.exit() — raise exceptions for caller to handle
##   - Password-injection (DevPlan 133 W2.3/D4): при credentials-контексте (dict из
##     .platform-db.env) реальный пароль подставляется в DSN (замена '***'); без
##     credentials поведение НЕ меняется (обратная совместимость)
## @rationale Single source of truth for project environment — generated from
##            platform-env.yaml provides: section. Library design enables direct import
##            from reconciler.py and other Python modules (T9b) without subprocess overhead.
## @links    DevPlan 133 W2.3: password-injection + CLI --project-dir/--credentials-file
## @changes  Plan 082 — extracted from gen-env-platform.sh inline python3 heredoc
## @changes  2026-07-30 · T9d — added --output argument, gen-env-platform.sh deleted
## @changes  2026-07-30 · T9a — library refactor: load_yaml/validate_provides raise exceptions;
##           added generate_env_platform() convenience wrapper; __all__ export
## @changes  2026-08-03 · DevPlan 133 W2 — +credentials (password-injection), --project-dir/--credentials-file
# endregion MODULE_CONTRACT

from __future__ import annotations

import argparse
import logging
import os
import re
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import TYPE_CHECKING, ClassVar, TypedDict, cast

import yaml

if TYPE_CHECKING:
    # Только типизация (W11: no-Any) — рантайм-импорт ленивый внутри функций
    # (standalone CLI bootstrap: core.* резолвится ПОСЛЕ sys.path-insert, TRAP[BUG] ниже).
    from core.internal.shared.placement import Placement

logger = logging.getLogger(__name__)

# ── sys.path bootstrap: standalone CLI invocation (python3 script.py) ──
# core.internal.shared.* резолвится без PYTHONPATH (паттерн on_project_deploy.py):
# core/internal/scaffold/ → parents[3] = repo root.
# ⚠️ TRAP[BUG] · 2026-08-16 · P1 · import core.* ДО bootstrap — standalone-запуск падал
# · Symptom: hook postgres → sys.executable gen_env_platform.py → ModuleNotFoundError
# ·   'core' (import на строке ДО sys.path-insert; core/ не пакет — site-packages
# ·   editable-маппинг не покрывает; tests живут на conftest addsitedir).
# · Root: порядок блоков — bootstrap (parents[3] → repo root) был ПОСЛЕ import'а.
# · Fix: bootstrap ДО импорта core.internal.* (проверка BROKEN-ORDER-сканом scaffold).
_PLATFORM_VARS_MIN: int = 8  # минимальное ожидаемое число PLATFORM_* переменных

_PROJECT_ROOT = str(Path(__file__).resolve().parents[3])
if _PROJECT_ROOT not in sys.path:
    sys.path.insert(0, _PROJECT_ROOT)

from core.internal.shared.exceptions import PlatformError  # намеренно ПОСЛЕ bootstrap (TRAP[BUG] выше)

__all__ = [
    "GenEnvPlatformError",
    "GenEnvPlatformValidationError",
    "generate",
    "generate_env_platform",
    "load_credentials",
    "load_yaml",
    "main",
    "resolve_placement_for_project",
    "validate_provides",
]


# ═══════════════════════════════════════════════════════════════════
# region TYPED_CONTRACTS
## @purpose  Typed boundaries for platform-env.yaml (W11: yaml payload — no Any).
##           Provides-entries have optional host/port/dsn_template/url_template/networks.
class _ProvidesEntry(TypedDict, total=False):
    host: str
    port: int | str
    dsn_template: str
    url_template: str
    networks: list[str]


class _ProxyConfig(TypedDict, total=False):
    consumers: list[str]
    no_proxy_internal: str


class _PlatformEnvYamlBase(TypedDict, total=False):
    provides: dict[str, _ProvidesEntry]
    profiles: list[str]
    proxy: _ProxyConfig


class _PlatformEnvYaml(_PlatformEnvYamlBase):
    """Top-level platform-env.yaml (все секции опциональны — total=False база)."""


# endregion TYPED_CONTRACTS


# ═══════════════════════════════════════════════════════════════════
# region EXCEPTIONS
## @purpose  Custom exception hierarchy for gen_env_platform library errors


class GenEnvPlatformError(Exception):
    """## @purpose Base exception for all gen_env_platform errors."""


class GenEnvPlatformValidationError(GenEnvPlatformError):
    """## @purpose Raised when provides: validation fails (missing section or key not in profiles)."""


# endregion EXCEPTIONS


# ═══════════════════════════════════════════════════════════════════
# region FUNC_load_yaml
## @purpose  Load and parse platform-env.yaml from disk.
##           Library-safe: raises FileNotFoundError or yaml.YAMLError instead of sys.exit().
## @param yaml_path  Path to platform-env.yaml on disk
## @return  Parsed YAML content as dict
## @raises FileNotFoundError  If yaml_path does not exist
## @raises yaml.YAMLError     If YAML content is malformed
def load_yaml(yaml_path: str) -> _PlatformEnvYaml:
    """Load and validate platform-env.yaml.

    Args:
        yaml_path: Path to platform-env.yaml on disk.

    Returns:
        Parsed YAML content as dict.

    Raises:
        FileNotFoundError: If yaml_path does not exist.
        yaml.YAMLError: If YAML content is malformed.
    """
    path = Path(yaml_path)
    if not path.is_file():
        msg = f"platform-env.yaml not found: {yaml_path}"
        raise FileNotFoundError(msg)
    with Path(path).open(encoding="utf-8") as f:
        # W11: yaml.safe_load returns Any → cast to platform-env boundary TypedDict
        data = cast(_PlatformEnvYaml, yaml.safe_load(f))
    logger.info("[IMP:8][load_yaml] Loaded YAML from %s", yaml_path)
    return data


# endregion FUNC_load_yaml


# ═══════════════════════════════════════════════════════════════════
# region FUNC_validate_provides
## @purpose  Validate that all provides: keys exist in profiles: list.
##           Library-safe: raises GenEnvPlatformValidationError instead of sys.exit().
## @param data      Parsed platform-env.yaml dict
## @param profiles  List of valid profile names from data
## @return  Validated provides dict (from data["provides"])
## @raises GenEnvPlatformValidationError  If provides section missing or key not in profiles
def validate_provides(data: _PlatformEnvYaml, profiles: list[str]) -> dict[str, _ProvidesEntry]:
    """Validate provides keys are subset of profiles.

    Args:
        data: Parsed platform-env.yaml dict.
        profiles: List of valid profile names.

    Returns:
        Validated provides dict from data["provides"].

    Raises:
        GenEnvPlatformValidationError: If provides section is missing
            or any provides key is not found in profiles.
    """
    provides = data.get("provides", {})
    if not provides:
        msg = "no provides: section found in platform-env.yaml"
        raise GenEnvPlatformValidationError(msg)
    profile_set = set(profiles)
    for svc_name in provides:
        if svc_name not in profile_set:
            msg = f'provides key "{svc_name}" is NOT in profiles list. Profiles: {profiles}'
            raise GenEnvPlatformValidationError(msg)
    logger.info("[IMP:9][validate_provides] Validated %d provide(s) against profiles", len(provides))
    return provides


# endregion FUNC_validate_provides


# ═══════════════════════════════════════════════════════════════════
# region FUNC_apply_credentials_to_dsn
## @purpose  Password-injection (DevPlan 133 W2.3/D4): подстановка реальных credentials
##           (из .platform-db.env) в DSN-шаблон. Заменяет ${NAME}_user/${NAME}_db на
##           фактические роль/БД (если заданы) и '***' на реальный пароль.
##           Без credentials → шаблон возвращается без изменений (обратная совместимость).
## @param dsn_tmpl     DSN template из platform-env.yaml (postgres-сервис: DSN вида
##                     postgresql://NAME_user:***\@pgbouncer:6432/NAME_db)
## @param project_name Project name (${NAME} подстановка — если credentials не покрывают)
## @param credentials  dict из .platform-db.env (PLATFORM_POSTGRES_DB/USER/PASSWORD) | None
## @return  str — DSN с подставленными credentials
## @complexity O(1)
## @invariants
##   - token_urlsafe(24) пароль не требует URL-экранирования (charset [A-Za-z0-9_-])
##   - Порядок: ${NAME}_user/${NAME}_db ДО ${NAME} (частичные совпадения не ломаются)
##   - '***' заменяется ТОЛЬКО при наличии пароля в credentials
def _apply_credentials_to_dsn(dsn_tmpl: str, project_name: str, credentials: dict[str, str] | None) -> str:
    """Substitute real DB credentials into a DSN template (password-injection, DevPlan 133)."""
    result = dsn_tmpl
    if credentials:
        user = credentials.get("PLATFORM_POSTGRES_USER", "") or ""
        db = credentials.get("PLATFORM_POSTGRES_DB", "") or ""
        pw = credentials.get("PLATFORM_POSTGRES_PASSWORD", "") or ""
        if user:
            result = result.replace("${NAME}_user", user)
        if db:
            result = result.replace("${NAME}_db", db)
        if pw:
            result = result.replace("***", pw)
    if project_name:
        result = result.replace("${NAME}", project_name)
    return result


# endregion FUNC_apply_credentials_to_dsn


# ═══════════════════════════════════════════════════════════════════
# region FUNC_load_credentials
## @purpose  Load DB credentials from .platform-db.env (project_dir) или явного файла
##           (--credentials-file). Канонический парсер — shared/secrets_env_parser.
##           Файл отсутствует → {} (без изменений поведения генератора).
## @param project_dir        Project directory (ищет dir/.platform-db.env)
## @param credentials_file   Explicit credentials file (приоритетнее project_dir)
## @return  dict[str, str] — {} если файла нет
## @complexity O(N) — N = строки файла
## @invariants
##   - Никогда не raise (отсутствие credentials-файла — нормальный режим)
##   - Значения маскируются в логах парсером (TRAP[BUG] 2026-08-03, секрет-лики)
def load_credentials(project_dir: str | None = None, credentials_file: str | None = None) -> dict[str, str]:
    """Load DB credentials from .platform-db.env ({} if file absent)."""
    from core.internal.shared.secrets_env_parser import parse

    path = ""
    if credentials_file:
        path = credentials_file
    elif project_dir:
        candidate = Path(project_dir) / ".platform-db.env"
        if candidate.is_file():
            path = str(candidate)
    if not path or not os.path.isfile(path):
        logger.info("[IMP:7][load_credentials] No credentials file at %s — DSN keeps '***'", path or "<none>")
        return {}
    try:
        creds = parse(path)
        logger.info(
            "[IMP:9][load_credentials] Credentials loaded from %s (%d key(s))",
            path,
            len(creds),
        )
    except (OSError, PlatformError, TypeError) as exc:  # noqa: EXC — graceful: битый credentials → без инъекции (best-effort)
        logger.warning("[IMP:7][load_credentials] Credentials parse skipped: %s", exc)
        return {}
    else:
        return creds


# endregion FUNC_load_credentials


# ═══════════════════════════════════════════════════════════════════
# region FUNC__resolve_effective_host
## @purpose  DevPlan 010 T2.1: эффективный host provides-сервиса для consumer-ноды.
##           placement+consumer_node заданы и сервис размещён на ДРУГОЙ ноде → host той ноды;
##           иначе (no placement / co-located / модуль вне placement) → Docker DNS alias из SoT.
## @io       ⇥ svc_name, default_host, placement|None, consumer_node → ⎋ tuple[str, str | None]
##           (effective_host, remote_host) — remote_host None = локальный путь (0 подстановок)
## @complexity O(1) — делегирует shared.placement.service_host
## @invariants
##   - placement=None или пустой consumer_node → legacy no-op (байт-совместимость §1.1)
##   - service_host() = None (co-located/off/неизвестный модуль) → Docker DNS alias
##   - Ошибки ConfigValidationError ПРОПАГИРУЮТСЯ (fail-fast, инвариант 3 плана)
def _resolve_effective_host(
    svc_name: str,
    default_host: str,
    placement: Placement | None,
    consumer_node: str,
) -> tuple[str, str | None]:
    """Resolve effective provides-host for the consumer node (cross-node aware)."""
    if placement is None or not consumer_node:
        return default_host, None
    # Ленивый импорт: scaffold не тянет shared.placement в legacy-путь (single-node стеки).
    from core.internal.shared.placement import service_host

    remote = service_host(placement, svc_name, consumer_node)
    if remote is None:
        return default_host, None
    return remote, remote


# endregion FUNC__resolve_effective_host


# ═══════════════════════════════════════════════════════════════════
# region FUNC__substitute_template_host
## @purpose  Подстановка cross-node host в dsn/url шаблон platform-env.yaml (DevPlan 010 T2.1).
##           Шаблоны встраивают Docker-DNS host литералом ("@pgbouncer:6432", "//redis:6379/");
##           при кросс-нодовом потребителе токен host'а заменяется на host ноды-пира.
## @io       ⇥ template, old_host, new_host → ⎋ template с заменённым host-токеном
## @complexity O(len(template))
## @invariants
##   - Замена ТОЛЬКО host-токена после якоря "//" (URL scheme-separator) или "@" (DSN userinfo);
##     scheme-токен ("redis://...") НЕ трогается — иначе подстановка ломает URL (TRAP[BUG] ниже)
##   - https://${DOMAIN} URL без host-токена остаются неизменными
def _substitute_template_host(template: str, old_host: str, new_host: str) -> str:
    """Replace the standalone Docker-DNS host token in a DSN/URL template with the node host."""
    if not old_host or old_host == new_host:
        return template
    # ⚠️ TRAP[BUG] · 2026-08-24 · P2 · regex с голым lookbehind заменял И scheme, И host
    # · Symptom: redis://redis:6379/0 → 10.8.0.11://10.8.0.11:6379/0 (двойная подстановка)
    # · Root: токен "redis" встречается дважды — как scheme перед ":" и как host после "//";
    #   lookbehind (?<![A-Za-z0-9_.-]) не отсекает scheme (перед ним начало строки)
    # · Fix: замена ТОЛЬКО по якорям "//" (URL) и "@" (DSN userinfo) — scheme недостижим
    # · Prevention: тест test_remote_postgres_host_emitted фиксирует REDIS_URL форму
    pattern = re.compile(r"(//|@)" + re.escape(old_host) + r"(?=[:/])")
    substituted, n_subs = pattern.subn(lambda m: f"{m.group(1)}{new_host}", template)
    if n_subs:
        logger.info(
            "[IMP:8][gen_env_platform][template-host] %r -> %r (%d substitution(s))",
            old_host,
            new_host,
            n_subs,
        )
    return substituted


# endregion FUNC__substitute_template_host


# ═══════════════════════════════════════════════════════════════════
# region FUNC_resolve_placement_for_project
## @purpose  Best-effort резолв (placement, consumer_node) для проекта (DevPlan 010 T2.1):
##           target_node ← ai-platform.yaml; placement.yaml ← NODE_YAML env (канон деплой-
##           контекста): ROOT/CONTEXT/placement.yaml (рядом с директорией ноды). Любое звено отсутствует →
##           (None, "") — legacy-путь. Валидационные ошибки ПРОПАГИРУЮТСЯ (fail-fast).
## @io       ⇥ project_dir: str → ⎋ tuple[Placement | None, str]
## @complexity O(1) — 2 чтения файлов максимум
## @invariants
##   - Единая логика для main(--project-dir), scaffolder и converge (0 дублирования)
##   - Отсутствие NODE_YAML / target_node / файла — НОРМА (single-node канон, IMP:7 лог)
def resolve_placement_for_project(project_dir: str) -> tuple[Placement | None, str]:
    """Resolve (placement, target_node) for a project dir; legacy no-op when unresolvable."""
    from core.internal.shared.project_yaml import get_target_node, load_project_yaml

    proj_path = Path(project_dir)
    try:
        ai_data = load_project_yaml(proj_path)
    except (OSError, PlatformError) as exc:
        logger.info("[IMP:7][resolve_placement][skip] ai-platform.yaml unreadable in %s: %s", proj_path, exc)
        return None, ""
    target_node = get_target_node(ai_data, required=False)
    if not target_node:
        logger.info("[IMP:7][resolve_placement][noop] no target_node — single-node emission")
        return None, ""
    node_yaml = os.environ.get("NODE_YAML", "")
    if not node_yaml:
        logger.info("[IMP:7][resolve_placement][noop] NODE_YAML not set — cannot derive placement path")
        return None, target_node
    # Канон деривации — deploy_orchestrator._placement_for_node: контекст из node.yaml
    # (contexts[0].name), путь ROOT/<context>/placement.yaml (root = parent директории ноды).
    from core.internal.shared.node_yaml import NodeYaml
    from core.internal.shared.placement import load_placement

    context = NodeYaml(node_yaml).get_context()
    if not context:
        logger.info("[IMP:7][resolve_placement][noop] no context in %s — legacy emission", node_yaml)
        return None, target_node
    placement_path = Path(node_yaml).parent.parent / str(context) / "placement.yaml"
    placement = load_placement(placement_path)
    if placement is None:
        return None, target_node
    logger.info(
        "[IMP:8][resolve_placement][loaded] context=%s target_node=%s modules=%d",
        placement.context,
        target_node,
        len(placement.modules),
    )
    return placement, target_node


# endregion FUNC_resolve_placement_for_project


# ═══════════════════════════════════════════════════════════════════
# region FUNC_generate
## @purpose  Generate .env.platform lines from parsed platform-env.yaml data dict.
##           Called by generate_env_platform() after load+validate.
## @param data          Parsed platform-env.yaml dict (must contain profiles/provides/proxy keys)
## @param domain        Platform domain (e.g. "ai-platform.local")
## @param project_name  Optional project name for ${NAME} substitution in DSN/URL templates
## @param credentials   Optional DB credentials dict (from .platform-db.env) — password-injection
## @param placement     Optional Placement (DevPlan 010 T2.1): multi-node топология контекста;
##                      None → legacy-путь (Docker DNS алиасы из provides, байт-идентично)
## @param consumer_node Optional имя ноды-потребителя (поле %target_node в ai-platform.yaml);
##                      учитывается только вместе с placement
## @return  List of .env.platform lines (newline-terminated)
## @raises GenEnvPlatformValidationError  If provides validation fails
def generate(
    data: _PlatformEnvYaml,
    domain: str,
    project_name: str = "",
    credentials: dict[str, str] | None = None,
    placement: Placement | None = None,
    consumer_node: str = "",
) -> list[str]:
    """Generate .env.platform lines from platform-env.yaml data.

    Args:
        data: Parsed platform-env.yaml dict.
        domain: Platform domain.
        project_name: Optional project name for DSN {NAME} substitution.
        credentials: Optional DB credentials (password-injection, DevPlan 133 W2).
        placement: Optional shared.placement.Placement (DevPlan 010 T2.1) — cross-node hosts.
        consumer_node: Optional consumer node name (поле %target_node в ai-platform.yaml).

    Returns:
        List of .env.platform lines (newline-terminated).
    """
    profiles = data.get("profiles", [])
    provides = validate_provides(data, profiles)
    proxy = data.get("proxy", {})

    lines: list[str] = []
    lines.append("# GENERATED by ai-platform — DO NOT EDIT")
    lines.append(f"# Generated: {datetime.now(timezone.utc).isoformat()}")

    # PLATFORM_DOMAIN
    lines.append(f"PLATFORM_DOMAIN={domain}")

    # PLATFORM_PROVIDES
    provides_keys = sorted(provides.keys())
    lines.append(f"PLATFORM_PROVIDES={','.join(provides_keys)}")

    # Per-service HOST/PORT/DSN/URL
    for svc_name in sorted(provides.keys()):
        svc_upper = svc_name.upper()
        svc_data = provides[svc_name]

        host = svc_data.get("host", "")
        port = svc_data.get("port", "")
        dsn_tmpl = svc_data.get("dsn_template", "")
        url_tmpl = svc_data.get("url_template", "")

        # DevPlan 010 T2.1: cross-node адресация — сервис на чужой ноде → HOST = <node>.host;
        # своя нода / no placement → Docker DNS alias как сейчас (байт-идентично легаси).
        effective_host, remote_host = _resolve_effective_host(svc_name, str(host), placement, consumer_node)

        if effective_host:
            lines.append(f"PLATFORM_{svc_upper}_HOST={effective_host}")
        if port:
            lines.append(f"PLATFORM_{svc_upper}_PORT={port}")

        # Substitute {NAME} in DSN template (credentials — password-injection, DevPlan 133 W2)
        if dsn_tmpl:
            dsn_val = _apply_credentials_to_dsn(dsn_tmpl, project_name, credentials)
            if remote_host:
                dsn_val = _substitute_template_host(dsn_val, str(host), remote_host)
            lines.append(f"PLATFORM_{svc_upper}_DSN={dsn_val}")
        if url_tmpl:
            url_val = url_tmpl.replace("${NAME}", project_name) if project_name else url_tmpl
            url_val = url_val.replace("${DOMAIN}", domain)
            if remote_host:
                url_val = _substitute_template_host(url_val, str(host), remote_host)
            lines.append(f"PLATFORM_{svc_upper}_URL={url_val}")

    # Networks from provides — unique networks
    all_networks: set[str] = set()
    for svc_data in provides.values():
        for net in svc_data.get("networks", []):
            all_networks.add(net)
    for net in sorted(all_networks):
        net_upper = net.upper().replace("-", "_")
        lines.append(f"PLATFORM_{net_upper}={net}")

    # Proxy NO_PROXY
    no_proxy = proxy.get("no_proxy_internal", "")
    if no_proxy:
        lines.append(f"PLATFORM_NO_PROXY={no_proxy}")

    # Validation
    plat_count = sum(1 for line in lines if line.startswith("PLATFORM_"))
    if plat_count < _PLATFORM_VARS_MIN:
        print(f"WARNING: Only {plat_count} PLATFORM_* variables generated (expected ≥8)", file=sys.stderr)

    logger.info("[IMP:9][gen_env_platform][generate] Generation complete — %d PLATFORM_* variables", plat_count)
    return lines


# endregion FUNC_generate


# ═══════════════════════════════════════════════════════════════════
# region FUNC_generate_env_platform
## @purpose  Convenience wrapper: load → validate → generate → return lines.
##           Single-call entry point for library consumers (reconciler.py, tests).
##           All errors propagate as exceptions — caller handles them.
## @param yaml_path     Path to platform-env.yaml on disk
## @param domain        Platform domain (e.g. "ai-platform.local")
## @param project_name  Optional project name for ${NAME} substitution
## @param credentials   Optional DB credentials dict — password-injection (DevPlan 133 W2)
## @param placement     Optional Placement — cross-node hosts (DevPlan 010 T2.1)
## @param consumer_node Optional consumer node name (target_node)
## @return  List of .env.platform lines (newline-terminated)
## @raises FileNotFoundError               If yaml_path does not exist
## @raises yaml.YAMLError                   If YAML content is malformed
## @raises GenEnvPlatformValidationError    If provides validation fails
## @complexity O(1) — delegates to load_yaml → generate
def generate_env_platform(
    yaml_path: str,
    domain: str,
    project_name: str = "",
    credentials: dict[str, str] | None = None,
    placement: Placement | None = None,
    consumer_node: str = "",
) -> list[str]:
    """Generate .env.platform lines from platform-env.yaml — convenience wrapper.

    Combines load_yaml + generate into a single call. All errors propagate
    as exceptions for the caller to handle appropriately.

    Args:
        yaml_path: Path to platform-env.yaml on disk.
        domain: Platform domain.
        project_name: Optional project name for DSN {NAME} substitution.
        credentials: Optional DB credentials (password-injection, DevPlan 133 W2).
        placement: Optional Placement (DevPlan 010 T2.1) — cross-node host emission.
        consumer_node: Optional consumer node name (поле %target_node в ai-platform.yaml).

    Returns:
        List of .env.platform lines (newline-terminated).

    Raises:
        FileNotFoundError: If yaml_path does not exist.
        yaml.YAMLError: If YAML content is malformed.
        GenEnvPlatformValidationError: If provides validation fails.
    """
    data = load_yaml(yaml_path)
    lines = generate(
        data,
        domain=domain,
        project_name=project_name,
        credentials=credentials,
        placement=placement,
        consumer_node=consumer_node,
    )
    logger.info("[IMP:9][gen_env_platform][generate_env_platform] Generated %d lines from %s", len(lines), yaml_path)
    return lines


# endregion FUNC_generate_env_platform


# ═══════════════════════════════════════════════════════════════════
# region FUNC_main
class _GenEnvArgs(argparse.Namespace):
    """Typed argparse namespace (W11: Namespace attribute access is Any).

    ClassVar-аннотации БЕЗ значений (только типы) — значения ломают hasattr/parser-дефолты.
    """

    yaml: ClassVar[str]
    name: ClassVar[str]
    domain: ClassVar[str]
    output: ClassVar[str | None]
    project_dir: ClassVar[str | None]
    credentials_file: ClassVar[str | None]
    placement: ClassVar[str]
    target_node: ClassVar[str]


## @purpose  CLI entry point. Parses args, calls generate_env_platform(), writes output.
##           Catches library exceptions and exits with code 1 + error message.
##           DI (DevPlan 167 D4): argv: list[str] | None = None — тесты вызывают main([...])
##           вместо monkeypatch-патча sys.argv (AF-4 main(argv) паттерн; None = sys.argv).
## @io       stdin: --yaml --domain --name args
##           stdout: .env.platform lines (unless --output specified)
##           stderr: LDD logs + error messages
## @exitcode 0  Success
## @exitcode 1  File not found, YAML parse error, or validation error
## 🧐 TRAP[DI-SEAM] · 2026-08-14 · — · CLI arg-flow тестируется реальным main(argv) + --output
## · Rejected: прямой вызов generate без проброса аргументов (тест патчил sys.argv +
## ·   gep.generate лямбдой — 3 monkeypatch.setattr на 2 сценария)
## · Reason: seam = тестируемость реального вызова main() с argv-инъекцией — 0 патчей,
## ·   тот же assert на потоке domain/project_name/credentials в generate
## · Rev: при появлении второго entrypoint-потребителя — вынести parse в отдельную функцию
def main(argv: list[str] | None = None) -> int:
    """CLI entry point for gen_env_platform.py.

    Wraps generate_env_platform() with CLI argument parsing and error
    handling. Exceptions from library functions are caught and printed
    to stderr; process exits with code 1.
    """
    logging.basicConfig(level=logging.INFO, format="[%(levelname)s][gen_env_platform] %(message)s", stream=sys.stderr)

    parser = argparse.ArgumentParser(description="Generate .env.platform from platform-env.yaml")
    parser.add_argument(
        "--yaml", type=str, default="", help="Path to platform-env.yaml (default: repo root via --project-dir)"
    )
    parser.add_argument("--name", type=str, default="", help="Project name for DSN substitution")
    parser.add_argument("--domain", type=str, default="", help="Platform domain")
    parser.add_argument("--output", type=str, default=None, help="Output path (default: stdout / project dir)")
    parser.add_argument(
        "--project-dir",
        type=str,
        default=None,
        help="Project directory: auto-resolve yaml/name/domain/output + credentials",
    )
    parser.add_argument(
        "--credentials-file", type=str, default=None, help="Explicit DB credentials file (.platform-db.env format)"
    )
    parser.add_argument(
        "--placement",
        type=str,
        default="",
        help="Path to placement.yaml (DevPlan 010 T2.1; empty = auto via NODE_YAML or legacy no-op)",
    )
    parser.add_argument(
        "--target-node",
        type=str,
        default="",
        help="Consumer node name for cross-node hosts (default: ai-platform.yaml#target_node)",
    )
    args = parser.parse_args(argv, namespace=_GenEnvArgs())

    # yaml_path инициализируется ДО try — except-ветка (yaml.YAMLError) читает его (reportPossiblyUnboundVariable)
    yaml_path: str = args.yaml
    # ruff: ignore[PLW0717] — тело try >5 операторов (длинный main-блок) — извлечение неразумно
    try:
        # ── --project-dir mode (DevPlan 133 W2.3): auto-resolve yaml/name/domain/output + credentials ──
        credentials: dict[str, str] | None = None
        output_path = args.output
        project_name = args.name
        domain = args.domain
        placement: Placement | None = None
        consumer_node = ""
        if args.project_dir:
            from core.internal.shared.project_yaml import get_domain, get_name, load_project_yaml

            proj_path = Path(args.project_dir)
            ai_data = load_project_yaml(proj_path)
            if not yaml_path:
                yaml_path = str(Path(__file__).resolve().parents[3] / "platform-env.yaml")
            if not project_name:
                project_name = get_name(ai_data) or proj_path.name
            if not domain:
                domain = get_domain(ai_data) or "ai-platform.local"
            if output_path is None:
                output_path = str(proj_path / ".env.platform")
            credentials = load_credentials(project_dir=args.project_dir, credentials_file=args.credentials_file)

        # DevPlan 010 T2.1: cross-node адресация .env.platform — placement + consumer_node.
        # Явные флаги приоритетны; иначе auto-resolve (target_node ← ai-platform.yaml,
        # placement ← NODE_YAML-деривация); не резолвится → legacy no-op (single-node канон).
        if args.placement:
            from core.internal.shared.placement import load_placement

            placement = load_placement(args.placement)
            consumer_node = args.target_node
        elif args.project_dir:
            placement, consumer_node = resolve_placement_for_project(args.project_dir)
            if args.target_node:
                consumer_node = args.target_node

        if not yaml_path:
            parser.error("--yaml is required (or use --project-dir)")
        if not domain:
            domain = "ai-platform.local"

        lines = generate_env_platform(
            yaml_path,
            domain=domain,
            project_name=project_name,
            credentials=credentials,
            placement=placement,
            consumer_node=consumer_node,
        )
        if output_path:
            output_file = Path(output_path)
            output_file.parent.mkdir(parents=True, exist_ok=True)
            output_file.write_text("\n".join(lines) + "\n", encoding="utf-8")
        else:
            for line in lines:
                print(line)
        logger.info("[IMP:9][gen_env_platform][main] CLI generation complete — %d lines written", len(lines))
    except FileNotFoundError as e:
        print(f"FAIL-FAST: {e}", file=sys.stderr)
        return 1
    except yaml.YAMLError as e:
        print(f"FAIL-FAST: YAML parse error in {yaml_path}: {e}", file=sys.stderr)
        return 1
    except GenEnvPlatformError as e:
        print(f"FAIL-FAST: {e}", file=sys.stderr)
        return 1
    return 0


# endregion FUNC_main


if __name__ == "__main__":
    sys.exit(main())
