#!/usr/bin/env python3
# GREP_SUMMARY: gen_env_platform, env-platform, generator, provides, profiles, pgbouncer, generate_env_platform
# STRUCTURE: ▶ generate_env_platform(load→validate→generate) → ⊕ lines list ▶ CLI main(catch→sys.exit)
# region MODULE_CONTRACT
## @purpose  Generate .env.platform from platform-env.yaml. Library function + CLI wrapper.
##           Extracted from gen-env-platform.sh as Tier 1 Strangler — Python business logic,
##           shell becomes thin facade. T9a: library refactor with exception-based error handling.
## @scope    CLI utility (main()) called from gen-env-platform.sh and scaffold.sh.
##           Library function (generate_env_platform()) imported directly by reconciler.py and tests.
## @invariants
##   - provides keys MUST be subset of profiles (fail-fast via GenEnvPlatformValidationError)
##   - Postgres DSN uses pgbouncer:6432 (O5), NEVER postgres:6432
##   - Output starts with "# GENERATED by ai-platform — DO NOT EDIT"
##   - Idempotent: same YAML → identical output (modulo timestamp header)
##   - ≥8 PLATFORM_* variables (gate test validates)
##   - Library functions NEVER call sys.exit() — raise exceptions for caller to handle
## @rationale Single source of truth for project environment — generated from
##            platform-env.yaml provides: section. Library design enables direct import
##            from reconciler.py and other Python modules (T9b) without subprocess overhead.
## @changes  Plan 082 — extracted from gen-env-platform.sh inline python3 heredoc
## @changes  2026-07-30 · T9d — added --output argument, gen-env-platform.sh deleted
## @changes  2026-07-30 · T9a — library refactor: load_yaml/validate_provides raise exceptions;
##           added generate_env_platform() convenience wrapper; __all__ export
# endregion MODULE_CONTRACT

from __future__ import annotations

import argparse
import logging
import sys
from datetime import datetime
from pathlib import Path

import yaml

logger = logging.getLogger(__name__)

__all__ = [
    "generate_env_platform",
    "generate",
    "load_yaml",
    "validate_provides",
    "main",
    "GenEnvPlatformError",
    "GenEnvPlatformValidationError",
]


# ═══════════════════════════════════════════════════════════════════
# region EXCEPTIONS
## @purpose  Custom exception hierarchy for gen_env_platform library errors


class GenEnvPlatformError(Exception):
    """## @purpose Base exception for all gen_env_platform errors."""


class GenEnvPlatformValidationError(GenEnvPlatformError):
    """## @purpose Raised when provides: validation fails (missing section or key not in profiles)."""


# endregion EXCEPTIONS


# ═══════════════════════════════════════════════════════════════════
# region FUNC_load_yaml
## @purpose  Load and parse platform-env.yaml from disk.
##           Library-safe: raises FileNotFoundError or yaml.YAMLError instead of sys.exit().
## @param yaml_path  Path to platform-env.yaml on disk
## @return  Parsed YAML content as dict
## @raises FileNotFoundError  If yaml_path does not exist
## @raises yaml.YAMLError     If YAML content is malformed
def load_yaml(yaml_path: str) -> dict:
    """Load and validate platform-env.yaml.

    Args:
        yaml_path: Path to platform-env.yaml on disk.

    Returns:
        Parsed YAML content as dict.

    Raises:
        FileNotFoundError: If yaml_path does not exist.
        yaml.YAMLError: If YAML content is malformed.
    """
    path = Path(yaml_path)
    if not path.is_file():
        raise FileNotFoundError(f"platform-env.yaml not found: {yaml_path}")
    with open(path) as f:
        data = yaml.safe_load(f)
    logger.info("[IMP:8][load_yaml] Loaded YAML from %s", yaml_path)
    return data


# endregion FUNC_load_yaml


# ═══════════════════════════════════════════════════════════════════
# region FUNC_validate_provides
## @purpose  Validate that all provides: keys exist in profiles: list.
##           Library-safe: raises GenEnvPlatformValidationError instead of sys.exit().
## @param data      Parsed platform-env.yaml dict
## @param profiles  List of valid profile names from data
## @return  Validated provides dict (from data["provides"])
## @raises GenEnvPlatformValidationError  If provides section missing or key not in profiles
def validate_provides(data: dict, profiles: list[str]) -> dict:
    """Validate provides keys are subset of profiles.

    Args:
        data: Parsed platform-env.yaml dict.
        profiles: List of valid profile names.

    Returns:
        Validated provides dict from data["provides"].

    Raises:
        GenEnvPlatformValidationError: If provides section is missing
            or any provides key is not found in profiles.
    """
    provides = data.get("provides", {})
    if not provides:
        raise GenEnvPlatformValidationError("no provides: section found in platform-env.yaml")
    profile_set = set(profiles)
    for svc_name in provides:
        if svc_name not in profile_set:
            raise GenEnvPlatformValidationError(
                f'provides key "{svc_name}" is NOT in profiles list. Profiles: {profiles}'
            )
    logger.info("[IMP:9][validate_provides] Validated %d provide(s) against profiles", len(provides))
    return provides


# endregion FUNC_validate_provides


# ═══════════════════════════════════════════════════════════════════
# region FUNC_generate
## @purpose  Generate .env.platform lines from parsed platform-env.yaml data dict.
##           Called by generate_env_platform() after load+validate.
## @param data          Parsed platform-env.yaml dict (must contain profiles/provides/proxy keys)
## @param domain        Platform domain (e.g. "ai-platform.local")
## @param project_name  Optional project name for ${NAME} substitution in DSN/URL templates
## @return  List of .env.platform lines (newline-terminated)
## @raises GenEnvPlatformValidationError  If provides validation fails
def generate(data: dict, domain: str, project_name: str = "") -> list[str]:
    """Generate .env.platform lines from platform-env.yaml data.

    Args:
        data: Parsed platform-env.yaml dict.
        domain: Platform domain.
        project_name: Optional project name for DSN {NAME} substitution.

    Returns:
        List of .env.platform lines.
    """
    profiles = data.get("profiles", [])
    provides = validate_provides(data, profiles)
    proxy = data.get("proxy", {})

    lines: list[str] = []
    lines.append("# GENERATED by ai-platform — DO NOT EDIT")
    lines.append(f"# Generated: {datetime.now().isoformat()}")

    # PLATFORM_DOMAIN
    lines.append(f"PLATFORM_DOMAIN={domain}")

    # PLATFORM_PROVIDES
    provides_keys = sorted(provides.keys())
    lines.append(f"PLATFORM_PROVIDES={','.join(provides_keys)}")

    # Per-service HOST/PORT/DSN/URL
    for svc_name in sorted(provides.keys()):
        svc_upper = svc_name.upper()
        svc_data = provides[svc_name]

        host = svc_data.get("host", "")
        port = svc_data.get("port", "")
        dsn_tmpl = svc_data.get("dsn_template", "")
        url_tmpl = svc_data.get("url_template", "")

        if host:
            lines.append(f"PLATFORM_{svc_upper}_HOST={host}")
        if port:
            lines.append(f"PLATFORM_{svc_upper}_PORT={port}")

        # Substitute {NAME} in DSN template
        if dsn_tmpl:
            dsn_val = dsn_tmpl.replace("${NAME}", project_name) if project_name else dsn_tmpl
            lines.append(f"PLATFORM_{svc_upper}_DSN={dsn_val}")
        if url_tmpl:
            url_val = url_tmpl.replace("${NAME}", project_name) if project_name else url_tmpl
            url_val = url_val.replace("${DOMAIN}", domain)
            lines.append(f"PLATFORM_{svc_upper}_URL={url_val}")

    # Networks from provides — unique networks
    all_networks: set[str] = set()
    for svc_data in provides.values():
        for net in svc_data.get("networks", []):
            all_networks.add(net)
    for net in sorted(all_networks):
        net_upper = net.upper().replace("-", "_")
        lines.append(f"PLATFORM_{net_upper}={net}")

    # Proxy NO_PROXY
    no_proxy = proxy.get("no_proxy_internal", "")
    if no_proxy:
        lines.append(f"PLATFORM_NO_PROXY={no_proxy}")

    # Validation
    plat_count = sum(1 for line in lines if line.startswith("PLATFORM_"))
    if plat_count < 8:
        print(f"WARNING: Only {plat_count} PLATFORM_* variables generated (expected ≥8)", file=sys.stderr)

    logger.info("[IMP:9][gen_env_platform][generate] Generation complete — %d PLATFORM_* variables", plat_count)
    return lines


# endregion FUNC_generate


# ═══════════════════════════════════════════════════════════════════
# region FUNC_generate_env_platform
## @purpose  Convenience wrapper: load → validate → generate → return lines.
##           Single-call entry point for library consumers (reconciler.py, tests).
##           All errors propagate as exceptions — caller handles them.
## @param yaml_path     Path to platform-env.yaml on disk
## @param domain        Platform domain (e.g. "ai-platform.local")
## @param project_name  Optional project name for ${NAME} substitution
## @return  List of .env.platform lines (newline-terminated)
## @raises FileNotFoundError               If yaml_path does not exist
## @raises yaml.YAMLError                   If YAML content is malformed
## @raises GenEnvPlatformValidationError    If provides validation fails
## @complexity O(1) — delegates to load_yaml → generate
def generate_env_platform(yaml_path: str, domain: str, project_name: str = "") -> list[str]:
    """Generate .env.platform lines from platform-env.yaml — convenience wrapper.

    Combines load_yaml + generate into a single call. All errors propagate
    as exceptions for the caller to handle appropriately.

    Args:
        yaml_path: Path to platform-env.yaml on disk.
        domain: Platform domain (e.g. \"ai-platform.local\").
        project_name: Optional project name for DSN {NAME} substitution.

    Returns:
        List of .env.platform lines (newline-terminated).

    Raises:
        FileNotFoundError: If yaml_path does not exist.
        yaml.YAMLError: If YAML content is malformed.
        GenEnvPlatformValidationError: If provides validation fails.
    """
    data = load_yaml(yaml_path)
    lines = generate(data, domain=domain, project_name=project_name)
    logger.info("[IMP:9][gen_env_platform][generate_env_platform] Generated %d lines from %s", len(lines), yaml_path)
    return lines


# endregion FUNC_generate_env_platform


# ═══════════════════════════════════════════════════════════════════
# region FUNC_main
## @purpose  CLI entry point. Parses args, calls generate_env_platform(), writes output.
##           Catches library exceptions and exits with code 1 + error message.
## @io       stdin: --yaml --domain --name args
##           stdout: .env.platform lines (unless --output specified)
##           stderr: LDD logs + error messages
## @exitcode 0  Success
## @exitcode 1  File not found, YAML parse error, or validation error
def main() -> None:
    """CLI entry point for gen_env_platform.py.

    Wraps generate_env_platform() with CLI argument parsing and error
    handling. Exceptions from library functions are caught and printed
    to stderr; process exits with code 1.
    """
    logging.basicConfig(level=logging.INFO, format="[%(levelname)s][gen_env_platform] %(message)s", stream=sys.stderr)

    parser = argparse.ArgumentParser(description="Generate .env.platform from platform-env.yaml")
    parser.add_argument("--yaml", required=True, type=str, help="Path to platform-env.yaml")
    parser.add_argument("--name", type=str, default="", help="Project name for DSN substitution")
    parser.add_argument("--domain", type=str, default="ai-platform.local", help="Platform domain")
    parser.add_argument("--output", type=str, default=None, help="Output path (default: stdout)")
    args = parser.parse_args()

    try:
        lines = generate_env_platform(args.yaml, domain=args.domain, project_name=args.name)
        if args.output:
            output_path = Path(args.output)
            output_path.parent.mkdir(parents=True, exist_ok=True)
            output_path.write_text("\n".join(lines) + "\n")
        else:
            for line in lines:
                print(line)
        logger.info("[IMP:9][gen_env_platform][main] CLI generation complete — %d lines written", len(lines))
    except FileNotFoundError as e:
        print(f"FAIL-FAST: {e}", file=sys.stderr)
        sys.exit(1)
    except yaml.YAMLError as e:
        print(f"FAIL-FAST: YAML parse error in {args.yaml}: {e}", file=sys.stderr)
        sys.exit(1)
    except GenEnvPlatformError as e:
        print(f"FAIL-FAST: {e}", file=sys.stderr)
        sys.exit(1)


# endregion FUNC_main


if __name__ == "__main__":
    main()
