#!/usr/bin/env python3
# GREP_SUMMARY: vhost-renderer, nginx, vhost, render-all, add, remove, node-yaml, GENERATED, content-hash, ssl, cert, harness, deterministic
# STRUCTURE: ▶ ┌ProjectEntry + ProjectConfig dataclasses┐ → ◇ ❶ read_node_yaml → ◇ ❷ check_duplicate_domains → ◇ ❸ render_vhost (resolve_cert → gen_body → hash → write) → ◇ ❹ nginx_t_harness (docker -t) → ◇ ❺ atomic mv → ⎋ CLI (render-all|add|remove)
# region MODULE_CONTRACT
## @purpose  Strangler-Fig decomposition of add-vhost.sh (926 LOC) — nginx vhost config management.
##           Replaces grep-based YAML parsing, inline python3 subprocess calls, and heredoc template
##           generation with pure Python. Three modes: render-all (batch from node.yaml), add (single
##           project), remove (delete vhost). Deterministic output: same inputs → byte-identical .conf.
## @scope    Core business logic for nginx vhost generation consumed by:
##           - add-vhost.sh (shell facade, dispatch via python3 -m)
##           - adopt-project.sh (configure_vhost step, TASK-036C)
##           - add-project.sh (vhost generation during project creation)
##           - make render-vhosts NODE=<n> (batch generation)
## @invariants
##   I1: Determinism — two render-all calls with same node.yaml → byte-identical .conf files
##   I2: FQDN uniqueness — duplicate domain → DuplicateDomainError (exit code 2 via CLI)
##   I3: All-or-nothing — render into temp dir, atomic mv after nginx -t validation
##   I4: Flat directory — output to overlays/nginx/<fqdn>.conf, no subdirectories (DRIFT-1)
##   I5: GENERATED header — every .conf has # GENERATED by vhost_renderer.py + content-hash
##   I6: SSL cert paths — subdomain of PLATFORM_DOMAIN → wildcard cert; else → personal domain cert
##   I7: Nginx runtime vars — $host, $request_uri, $upstream_xxx, $remote_addr, $scheme
##       are nginx runtime variables, NOT template placeholders — never substituted
##   I8: compute_body_hash uses SHA-256 (same algorithm as core.internal.shared.content_hash)
## @rationale  TASK-036B (Wave 5b) of Strangler-Fig program. Full Option A migration per DevPlan 036B.
##             Python-first per AGENTS.md language policy. Eliminates 3 inline python3 -c blocks,
##             2 python3 subprocess calls, grep-based YAML parsing. Unit-testable vhost generation
##             (0 tests before migration → 20 tests after).
## @changes  2026-07-26 · Wave 5b — Created vhost_renderer.py from add-vhost.sh Strangler-Fig
## @rationale (D1) vhost_yaml_reader.py consolidated into this module (read_node_yaml_projects).
## @rationale (D2) validate.sh --check-fqdn removed — check_duplicate_domains in Python covers it.
## @rationale (D4) f-strings for nginx template (NOT template_engine.py — ${var} conflicts with {{UPPER_SNAKE}})
## @rationale (D5) argparse subcommands (render-all, add, remove) not --mode flag
## ⚠️ TRAP[DECISION] · 2026-07-26 · — · add-vhost.sh мигрирован в vhost_renderer.py через Strangler-Fig
## · Rejected: keeping vhost generation in shell (risk: 926 LOC monolith, grep-based YAML, inline python3)
## · Reason: языковая политика (AGENTS.md), тестируемость, дедупликация с vhost_yaml_reader.py
## · Rev: если Python vhost_renderer генерирует vhost'ы >5% медленнее shell-версии → профилировать
# endregion MODULE_CONTRACT

import argparse
import hashlib
import logging
import os
import re
import shutil
import subprocess
import sys
import tempfile
from dataclasses import dataclass, field
from pathlib import Path

import yaml

from core.internal.shared.exceptions import ConfigNotFoundError, ConfigParseError
from core.internal.shared.node_yaml import NodeYaml, ProjectEntry

logger = logging.getLogger(__name__)

# ─────────────────────────────────────────────────────────────────────
# DATA CLASSES
# ─────────────────────────────────────────────────────────────────────

# region DATA_CLASSES


@dataclass
class ProjectConfig:
    """Parsed ai-platform.yaml project configuration for vhost generation.

    ## @purpose — Extracted expose/domain/target_node from project YAML.
    ## @io — ⇥ YAML fields → ⎋ dataclass with name, domain, target_node, expose
    """

    name: str
    domain: str
    target_node: str
    expose: bool = True


# NOTE (DevPlan 116 B6 T4.3): локальный DTO ProjectEntry УДАЛЁН — канон живёт
# в core.internal.shared.node_yaml.ProjectEntry (единственное определение в core/).
# Конструкции ProjectEntry(name=..., domain=...) валидны — остальные поля имеют defaults.


@dataclass
class VhostFile:
    """Result of rendering a single vhost.

    ## @purpose — Captures the output path, FQDN, project name, and content hash.
    ## @io — ⇥ render_vhost() → ⎋ VhostFile
    """

    path: str
    fqdn: str
    project_name: str
    body_hash: str


@dataclass
class RenderResult:
    """Result of a full render-all pipeline.

    ## @purpose — Aggregate result with count, errors, and nginx -t status.
    ## @io — ⇥ render_all() → ⎋ RenderResult
    """

    rendered_count: int = 0
    errors: list[str] = field(default_factory=list)
    harness_passed: bool = True


class DuplicateDomainError(Exception):
    """Raised when two projects have the same FQDN.

    ## @purpose — FQDN uniqueness enforcement (exit code 2).
    ## @io — ⇥ duplicate domain details → ⎋ error message
    """


# endregion DATA_CLASSES


# ─────────────────────────────────────────────────────────────────────
# READ_PROJECT_YAML
# ─────────────────────────────────────────────────────────────────────

# region FUNC_read_project_yaml


def read_project_yaml(project_dir: str) -> ProjectConfig | None:
    """Read ai-platform.yaml, extract expose/domain/target_node.

    ▶ ┌project_dir┐ → ◇ ai-platform.yaml exists? → ◇ safe_load → ◇ expose:true?
    → ◇ domain set? → ◇ target_node set? → ⎋ ProjectConfig | None

    ## @purpose — Parse project YAML for vhost eligibility.
    ## @io — ⇥ project_dir: str — path to project directory
    ##       → ⎋ ProjectConfig if expose:true + domain + target_node, else None
    ## @complexity — O(P) where P = YAML file size
    ## @invariants
    ##   - Returns None if expose != true (vhost not needed)
    ##   - Returns None if domain is empty or missing
    ##   - target_node is required — returns None if missing
    ##   - safe_load prevents YAML code execution
    """
    yaml_path = Path(project_dir) / "ai-platform.yaml"
    if not yaml_path.exists():
        logger.warning("[IMP:7][read_project_yaml] ai-platform.yaml not found: %s", yaml_path)
        return None

    logger.info("[IMP:7][read_project_yaml] Reading: %s", yaml_path)

    try:
        with open(yaml_path) as f:
            data = yaml.safe_load(f)
    except yaml.YAMLError as e:
        logger.error("[IMP:8][read_project_yaml] YAML parse error: %s", e)
        return None

    if not isinstance(data, dict):
        logger.warning("[IMP:8][read_project_yaml] Invalid YAML structure (not a dict)")
        return None

    # Check needs.expose structure
    needs = data.get("needs", {})
    expose = needs.get("expose", False)
    domain = needs.get("domain", "")
    target_node = data.get("target_node", "")

    # Also check top-level expose (legacy format)
    if not expose:
        expose = data.get("expose", False)
    if not domain:
        domain = data.get("domain", "")

    if not expose:
        logger.info("[IMP:8][read_project_yaml] Project does not have expose: true — skipping")
        return None

    domain_str = str(domain).strip() if domain else ""
    if not domain_str:
        logger.info("[IMP:8][read_project_yaml] expose:true but no domain — skipping")
        return None

    target_node_str = str(target_node).strip() if target_node else ""
    if not target_node_str:
        logger.warning("[IMP:8][read_project_yaml] expose:true + domain set but no target_node — skipping")
        return None

    project_name = yaml_path.parent.name
    logger.info(
        "[IMP:9][read_project_yaml] Parsed: expose=true, domain=%s, target_node=%s", domain_str, target_node_str
    )

    return ProjectConfig(
        name=project_name,
        domain=domain_str,
        target_node=target_node_str,
        expose=True,
    )


# endregion FUNC_read_project_yaml


# ─────────────────────────────────────────────────────────────────────
# READ_NODE_YAML_PROJECTS
# ─────────────────────────────────────────────────────────────────────

# region FUNC_read_node_yaml_projects


def read_node_yaml_projects(node_yaml_path: str) -> list[ProjectEntry]:
    """Read node.yaml via NodeYaml and extract project entries with domain.

    ▶ ┌node_yaml_path → NodeYaml┐ → ◇ get_projects → ◇ filter name + domain
    → ⊕ append → ⎋ list[ProjectEntry]

    ## @purpose — Parse node.yaml via NodeYaml for vhost batch generation (render-all mode).
    ## @io — ⇥ node_yaml_path: str — path to node.yaml
    ##       → ⎋ list[ProjectEntry] — projects with non-empty domain
    ## @complexity — O(P) where P = number of projects
    ## @invariants
    ##   - Only emits projects with non-empty 'domain' field
    ##   - Returns empty list if node.yaml missing or no projects
    ##   - Projects without domain field are silently skipped
    ##   - Uses NodeYaml facade (not direct yaml.safe_load)
    """
    yaml_path = Path(node_yaml_path)
    if not yaml_path.exists():
        logger.warning("[IMP:7][read_node_yaml_projects] node.yaml not found: %s", yaml_path)
        return []

    logger.info("[IMP:7][read_node_yaml_projects] Parsing projects from: %s", yaml_path)

    try:
        node = NodeYaml(node_yaml_path)
    except (ConfigNotFoundError, ConfigParseError, OSError) as e:
        logger.error("[IMP:8][read_node_yaml_projects] Failed to parse node.yaml: %s", e)
        return []

    projects = node.get("projects", default=[])
    if not isinstance(projects, list):
        return []

    result: list[ProjectEntry] = []
    for p in projects:
        if not isinstance(p, dict):
            continue
        name = str(p.get("name", "")).strip()
        domain = str(p.get("domain", "")).strip()
        if name and domain:
            result.append(ProjectEntry(name=name, domain=domain))
            logger.debug("[IMP:6][read_node_yaml_projects] Found: %s → %s", name, domain)

    logger.info("[IMP:9][read_node_yaml_projects] Found %d project(s) with domain", len(result))
    return result


# endregion FUNC_read_node_yaml_projects


# ─────────────────────────────────────────────────────────────────────
# RESOLVE_CERT_DOMAIN
# ─────────────────────────────────────────────────────────────────────

# region FUNC_resolve_cert_domain


def resolve_cert_domain(fqdn: str, platform_domain: str | None = None) -> str:
    """Determine cert domain for SSL certificate path.

    ▶ ┌fqdn + platform_domain┐ → ◇ fqdn ends with .<platform_domain>?
    → ⊕ platform_domain (wildcard) | ⎋ fqdn (personal cert)

    ## @purpose — Resolve cert path: subdomain of PLATFORM_DOMAIN → wildcard
    ##            cert (/etc/letsencrypt/live/<platform_domain>/), else personal
    ##            cert (/etc/letsencrypt/live/<fqdn>/).
    ## @io — ⇥ fqdn: str — full domain name
    ##       ⇥ platform_domain: str | None — platform wildcard domain (optional)
    ##       → ⎋ str — resolved cert domain
    ## @complexity — O(N) where N = fqdn length
    ## @invariants
    ##   - If platform_domain is None or empty → return fqdn (personal cert)
    ##   - If fqdn.endswith(f".{platform_domain}") → return platform_domain (wildcard)
    ##   - Otherwise → return fqdn (personal cert)
    """
    if platform_domain and fqdn.endswith(f".{platform_domain}"):
        logger.info(
            "[IMP:9][resolve_cert_domain] Wildcard cert domain: %s (subdomain of PLATFORM_DOMAIN)", platform_domain
        )
        return platform_domain

    logger.info("[IMP:9][resolve_cert_domain] Personal cert domain: %s (own cert path)", fqdn)
    return fqdn


# endregion FUNC_resolve_cert_domain


# ─────────────────────────────────────────────────────────────────────
# GENERATE_VHOST_BODY
# ─────────────────────────────────────────────────────────────────────

# region FUNC_generate_vhost_body

# 🧐 TRAP[DECISION] · 2026-07-26 · — · template_engine.py НЕ используется для nginx vhost'ов
# · Rejected: использование template_engine.py ({{UPPER_SNAKE}} strict grammar) для nginx config
# · Reason: nginx использует ${var} синтаксис runtime переменных, несовместимый с {{UPPER_SNAKE}}.
#   Попытка escape nginx-переменных → fragile, error-prone. F-строки — естественный механизм.
# · Rev: если nginx перейдёт на другой синтаксис переменных без конфликта с {{}} — пересмотреть


def generate_vhost_body(fqdn: str, project_name: str, cert_domain: str) -> str:
    """Generate nginx vhost config body (without GENERATED header).

    ▶ ┌{fqdn, project_name, cert_domain}┐ → ⊕ multi-line f-string nginx config
    → ◇ HTTP redirect (80) ◇ HTTPS server (443 ssl, http2) → ⎋ str

    ## @purpose — Generate nginx server block body using Python f-strings.
    ##            HTTP redirect on port 80, HTTPS on 443 with ssl_certificate paths,
    ##            Docker DNS resolver (127.0.0.11), security headers include,
    ##            rate limiting, proxy buffering, lazy DNS resolution via variable proxy_pass.
    ## @io — ⇥ fqdn: str — full domain name
    ##       ⇥ project_name: str — upstream service name
    ##       ⇥ cert_domain: str — resolved cert domain (from resolve_cert_domain)
    ##       → ⎋ str — nginx config body (without GENERATED header)
    ## @complexity — O(1) — fixed template
    ## @invariants
    ##   - $host, $request_uri, $upstream_xxx, $remote_addr, $scheme — nginx runtime vars
    ##     (NOT substituted — nginx resolves them at request time)
    ##   - {fqdn}, {project_name}, {cert_domain}, {nginx_safe_name} — compile-time values
    ##   - http2 on; on separate line (not deprecated listen ... http2 syntax)
    ##   - resolver 127.0.0.11 valid=30s for lazy Docker DNS resolution
    ##   - security-headers.conf included from /etc/nginx/includes/
    """
    nginx_safe_name = project_name.replace("-", "_")

    # NOTE: In this f-string, $host, $request_uri, $proxy_add_x_forwarded_for, etc.
    # are nginx runtime variables — they are literal $ in the output (not Python-
    # substituted). Only {fqdn}, {project_name}, {cert_domain}, {nginx_safe_name}
    # are compile-time substitutions via f-string interpolation.

    body = f"""# HTTP → HTTPS redirect
server {{
    listen 80;
    listen [::]:80;
    server_name {fqdn};

    location /.well-known/acme-challenge/ {{
        root /var/www/acme;
    }}

    location / {{
        return 301 https://$host$request_uri;
    }}
}}

# HTTPS vhost
server {{
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name {fqdn};

    http2 on;

    ssl_certificate /etc/letsencrypt/live/{cert_domain}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/{cert_domain}/privkey.pem;

    # Docker DNS resolver with caching (30s TTL) — enables lazy DNS resolution
    # @rationale nginx resolves upstream hostnames at config load time by default.
    #   Using resolver 127.0.0.11 (Docker embedded DNS) + variables in proxy_pass
    #   defers resolution to request time. This allows nginx to start even when
    #   upstream containers are not ready, and to automatically pick up new IPs
    #   after force-recreate (TTL 30s).
    resolver 127.0.0.11 valid=30s ipv6=off;

    # ── Security headers (platform policy) ─────────────────────────────────
    include /etc/nginx/includes/security-headers.conf;

    # ── Rate limiting (dynamic zone: 10 r/s, burst 20) ─────────────────────
    limit_req zone=dynamic burst=20 nodelay;
    limit_req_status 429;

    # ── Buffering (platform policy) ────────────────────────────────────────
    proxy_buffering on;
    proxy_buffer_size 4k;
    proxy_buffers 8 4k;
    proxy_busy_buffers_size 8k;

    # ── Graceful degradation (S4 DevPlan 019) ────────────────────────────
    # Global resolver (127.0.0.11 valid=30s) in nginx.conf http-block + variable
    # proxy_pass provides lazy DNS resolution. If upstream container is not running,
    # nginx starts successfully and returns 502 on request (graceful degradation).
    # No need for upstream containers to exist at nginx startup.
    location / {{
        # Lazy DNS resolution via variable
        set $upstream_{nginx_safe_name} http://{project_name}:80;
        proxy_pass $upstream_{nginx_safe_name};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Timeouts
        proxy_connect_timeout 10s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }}

    location /health {{
        proxy_pass $upstream_{nginx_safe_name}/health;
        access_log off;
    }}
}}
"""
    logger.info("[IMP:9][generate_vhost_body] Generated vhost body for %s (cert=%s)", fqdn, cert_domain)
    return body


# endregion FUNC_generate_vhost_body


# ─────────────────────────────────────────────────────────────────────
# GENERATE_VHOST_HEADER
# ─────────────────────────────────────────────────────────────────────

# region FUNC_generate_vhost_header


def generate_vhost_header(project_name: str, fqdn: str, node: str, body_hash: str) -> str:
    """Generate the GENERATED header block for vhost config.

    ▶ ┌{project_name, fqdn, node, body_hash}┐ → ⊕ formatted header → ⎋ str

    ## @purpose — Produce deterministic GENERATED header with source metadata
    ##            and content-hash for R6 drift detection.
    ## @io — ⇥ project_name: str — project name
    ##       ⇥ fqdn: str — full domain name
    ##       ⇥ node: str — target node name
    ##       ⇥ body_hash: str — SHA-256 hex digest of body
    ##       → ⎋ str — multi-line header comment
    ## @complexity — O(1) — fixed template
    ## @invariants
    ##   - Format must be parseable by cleanup step (contains # GENERATED)
    ##   - body_hash enables drift detection (R6)
    """
    return f"""# ============================================================
# GENERATED by vhost_renderer.py — DO NOT EDIT
# Source: node.yaml#projects[{project_name}]
# Domain: {fqdn}
# Node: {node}
# Content-Hash: {body_hash}
# Generator: vhost_renderer.py render-vhosts (S1)
# ============================================================

"""


# endregion FUNC_generate_vhost_header


# ─────────────────────────────────────────────────────────────────────
# COMPUTE_BODY_HASH
# ─────────────────────────────────────────────────────────────────────

# region FUNC_compute_body_hash

# ⚠️ TRAP[BUG] · 2026-07-20 · P1 · || chain with pipefail evaluates ALL branches (compute_body_hash fallback)
# · Symptom: sha256sum AND shasum both output hash → body_hash=hash\\nhash (129 chars)
# · Root: A && B || C && D || E — || does NOT short-circuit under set -o pipefail
# · Fix: delegation to Python hashlib (SHA-256) — shell pipefail irrelevant
# · Prevention: hashlib.sha256() is single source of truth for string hashing


def compute_body_hash(content: str) -> str:
    """Compute SHA-256 hex digest of vhost body content.

    ▶ ┌content str┐ → ⊕ hashlib.sha256(content.encode()) → ⎋ hexdigest (64-char)

    ## @purpose — Deterministic content hash for drift detection (R6).
    ##            Uses same algorithm (SHA-256) as core.internal.shared.content_hash.
    ## @io — ⇥ content: str — vhost body content (without GENERATED header)
    ##       → ⎋ str — 64-char hex SHA-256 digest
    ## @complexity — O(N) where N = content size
    ## @invariants
    ##   - Same input → same output (deterministic)
    ##   - Uses SHA-256 via hashlib (cross-platform, deterministic)
    ##   - Content is the body text before header is prepended
    """
    digest = hashlib.sha256(content.encode("utf-8")).hexdigest()
    logger.debug("[IMP:6][compute_body_hash] Hash: %s...", digest[:12])
    return digest


# endregion FUNC_compute_body_hash


# ─────────────────────────────────────────────────────────────────────
# CHECK_DUPLICATE_DOMAINS
# ─────────────────────────────────────────────────────────────────────

# region FUNC_check_duplicate_domains


def check_duplicate_domains(entries: list[ProjectEntry]) -> None:
    """Check FQDN uniqueness across projects.

    ▶ ┌list[ProjectEntry]┐ → ○ set-based dict: domain → name → ◇ dup found?
    → ⊕ DuplicateDomainError | ⎋ None (PASS)

    ## @purpose — Enforce FQDN uniqueness: each domain must be claimed by exactly
    ##            one project. Replaces validate.sh --check-fqdn and inline python3 -c.
    ## @io — ⇥ entries: list[ProjectEntry] — projects with domains
    ##       → ⊕ DuplicateDomainError on duplicate | ⎋ None on pass
    ## @complexity — O(N) where N = entry count (dict-based dedup)
    ## @invariants
    ##   - Duplicate domain → DuplicateDomainError with details
    ##   - No duplicates → returns None (PASS)
    ##   - Empty list → returns None (trivially PASS)
    """
    seen: dict[str, str] = {}
    for entry in entries:
        domain = entry.domain.lower()
        if domain in seen:
            msg = f"Duplicate domain {domain} in projects: {seen[domain]} and {entry.name}"
            logger.error("[IMP:10][check_duplicate_domains] %s", msg)
            raise DuplicateDomainError(msg)
        seen[domain] = entry.name

    logger.info("[IMP:9][check_duplicate_domains] FQDN uniqueness check PASS (%d domains)", len(entries))


# endregion FUNC_check_duplicate_domains


# ─────────────────────────────────────────────────────────────────────
# RENDER_VHOST (single project)
# ─────────────────────────────────────────────────────────────────────

# region FUNC_render_vhost

# ⚠️ TRAP[BUG] · 2026-07-17 · DRIFT-1 · Flat directory (depth 1) required for vhost output
# · Symptom: vhost silently not loaded (fall-through to catch-all, class D12)
# · Root: producer wrote to conf.d/ subdir, non-recursive include overlay/*.conf
#   reads parent level — path mismatch → vhost never picked up
# · Fix: flat layout overlays/nginx/, no subdirectories
# · Prevention: static test verifies output path depth == 1 under overlays/nginx/


def render_vhost(
    entry: ProjectEntry,
    node: str,
    node_configs_dir: str,
    platform_domain: str | None = None,
    output_dir: str | None = None,
) -> VhostFile:
    """Render a single vhost file for a project entry.

    ▶ ┌entry + node + configs_dir┐ → ◇ resolve_cert_domain → ◇ generate_vhost_body
    → ◇ compute_body_hash → ◇ generate_vhost_header → ⊕ write <fqdn>.conf → ⎋ VhostFile

    ## @purpose — Full vhost generation pipeline for one project.
    ## @io — ⇥ entry: ProjectEntry — project name and domain
    ##       ⇥ node: str — target node name
    ##       ⇥ node_configs_dir: str — path to node-configs directory
    ##       ⇥ platform_domain: str | None — platform wildcard domain (optional)
    ##       ⇥ output_dir: str | None — override output directory (default: <node-configs>/<node>/overlays/nginx)
    ##       → ⎋ VhostFile — rendered vhost metadata
    ## @complexity — O(S) where S = template size
    ## @invariants
    ##   - Output is always <fqdn>.conf (flat directory, no subdirs — DRIFT-1)
    ##   - Body hash is computed BEFORE header prepends
    ##   - Header includes project source, domain, node, content-hash
    """
    fqdn = entry.domain.lower()
    cert_domain = resolve_cert_domain(fqdn, platform_domain)

    # Generate body first to compute hash (before header prepends)
    body = generate_vhost_body(fqdn, entry.name, cert_domain)
    body_hash = compute_body_hash(body)

    # Generate complete file: header + body
    header = generate_vhost_header(entry.name, fqdn, node, body_hash)
    full_content = header + body

    # Determine output path
    vhost_dir = Path(output_dir) if output_dir else Path(node_configs_dir) / node / "overlays" / "nginx"

    vhost_dir.mkdir(parents=True, exist_ok=True)
    vhost_path = vhost_dir / f"{fqdn}.conf"

    # Write to file
    vhost_path.write_text(full_content, encoding="utf-8")

    logger.info(
        "[IMP:9][render_vhost] Rendered: %s → %s (cert=%s, hash=%s...)",
        entry.name,
        vhost_path,
        cert_domain,
        body_hash[:12],
    )

    return VhostFile(
        path=str(vhost_path),
        fqdn=fqdn,
        project_name=entry.name,
        body_hash=body_hash,
    )


# endregion FUNC_render_vhost


# ──────────────────────────────────────────────────────────────────────
# REMOVE_VHOST
# ──────────────────────────────────────────────────────────────────────

# region FUNC_remove_vhost


def remove_vhost(project_name: str, overlays_dir: str, platform_root: str | None = None) -> bool:
    """Remove an existing nginx vhost config.

    ▶ ┌project_name + overlays_dir┐ → ◇ find .conf with matching name/fqdn
    → ◇ file exists? → ⊕ delete + write audit-log | ⎋ True (idempotent)

    ## @purpose — Idempotent removal of vhost overlay file. Deletes the .conf
    ##            file and optionally writes an audit log entry. Safe to call
    ##            multiple times (no-op if file already removed).
    ## @io — ⇥ project_name: str — name of the project to remove vhost for
    ##       ⇥ overlays_dir: str — path to overlays/nginx directory
    ##       ⇥ platform_root: str | None — platform root for audit log (optional)
    ##       → ⎋ bool — True on success (or idempotent skip)
    ## @complexity — O(F) where F = number of .conf files in overlays_dir
    ## @invariants
    ##   - Idempotent: no-op if .conf file does not exist
    ##   - Audit log written only on actual deletion (not on skip)
    ##   - No service restart, no cert cleanup
    """
    overlay_path = Path(overlays_dir)
    if not overlay_path.exists():
        logger.info("[IMP:8][remove_vhost] Overlay dir not found: %s — idempotent skip", overlays_dir)
        return True

    # Find vhost file for this project (match by project name or domain pattern)
    # Strategy: scan .conf files, parse GENERATED header for project name
    removed = False
    for conf_file in overlay_path.glob("*.conf"):
        if not conf_file.is_file():
            continue
        # Check if this conf belongs to our project
        content = conf_file.read_text(encoding="utf-8")
        if f"node.yaml#projects[{project_name}]" in content or f"Source: node.yaml#projects[{project_name}]" in content:
            conf_file.unlink()
            logger.info("[IMP:9][remove_vhost] Deleted vhost: %s", conf_file)
            removed = True

    if not removed:
        logger.info("[IMP:8][remove_vhost] No vhost found for project '%s' — idempotent skip", project_name)

    # Write audit log on actual removal
    if removed and platform_root:
        audit_dir = Path(platform_root) / "var" / "log"
        audit_dir.mkdir(parents=True, exist_ok=True)
        audit_log = audit_dir / "audit.log"
        from datetime import datetime, timezone

        timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
        audit_line = f"[{timestamp}] [audit] [vhost:remove] project={project_name}\n"
        with open(audit_log, "a") as f:
            f.write(audit_line)
        logger.info("[IMP:8][remove_vhost] Audit log written: removed vhost for %s", project_name)

    return True


# endregion FUNC_remove_vhost


# ──────────────────────────────────────────────────────────────────────
# NGINX -T HARNESS
# ──────────────────────────────────────────────────────────────────────

# region FUNC_nginx_t_harness

# 🧐 TRAP[DECISION] · 2026-07-20 · — · nginx_t_harness: isolate overlay vhosts from harness_dir
# · Rejected: storing vhosts and harness support files (security-headers.conf) in same dir
# · Reason: mount -v ${harness_dir}:/etc/nginx/conf.d/overlay:ro exposes ALL .conf files
#   in harness_dir as vhost configs. security-headers.conf is NOT a valid vhost → nginx -t fails
#   with 'unknown directive' on parsed content. Fix: put vhosts in vhosts/ subdir,
#   security-headers in includes/ subdir, dev-certs in dev-certs/ subdir.
# · Rev: if harness nginx.conf is changed to use a non-glob include pattern for vhosts


def nginx_t_harness(temp_dir: str, nginx_version: str = "1.28-alpine") -> bool:
    """Run nginx -t on rendered configs using docker nginx:alpine image.

    ▶ ┌temp_dir┐ → ◇ docker available? → ⊕ create harness_dir (nginx-main/,
    includes/, vhosts/, dev-certs/) → ⊕ generate stub nginx.conf + security-headers
    → ⊕ SSL path swap (re.sub) → ⊕ docker run nginx -t → ◇ result?
    → ⊕ cleanup → ⎋ bool (True = pass, False = fail)

    ## @purpose — Validate rendered nginx configs via docker-based nginx -t.
    ##            Replaces 130 lines of shell (mounts, sed, openssl) with Python.
    ##            SSL cert paths are swapped to dev-certs for local validation.
    ##            Falls back to WARN if docker is unavailable.
    ## @io — ⇥ temp_dir: str — directory with rendered vhost .conf files
    ##       ⇥ nginx_version: str — nginx image tag (default: 1.28-alpine)
    ##       → ⎋ bool — True if validation passes or docker unavailable
    ## @complexity — O(V * S) where V = vhost count, S = file size
    ## @invariants
    ##   - Does NOT modify source files — only docker container context
    ##   - Vhosts in vhosts/ subdir, includes in includes/ subdir (isolation)
    ##   - SSL paths /etc/letsencrypt/live/<domain>/ → /etc/nginx/dev-certs/
    ##   - openssl for self-signed certs; fallback to empty files if unavailable
    ##   - Returns True if docker not found (WARN, non-blocking)
    ##   - Returns True if no vhost files to validate
    ##   - Cleanup: removes harness_dir after completion
    """
    harness_dir = Path(tempfile.mkdtemp(prefix="nginx_harness_"))
    logger.info("[IMP:7][nginx_t_harness] Starting nginx -t validation (nginx:%s)", nginx_version)

    try:
        # ── Step 1: Create harness subdirectory structure ─────────────────
        # nginx-main/ — contains minimal nginx.conf for validation
        # vhosts/ — contains dev-certs-swapped vhost files
        # includes/ — contains stub security-headers.conf
        # dev-certs/ — contains self-signed dev certificates
        harness_nginx_dir = harness_dir / "nginx-main"
        vhosts_dir = harness_dir / "vhosts"
        includes_dir = harness_dir / "includes"
        dev_certs_dir = harness_dir / "dev-certs"

        harness_nginx_dir.mkdir(parents=True, exist_ok=True)
        vhosts_dir.mkdir(parents=True, exist_ok=True)
        includes_dir.mkdir(parents=True, exist_ok=True)
        dev_certs_dir.mkdir(parents=True, exist_ok=True)

        # ── Step 2: Generate minimal nginx.conf ───────────────────────────
        nginx_conf = harness_nginx_dir / "nginx.conf"
        nginx_conf.write_text(
            """events {
    worker_connections 64;
}
http {
    # Base includes for vhosts to resolve
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    # Rate limiting zones (referenced by GENERATED vhosts)
    limit_req_zone $binary_remote_addr zone=dynamic:10m rate=10r/s;

    # Docker DNS resolver
    resolver 127.0.0.11 valid=30s ipv6=off;

    # Stub security headers include
    server {
        listen 80 default_server;
        return 444;
    }

    # Overlay vhosts
    include /etc/nginx/conf.d/overlay/*.conf;
}
""",
            encoding="utf-8",
        )

        # ── Step 3: Generate stub security-headers.conf ───────────────────
        security_headers = includes_dir / "security-headers.conf"
        security_headers.write_text(
            """# Stub security-headers.conf for nginx -t validation
add_header X-Content-Type-Options "nosniff" always;
add_header X-Frame-Options "DENY" always;
""",
            encoding="utf-8",
        )

        # ── Step 4: Generate dev certs ────────────────────────────────────
        fullchain = dev_certs_dir / "fullchain.pem"
        privkey = dev_certs_dir / "privkey.pem"

        try:
            result = subprocess.run(
                [
                    "openssl",
                    "req",
                    "-x509",
                    "-nodes",
                    "-days",
                    "1",
                    "-newkey",
                    "rsa:2048",
                    "-keyout",
                    str(privkey),
                    "-out",
                    str(fullchain),
                    "-subj",
                    "/CN=localhost",
                ],
                capture_output=True,
                timeout=30,
            )
            if result.returncode != 0:
                logger.warning("[IMP:8][nginx_t_harness] openssl failed — creating empty cert files")
                fullchain.write_text("", encoding="utf-8")
                privkey.write_text("", encoding="utf-8")
        except (FileNotFoundError, subprocess.TimeoutExpired):
            logger.warning("[IMP:8][nginx_t_harness] openssl not available — creating empty cert files")
            fullchain.write_text("", encoding="utf-8")
            privkey.write_text("", encoding="utf-8")

        # ── Step 5: Create dev versions of vhosts with SSL paths swapped ──
        temp_path = Path(temp_dir)
        vhost_files = list(temp_path.glob("*.conf"))

        if not vhost_files:
            logger.info("[IMP:7][nginx_t_harness] No vhost files to validate — SKIP")
            return True

        vhost_count = 0
        for vhost_file in vhost_files:
            if not vhost_file.is_file():
                continue
            dev_vhost = vhosts_dir / vhost_file.name
            content = vhost_file.read_text(encoding="utf-8")
            # Replace production SSL paths with dev-certs for validation
            swapped = re.sub(
                r"/etc/letsencrypt/live/[^/]*/fullchain\.pem",
                "/etc/nginx/dev-certs/fullchain.pem",
                content,
            )
            swapped = re.sub(
                r"/etc/letsencrypt/live/[^/]*/privkey\.pem",
                "/etc/nginx/dev-certs/privkey.pem",
                swapped,
            )
            swapped = swapped.replace("/var/www/acme", "/tmp/acme-stub")  # nosec B108 — dev-only acme stub, not production
            dev_vhost.write_text(swapped, encoding="utf-8")
            vhost_count += 1

        logger.info("[IMP:7][nginx_t_harness] Validating %d vhost(s) via nginx -t (docker)", vhost_count)

        # Create stub acme directory
        acme_stub = harness_dir / "acme-stub"
        acme_stub.mkdir(parents=True, exist_ok=True)

        # ── Step 6: Check docker availability and run nginx -t ────────────
        if shutil.which("docker") is None:
            logger.warning("[IMP:8][nginx_t_harness] docker not available — skipping nginx -t validation (WARN)")
            return True

        docker_result = subprocess.run(
            [
                "docker",
                "run",
                "--rm",
                "-v",
                f"{harness_nginx_dir}/nginx.conf:/etc/nginx/nginx.conf:ro",
                "-v",
                f"{dev_certs_dir}:/etc/nginx/dev-certs:ro",
                "-v",
                f"{includes_dir}/security-headers.conf:/etc/nginx/includes/security-headers.conf:ro",
                "-v",
                f"{vhosts_dir}:/etc/nginx/conf.d/overlay:ro",
                f"nginx:{nginx_version}",
                "nginx",
                "-t",
            ],
            capture_output=True,
            timeout=120,
        )

        if docker_result.returncode == 0:
            logger.info("[IMP:9][nginx_t_harness] nginx -t PASS: %d vhost(s) valid", vhost_count)
            return True
        logger.error("[IMP:10][nginx_t_harness] nginx -t FAIL — rendered configs contain syntax errors")
        stderr_text = docker_result.stderr.decode("utf-8", errors="replace")
        for line in stderr_text.splitlines():
            logger.error("[IMP:8][nginx_t_harness] nginx -t: %s", line)
        return False

    finally:
        # Cleanup harness directory
        shutil.rmtree(harness_dir, ignore_errors=True)
        logger.debug("[IMP:6][nginx_t_harness] Cleaned up harness dir: %s", harness_dir)


# endregion FUNC_nginx_t_harness


# ─────────────────────────────────────────────────────────────────────
# RENDER_ALL (batch pipeline)
# ─────────────────────────────────────────────────────────────────────

# region FUNC_render_all


def render_all(
    node_yaml_path: str,
    node_configs_dir: str,
    node: str,
    platform_domain: str | None = None,
) -> RenderResult:
    """Render all vhosts from node.yaml#projects with domain.

    ▶ ┌node_yaml_path + configs_dir + node┐
    → ❶ read_node_yaml_projects → list[ProjectEntry]
    → ❷ check_duplicate_domains → PASS | raise
    → ❸ temp_dir = mkdtemp
    → ❹ for entry: render_vhost → temp_dir/<fqdn>.conf
    → ❺ nginx_t_harness(temp_dir) → ◇ fail? → cleanup + raise
    → ❻ atomic mv: remove existing GENERATED vhosts → mv new → ⎋ RenderResult

    ## @purpose — Full batch pipeline: parse node.yaml, check FQDNs, render
    ##            all vhosts to temp dir, validate via nginx -t, atomic swap.
    ##            6-step pipeline reproducing original render_all() shell logic.
    ## @io — ⇥ node_yaml_path: str — path to node.yaml
    ##       ⇥ node_configs_dir: str — path to node-configs directory
    ##       ⇥ node: str — node name (for output path resolution)
    ##       ⇥ platform_domain: str | None — platform wildcard domain (optional)
    ##       → ⎋ RenderResult — summary of rendered vhosts
    ## @complexity — O(P * S + V) where P = projects, S = template size, V = validation
    ## @throws — DuplicateDomainError on FQDN collision
    ## @throws — RuntimeError if nginx -t validation fails
    ## @invariants
    ##   - Step ❻: removes ONLY files with # GENERATED marker (not hand-written .conf)
    ##   - All-or-nothing: if nginx -t fails, temp dir is cleaned up, no files moved
    ##   - Deterministic: same inputs → byte-identical output
    """
    overlay_dir = Path(node_configs_dir) / node / "overlays" / "nginx"

    logger.info("[IMP:7][render_all] Starting render-all for node=%s", node)
    logger.info("[IMP:7][render_all] node.yaml: %s", node_yaml_path)
    logger.info("[IMP:7][render_all] overlay dir: %s", overlay_dir)

    # ── Step 1: Parse node.yaml projects ──────────────────────────
    entries = read_node_yaml_projects(node_yaml_path)

    if not entries:
        logger.info("[IMP:8][render_all] No projects with domain found — rendering 0 files")
        result = RenderResult(rendered_count=0)
        print("")
        print("──────────────────────────────────────────────────────")
        print("  ⚠️  render-vhosts: 0 files rendered (no domain projects)")
        print("──────────────────────────────────────────────────────")
        return result

    logger.info("[IMP:7][render_all] Found %d project(s) with domain", len(entries))

    # ── Step 2: FQDN uniqueness check ─────────────────────────────
    check_duplicate_domains(entries)

    # ── Step 3: Create temp directory for rendering ───────────────
    temp_dir = Path(tempfile.mkdtemp(prefix="vhost_render_"))
    logger.info("[IMP:7][render_all] Render temp dir: %s", temp_dir)

    try:
        # ── Step 4: Render all vhosts to temp dir ─────────────────
        rendered_vhosts: list[VhostFile] = []
        for entry in entries:
            logger.info("[IMP:7][render_all] Rendering vhost for %s → %s", entry.name, entry.domain)
            vhost = render_vhost(
                entry=entry,
                node=node,
                node_configs_dir=node_configs_dir,
                platform_domain=platform_domain,
                output_dir=str(temp_dir),
            )
            rendered_vhosts.append(vhost)
            logger.info("[IMP:9][render_all] Rendered: %s.conf (hash=%s...)", entry.domain, vhost.body_hash[:12])

        logger.info("[IMP:7][render_all] Rendered %d vhost(s) to temp dir", len(rendered_vhosts))

        # ── Step 5: nginx -t validation ───────────────────────────
        if not nginx_t_harness(str(temp_dir)):
            logger.error("[IMP:10][render_all] nginx -t validation FAILED — removing temp dir, aborting")
            raise RuntimeError("nginx -t validation failed — no files written (all-or-nothing)")

        # ── Step 6: Atomic mv to overlay dir ──────────────────────
        overlay_dir.mkdir(parents=True, exist_ok=True)

        # Remove existing GENERATED vhosts (files with GENERATED marker)
        existing_count = 0
        for gen_file in overlay_dir.glob("*.conf"):
            if not gen_file.is_file():
                continue
            content = gen_file.read_text(encoding="utf-8")
            if "# GENERATED" in content:
                gen_file.unlink()
                existing_count += 1

        if existing_count > 0:
            logger.info("[IMP:7][render_all] Removed %d existing GENERATED vhost(s)", existing_count)

        # Move rendered files from temp_dir to overlay_dir
        moved_count = 0
        for vhost_file in temp_dir.glob("*.conf"):
            if not vhost_file.is_file():
                continue
            dest = overlay_dir / vhost_file.name
            shutil.move(str(vhost_file), str(dest))
            moved_count += 1

        logger.info("[IMP:9][render_all] Atomic mv complete: %d vhost(s) → %s", moved_count, overlay_dir)

        print("")
        print("──────────────────────────────────────────────────────")
        print(f"  ✅ render-vhosts: {moved_count} vhost(s) generated")
        print(f"     Node: {node}")
        print(f"     Output: {overlay_dir}")
        print("──────────────────────────────────────────────────────")
        print("")

        result = RenderResult(
            rendered_count=moved_count,
            harness_passed=True,
        )

    except (DuplicateDomainError, RuntimeError) as e:
        # Cleanup temp dir on failure
        shutil.rmtree(temp_dir, ignore_errors=True)
        logger.info("[IMP:7][render_all] Cleaned up temp dir due to error")
        result = RenderResult(
            rendered_count=0,
            errors=[str(e)],
            harness_passed=False,
        )
        raise

    # Cleanup temp dir on success
    shutil.rmtree(temp_dir, ignore_errors=True)
    logger.info("[IMP:9][render_all] DONE: render-all for node=%s (%d vhosts)", node, result.rendered_count)
    return result


# endregion FUNC_render_all


# ─────────────────────────────────────────────────────────────────────
# CLI (argparse subcommands)
# ─────────────────────────────────────────────────────────────────────

# region CLI


def build_parser() -> argparse.ArgumentParser:
    """Build CLI argument parser with 3 subcommands.

    ▶ ┌None┐ → ⊕ argparse.ArgumentParser → ⎋ parser
    ## @purpose — CLI entry for vhost_renderer with render-all, add, remove.
    ## @io — ⇥ None → ⎋ argparse.ArgumentParser
    ## @complexity — O(1)
    """
    parser = argparse.ArgumentParser(
        description="nginx vhost config manager — render, add, remove",
    )
    parser.add_argument(
        "--platform-domain",
        default=None,
        help="Platform wildcard domain (PLATFORM_DOMAIN) — subdomains use wildcard cert",
    )
    parser.add_argument("--platform-root", default=None, help="Platform root directory (for audit log path)")

    subparsers = parser.add_subparsers(dest="command")
    subparsers.required = True

    # ── render-all subcommand ─────────────────────────────────────
    render_parser = subparsers.add_parser("render-all", help="Batch-render all vhosts from node.yaml")
    render_parser.add_argument("--node", required=True, help="Node name")
    render_parser.add_argument("--node-configs-dir", required=True, help="Path to node-configs/ directory")

    # ── add subcommand ────────────────────────────────────────────
    add_parser = subparsers.add_parser("add", help="Generate vhost for a single project")
    add_parser.add_argument(
        "--project-dir", required=True, help="Path to project directory (contains ai-platform.yaml)"
    )
    add_parser.add_argument("--node-configs-dir", required=True, help="Path to node-configs/ directory")

    # ── remove subcommand ─────────────────────────────────────────
    remove_parser = subparsers.add_parser("remove", help="Remove vhost for a project")
    remove_parser.add_argument(
        "--project-dir", required=True, help="Path to project directory (contains ai-platform.yaml)"
    )
    remove_parser.add_argument("--node-configs-dir", required=True, help="Path to node-configs/ directory")

    return parser


def main(argv: list[str] | None = None) -> int:
    """CLI entry point for vhost_renderer.

    ▶ ┌sys.argv┐ → ◇ parse args → ◇ dispatch (render-all|add|remove) → ⊕ exit code

    ## @purpose — CLI entry with 3 subcommands. Returns exit code for shell facade.
    ## @io — ⇥ argv: list[str] | None → ⎋ int — exit code (0 = success)
    ## @complexity — O(R) where R = render pipeline complexity
    """
    logging.basicConfig(
        level=logging.INFO,
        format="%(message)s",
        stream=sys.stderr,
    )

    parser = build_parser()
    args = parser.parse_args(argv)

    # Resolve platform_domain: CLI arg > env var > None
    platform_domain = args.platform_domain or os.environ.get("PLATFORM_DOMAIN")
    platform_root = args.platform_root or os.environ.get("PLATFORM_ROOT")

    try:
        if args.command == "render-all":
            node_yaml_path = os.path.join(args.node_configs_dir, args.node, "node.yaml")
            render_all(
                node_yaml_path=node_yaml_path,
                node_configs_dir=args.node_configs_dir,
                node=args.node,
                platform_domain=platform_domain,
            )
            return 0

        if args.command == "add":
            # Read project YAML
            config = read_project_yaml(args.project_dir)
            if config is None:
                logger.info("[IMP:8][main] No vhost config found — skipping vhost generation")
                return 0

            # Render vhost
            render_vhost(
                entry=ProjectEntry(name=config.name, domain=config.domain),
                node=config.target_node,
                node_configs_dir=args.node_configs_dir,
                platform_domain=platform_domain,
            )

            print("")
            print("──────────────────────────────────────────────────────")
            print("  ✅ nginx vhost создан")
            print("──────────────────────────────────────────────────────")
            print("")
            logger.info("[IMP:9][main] DONE: vhost for %s generated successfully", config.domain)
            return 0

        if args.command == "remove":
            # Read project YAML
            config = read_project_yaml(args.project_dir)
            if config is None:
                logger.info("[IMP:8][main] No project config found — skipping vhost removal")
                return 0

            # Remove vhost
            overlays_dir = os.path.join(args.node_configs_dir, config.target_node, "overlays", "nginx")
            remove_vhost(
                project_name=config.name,
                overlays_dir=overlays_dir,
                platform_root=platform_root,
            )

            print("")
            print("──────────────────────────────────────────────────────")
            print("  ✅ nginx vhost удалён")
            print("──────────────────────────────────────────────────────")
            print("")
            logger.info("[IMP:9][main] DONE: vhost for %s removed successfully", config.domain)
            return 0

        parser.print_help()
        return 1

    except DuplicateDomainError as e:
        logger.error("[IMP:10][main] FQDN uniqueness violation: %s", str(e))
        return 2

    except RuntimeError as e:
        logger.error("[IMP:10][main] %s", str(e))
        return 1

    except Exception as e:  # noqa: EXC — top-level CLI handler for unexpected errors
        logger.error("[IMP:10][main] Unexpected error: %s", str(e))
        return 1


# endregion CLI

if __name__ == "__main__":
    sys.exit(main())
