# GREP_SUMMARY: config pydantic-settings BaseSettings PLATFORM_ env.platform
# STRUCTURE: ┌Settings(BaseSettings)┐ → ◇ env_prefix=PLATFORM_ → ◇ env_file=.env.platform → ⎋ settings singleton
# region MODULE_CONTRACT
## @purpose  Application configuration via pydantic-settings — reads PLATFORM_* from .env.platform
##           (генерируется `make sync-env`). Типобезопасный доступ к платформенным сервисам.
## @scope    FastAPI backend projects (template-backend, DevPlan 141 B1)
## @invariants
##   - env_prefix=PLATFORM_ — все переменные читаются из .env.platform
##   - extra=ignore — неизвестные PLATFORM_* переменные не падают
##   - Поля с default "" — сервис опционален (пустой DSN = не используется)
## @rationale pydantic-settings — best-practice для FastAPI: валидация типов + defaults
# endregion MODULE_CONTRACT

"""Application configuration via pydantic-settings — reads from .env.platform."""

from pydantic_settings import BaseSettings


class Settings(BaseSettings):
    # Platform services (from .env.platform, generated by `make sync-env`)
    postgres_dsn: str = ""
    redis_url: str = ""
    litellm_url: str = ""
    langfuse_url: str = ""
    minio_url: str = ""
    clickhouse_dsn: str = ""
    platform_domain: str = ""

    # Application
    port: int = 8000
    debug: bool = False

    model_config = {
        "env_prefix": "PLATFORM_",
        "env_file": ".env.platform",
        "extra": "ignore",
    }


settings = Settings()
