# GREP_SUMMARY: smoke_env_generated, ci-defaults, generated, test-env
# STRUCTURE: ┌ci_defaults┐ → ○ sorted keys → ⊕ SMOKE_ENV_GENERATED dict → ⎋ test env vars
# region MODULE_CONTRACT
"""## @purpose  AUTO-GENERATED CI defaults for smoke tests. Source: core/secret-definitions.yaml ci_default fields.
## @scope     Consumed by smoke tests to provide default values for all platform secrets.
## @invariants  Keys are uppercase strings matching secret names. Values are CI/test-only, never production.
"""
# endregion MODULE_CONTRACT
#
# GENERATED by generate_platform_env.py — DO NOT EDIT
# Changes will be overwritten on next generation.
#

from __future__ import annotations

SMOKE_ENV_GENERATED: dict[str, str] = {
    "AGE_SECRET_KEY": "AGE-SECRET-KEY-TEST1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZ",
    "CLICKHOUSE_PASSWORD": "test-clickhouse-pwd-not-for-prod",
    "GF_SECURITY_ADMIN_PASSWORD": "testpass",
    "GHCR_PULL_TOKEN": "ghp_test-token-for-ci-only",
    "HERMES_DASHBOARD_PASSWORD": "test-db-pwd",
    "LANGFUSE_INIT_ORG_ID": "ci-test-org",
    "LANGFUSE_INIT_PROJECT_ID": "ci-test-project",
    "LANGFUSE_INIT_USER_PASSWORD": "ci-test-langfuse-pwd",
    "LANGFUSE_PUBLIC_KEY": "ci-test-public-key",
    "LANGFUSE_SECRET_KEY": "ci-test-secret-key",
    "LITELLM_MASTER_KEY": "sk-ci-test-master-key",
    "MINIO_ROOT_PASSWORD": "minioadmin",
    "MINIO_ROOT_USER": "minioadmin",
    "NEXTAUTH_SECRET": "ci-test-nextauth-secret-32-chars-min!!",
    "OPENAI_API_KEY": "sk-ci-test-master-key",
    "PLATFORM_MASTER_EMAIL": "admin@test.local",
    "PLATFORM_MASTER_PASSWORD": "test-master-password",
    "POSTGRES_PASSWORD": "test-pg-pwd",
    "POSTGRES_USER": "postgres",
    "S3_ACCESS_KEY": "test-access-key",
    "S3_BUCKET": "test-bucket",
    "S3_SECRET_KEY": "test-secret-key",
    "SALT": "ci-test-salt-value",
    "TELEGRAM_BOT_TOKEN": "1234567890:test-telegram-bot-token-for-ci",
    "WEBNAMES_API_KEY": "*test-webnames-api-key",
}
