#!/usr/bin/env python3
# GREP_SUMMARY: converge-sudoers, reconcile-sudoers, r8, sudoers-d, visudo, atomic-write, drift-self-heal
# STRUCTURE: ▶ parse modules → ○ for each: ⚡ render_sudoers_rules (deploy/sudoers_generator public) → ⊕ build_sudoers_content → ◇ drift? → ⚡ atomic_write_sudoers (tmp → visudo -c -f → os.replace) → ⎋ drift entry {R8}
# region MODULE_CONTRACT
## @purpose  R8 reconcile_sudoers — sudoers.d drift detection + self-heal via visudo + atomic write.
##           Извлечён из reconciler.py (B9 T2, U-31).
## @scope    converge/sudoers.py: reconcile_sudoers, build_sudoers_content, atomic_write_sudoers,
##           safe_cleanup_tmp. Вызывается оркестратором reconciler.py.
## @invariants
##   - Рендер правил — через deploy/sudoers_generator.render_sudoers_rules (ПУБЛИЧНАЯ, T3 CS-2)
##   - visudo -c -f обязателен ДО os.replace; при fail — оригинал не тронут, tmp очищен
##   - Итоговый mode 0440 (root readable only)
## @rationale DevPlan 116 B9 D3: 8 доменов reconciler по модулям; shim _import_sudoers_generator
##            удалён (прямые импорты, §4.2).
## @changes  2026-08-01 · Extracted from reconciler.py (B9 T2)
# endregion MODULE_CONTRACT

from __future__ import annotations

import contextlib
import logging
import os
import tempfile
from pathlib import Path

import core.internal.bootstrap.converge.infra as infra
from core.internal.bootstrap.converge.infra import FILE_OP_TIMEOUT, SUDOERS_DIR, report_add, run_subprocess, set_exit
from core.internal.bootstrap.converge.volumes import parse_node_modules_yaml
from core.internal.bootstrap.deploy.sudoers_generator import render_sudoers_rules

logger = logging.getLogger(__name__)


# region FUNC_build_sudoers_content
## @purpose  Build complete sudoers file content for a module given rules.
## @param module_name  Module name (for header comment)
## @param rules        List of sudoers rule strings
## @return  Full file content as string
def build_sudoers_content(module_name: str, rules: list[str]) -> str:
    """Build sudoers file content with header and rules."""
    lines = [
        f"# platform module sudoers — {module_name}",
        "# Generated by reconciler.py (R8)",
        "# DO NOT edit manually — managed by core bootstrap",
        "",
    ]
    lines.extend(rules)
    lines.append("")
    return "\n".join(lines)


# endregion FUNC_build_sudoers_content


# region FUNC_atomic_write_sudoers
## @purpose  Atomic sudoers write: temp file → visudo -c -f validation → os.replace.
##           On validation failure: original file untouched, temp file cleaned up.
## @param target_path  Path to target sudoers file (e.g. /etc/sudoers.d/platform-nginx)
## @param content      Full sudoers file content
## @param module_name  Module name for temp file prefix
## @return  True if write + validation succeeded, False otherwise
def atomic_write_sudoers(target_path: Path, content: str, module_name: str) -> bool:
    """Write sudoers file atomically with visudo validation."""
    parent_dir = target_path.parent
    parent_dir.mkdir(parents=True, exist_ok=True)
    tmp_path: str = ""

    try:
        with tempfile.NamedTemporaryFile(
            mode="w",
            prefix=f".platform-sudoers-{module_name}-",
            suffix=".tmp",
            dir=str(parent_dir),
            delete=False,
        ) as tmp_fh:
            tmp_path = tmp_fh.name
            tmp_fh.write(content)

        # Set mode 0440 before validation
        os.chmod(tmp_path, 0o440)

        # Validate with visudo -c -f
        validate_r = run_subprocess(["visudo", "-c", "-f", tmp_path], timeout=FILE_OP_TIMEOUT)
        if validate_r.returncode != 0:
            logger.error(
                "[IMP:10][atomic_write_sudoers] visudo -c FAILED for %s — original untouched: %s",
                target_path,
                validate_r.stderr.strip(),
            )
            safe_cleanup_tmp(tmp_path)
            return False

        # Atomic replace via os.replace (same-filesystem atomic rename)
        os.replace(tmp_path, str(target_path))
        os.chmod(str(target_path), 0o440)
        logger.info("[IMP:9][atomic_write_sudoers] DONE: %s written and validated", target_path)
        return True

    except OSError as exc:
        logger.error("[IMP:10][atomic_write_sudoers] OS error writing %s: %s", target_path, exc)
        safe_cleanup_tmp(tmp_path)
        return False
    # noqa: EXC — catch-all after OSError already handled, prevents silent sudoers write failure
    except Exception as exc:  # noqa: EXC — catch-all after OSError already handled (best-effort: DEPLOY_BEST_EFFORT policy)
        logger.error("[IMP:9][atomic_write_sudoers] Unexpected error writing %s: %s", target_path, exc)
        safe_cleanup_tmp(tmp_path)
        return False


# endregion FUNC_atomic_write_sudoers


# region FUNC_safe_cleanup_tmp
## @purpose  Remove a temp file if it exists (best-effort)
def safe_cleanup_tmp(tmp_path: str) -> None:
    """Remove a temp file if it exists (best-effort cleanup)."""
    if tmp_path and os.path.exists(tmp_path):
        with contextlib.suppress(OSError):
            os.unlink(tmp_path)


# endregion FUNC_safe_cleanup_tmp


# region FUNC_reconcile_sudoers
## @purpose  Reconcile sudoers.d files for all enabled modules. Generates desired
##           content via sudoers_generator (template_engine.render_template native),
##           compares with actual files at SUDOERS_DIR, and self-heals via atomic write.
## @complexity O(N×M) — N=modules, M=sudoers files per module
## @io       stdout/stderr: LDD logs [IMP:7-10]
##           side-effect: temp file write, visudo -c, os.replace of sudoers files
## @param node_yaml_path  Path to node.yaml
## @param templates_dir   Path to templates/ directory (contains sudo-whitelist.template)
## @param dry_run         If True, only report planned mutations
## @param report_only     If True, skip mutations entirely
## @return  Drift report entry dict
## @edge-cases
##   - Docker daemon unavailable → status=fail, no further checks
##   - Module without compose.yml → skipped (not a docker module)
##   - All volumes exist → status=converged
##   - visudo validation fails → warn, original file unchanged
##   - SUDOERS_DIR does not exist → created on write
def reconcile_sudoers(
    node_yaml_path: str,
    templates_dir: str,
    dry_run: bool = False,
    report_only: bool = False,
) -> dict:
    """Reconcile sudoers.d files — detect drift and self-heal via atomic write.

    Returns a drift entry dict with status: ok|skipped|converged|mutated|warn|fail.
    """
    unit = "R8"
    logger.info("[IMP:8][converge][%s] START: reconcile_sudoers — drift detection and self-heal", unit)

    # ── Parse modules from node.yaml ──
    modules = parse_node_modules_yaml(node_yaml_path)
    if not modules:
        logger.info("[IMP:9][converge][%s] SKIP: No modules defined in node.yaml", unit)
        report_add(unit, "skipped", "No modules defined in node.yaml")
        return {"unit": unit, "status": "skipped", "detail": "No modules defined in node.yaml"}

    # Derive modules dir and platform root
    core_dir_path = Path(infra.core_dir)
    modules_dir = core_dir_path / "modules"
    platform_root = str(core_dir_path.parent)
    templates_dir_path = Path(templates_dir)

    mutated = 0
    errors = 0
    skipped = 0
    warnings = 0

    for mod in modules:
        mod_name = mod.get("name", "")
        if not mod_name or not mod.get("enabled", True):
            continue

        logger.info("[IMP:7][converge][%s] Processing module: %s", unit, mod_name)

        # Render rules via sudoers_generator (публичная render_sudoers_rules — T3 CS-2)
        try:
            rules = render_sudoers_rules(
                module_name=mod_name,
                modules_dir=modules_dir,
                templates_dir=templates_dir_path,
                platform_root=platform_root,
            )
        except (OSError, FileNotFoundError) as exc:
            logger.warning("[IMP:8][converge][%s] Failed to render rules for %s: %s", unit, mod_name, exc)
            errors += 1
            set_exit(2)
            continue

        if not rules:
            logger.info("[IMP:7][converge][%s] No sudoers rules for %s — skipping", unit, mod_name)
            skipped += 1
            continue

        # Build desired content
        desired_content = build_sudoers_content(mod_name, rules)

        # Read actual content
        sudoers_file = Path(SUDOERS_DIR) / f"platform-{mod_name}"
        actual_content = ""
        try:
            if sudoers_file.is_file():
                actual_content = sudoers_file.read_text()
        except OSError:
            actual_content = ""

        # Compare
        if actual_content == desired_content:
            logger.info("[IMP:9][converge][%s] CONVERGED: %s already matches desired state", unit, sudoers_file)
            report_add(unit, "converged", f"{sudoers_file.name} converged")
            continue

        # Drift detected
        if dry_run or report_only:
            logger.info("[IMP:9][converge][%s] WOULD update: %s (drift detected)", unit, sudoers_file)
            report_add(unit, "mutated", f"{sudoers_file.name} would be updated")
            mutated += 1
            set_exit(1)
            continue

        # Self-heal via atomic write
        logger.info("[IMP:8][converge][%s] Drift detected in %s — self-healing via atomic write", unit, sudoers_file)
        success = atomic_write_sudoers(sudoers_file, desired_content, mod_name)

        if success:
            logger.info("[IMP:9][converge][%s] DONE: %s updated successfully", unit, sudoers_file)
            report_add(unit, "mutated", f"{sudoers_file.name} updated")
            mutated += 1
            set_exit(1)
        else:
            logger.warning(
                "[IMP:9][converge][%s] WARN: visudo validation failed for %s — original untouched",
                unit,
                sudoers_file,
            )
            report_add(unit, "warn", f"{sudoers_file.name}: visudo validation failed")
            warnings += 1
            set_exit(1)

    # ── Final report ──
    if mutated > 0:
        status = "mutated"
        detail = f"{mutated} sudoers file(s) updated"
    elif warnings > 0:
        status = "warn"
        detail = f"{warnings} module(s) had visudo validation warnings"
    elif errors > 0:
        status = "fail"
        detail = f"{errors} module(s) had errors"
    else:
        status = "converged"
        detail = "All sudoers files match desired state"

    logger.info(
        "[IMP:9][converge][%s] DONE: mutated=%d errors=%d warnings=%d skipped=%d",
        unit,
        mutated,
        errors,
        warnings,
        skipped,
    )
    report_add(unit, status, detail)
    return {"unit": unit, "status": status, "detail": detail}


# endregion FUNC_reconcile_sudoers
