#!/usr/bin/env python3
# GREP_SUMMARY: converge-vhosts, verify-vhosts, r5, r6, detect-hosts-drift, nginx, vhost, orphan-vhost, nginx-t, overlay
# STRUCTURE: ▶ R5 detect_hosts_drift ┌/etc/hosts word-boundary grep (read-only)┐ → ⚡ R6 verify_vhosts ┌resolve overlay → per-domain conf + GENERATED marker → orphan detect → nginx -t┐ → ⎋ drift entries {R5,R6}
# region MODULE_CONTRACT
## @purpose  R5 detect_hosts_drift (read-only /etc/hosts stale entries) + R6 verify_vhosts
##           (nginx vhost integrity + orphan detection + nginx -t). Извлечены из reconciler.py
##           (B9 T2, U-31).
## @scope    converge/vhosts.py: detect_hosts_drift, verify_vhosts, resolve_nginx_overlay,
##           detect_orphan_vhosts, run_nginx_test. Вызываются оркестратором reconciler.py.
## @invariants
##   - R5 read-only — мутации НЕ выполняются (только WARN)
##   - R6: GENERATED marker "GENERATED by add-vhost.sh" обязателен (conf → WARN)
##   - R6: nginx container не запущен → nginx -t SKIP (WARN), остальные проверки продолжаются
##   - Оverlay резолвится: context → node-configs → node-configs стандартный путь (fallback)
## @rationale DevPlan 116 B9 D3: 8 доменов reconciler по модулям.
## @changes  2026-08-01 · Extracted from reconciler.py (B9 T2)
# endregion MODULE_CONTRACT

from __future__ import annotations

import logging
import os
import re
from pathlib import Path

from core.internal.bootstrap.converge.infra import (
    HOSTS_FILE,
    report_add,
    set_exit,
)
from core.internal.bootstrap.converge.projects import parse_projects_yaml
from core.internal.shared import docker_ops  # W1: docker ps/exec примитивы (гейт docker_sole_path)
from core.internal.shared.exceptions import ConfigNotFoundError, ConfigParseError

# R5/R6-канон таймаута — прямой импорт из shared SoT (pyright reportPrivateLocalImportUsage)
from core.internal.shared.timeouts import CONVERGE_DOCKER_TIMEOUT as DOCKER_TIMEOUT

logger = logging.getLogger(__name__)

# pyright: reportUnusedParameter = false
# R6-контракт оркестратора: verify_vhosts обязан принимать core_dir/dry_run/report_only (единая
# сигнатура R-юнитов); параметры не используются (verify read-only); ruff: ignore[ARG001] — тот же
# контракт (tool-conflict: pyright требует pyright-лидирующий комментарий, ruff — ruff-лидирующий).


# ═══════════════════════════════════════════════════════════════════
# R5 — detect_hosts_drift
# ═══════════════════════════════════════════════════════════════════
# region FUNC_detect_hosts_drift
## @purpose  Read-only detection of stale /etc/hosts entries for project names
##           from node.yaml. No mutation — only WARN.
## @io       stdout/stderr: WARN logs [IMP:9], JSON entries in report
## @param node_yaml_path  Path to node.yaml
## @return  Drift report entry dict
## @edge-cases
##   - /etc/hosts unreadable → WARN, not fail
##   - Project name matches substring of legitimate entry → word-boundary grep
def detect_hosts_drift(node_yaml_path: str) -> dict[str, str]:
    """Detect stale /etc/hosts entries for project names from node.yaml.

    Read-only — no mutations. Returns drift report entry.
    """
    unit = "R5"
    logger.info("[IMP:8][converge][%s] START: detect_hosts_drift — checking /etc/hosts for stale entries", unit)

    hosts_file = Path(HOSTS_FILE)
    if not hosts_file.is_file() or not os.access(str(hosts_file), os.R_OK):
        logger.warning("[IMP:8][converge][%s] WARN: %s not readable — skipping drift detection", unit, HOSTS_FILE)
        report_add(unit, "warn", f"Cannot read {HOSTS_FILE}")
        return {"unit": unit, "status": "warn", "detail": f"Cannot read {HOSTS_FILE}"}

    # Extract project names from node.yaml
    projects = parse_projects_yaml(node_yaml_path)
    if not projects:
        logger.info("[IMP:9][converge][%s] SKIP: No projects defined in node.yaml", unit)
        report_add(unit, "skipped", "No projects to check")
        return {"unit": unit, "status": "skipped", "detail": "No projects to check"}

    # Read /etc/hosts content
    try:
        hosts_content = hosts_file.read_text(encoding="utf-8")
    except OSError as exc:
        logger.warning("[IMP:8][converge][%s] WARN: Cannot read %s: %s", unit, HOSTS_FILE, exc)
        report_add(unit, "warn", f"Cannot read {HOSTS_FILE}: {exc}")
        return {"unit": unit, "status": "warn", "detail": f"Cannot read {HOSTS_FILE}: {exc}"}

    drift_found = 0
    for proj in projects:
        pname = proj.get("name", "")
        if not pname:
            continue

        # Word-boundary match to avoid substring false positives
        pattern = re.compile(r"\b" + re.escape(pname) + r"\b")
        matches = pattern.findall(hosts_content)
        if matches:
            logger.warning(
                "[IMP:9][converge][%s] WARN: Stale /etc/hosts entry found for project '%s': %s",
                unit,
                pname,
                matches,
            )
            report_add(unit, "warn", f"Stale /etc/hosts entry for {pname}")
            drift_found += 1
            set_exit(1)

    if drift_found == 0:
        logger.info("[IMP:9][converge][%s] SKIP: No stale /etc/hosts entries (converged)", unit)
        report_add(unit, "converged", "No stale /etc/hosts entries")
    else:
        logger.info("[IMP:9][converge][%s] DONE: %d drift(s) detected (read-only — no mutation)", unit, drift_found)

    return {
        "unit": unit,
        "status": "warn" if drift_found > 0 else "converged",
        "detail": f"{drift_found} stale entries found" if drift_found > 0 else "No stale entries",
    }


# endregion FUNC_detect_hosts_drift


# ═══════════════════════════════════════════════════════════════════
# R6 — verify_vhosts
# ═══════════════════════════════════════════════════════════════════
# region FUNC__preview_note
def _preview_note(unit: str, *, dry_run: bool, report_only: bool, plan: str) -> bool:
    """Печатать план dry-run/report-only; вернуть True если прогон preview-режима (AI-0031).

    ## @purpose  Общая ветка флагов для detect/verify-only юнитов converge — C901
    ##            основных функций не растёт.
    """
    if not (dry_run or report_only):
        return False
    logger.info("[IMP:9][converge][%s] DRY-RUN/REPORT-ONLY: %s", unit, plan)
    return True


# endregion FUNC__preview_note


# region FUNC_verify_vhosts
## @purpose  Read-only verification of nginx vhost config integrity.
##           Checks: (1) for each project with domain, <domain\>.conf exists;
##           (2) GENERATED marker present; (3) orphan vhosts without project
##           → WARN; (4) docker exec nginx nginx -t passes.
## @io       stdout/stderr: LDD logs [IMP:7-10], drift report entries
## @param node_yaml_path  Path to node.yaml
## @param converge_node   Node name for overlay resolution
## @param core_dir        Path to core/ directory
## @param dry_run         If True, only report planned mutations
## @param report_only     If True, skip mutations entirely
## @param overlay_base    Base directory for nginx overlay resolution (default /opt)
## @return  Drift report entry dict
## @edge-cases
##   - nginx container not running → WARN nginx -t, other checks proceed
##   - Project without domain → SKIP
##   - Orphan vhost (no project match) → WARN
##   - conf without GENERATED marker → WARN
def verify_vhosts(
    node_yaml_path: str,
    converge_node: str,
    core_dir: str,  # ruff: ignore[ARG001] — keyword-контракт оркестратора/тестов (core_dir=)
    # AI-0031 (DevPlan 17 T7.1): флаги подключены по образцу networks/runtime — юнит
    # verify-only; при dry_run/report_only печатается план («мутаций нет»),
    # detail помечается [dry-run]. Keyword-only: FBT (булевы позиционные запрещены)
    *,
    dry_run: bool = False,
    report_only: bool = False,
    overlay_base: str | None = None,
) -> dict[str, str]:
    """Verify nginx vhost config integrity.

    Returns a drift entry dict with status: ok|skipped|warn|fail.
    """
    unit = "R6"
    preview = bool(dry_run or report_only)
    if preview:
        logger.info(
            "[IMP:9][converge][%s] DRY-RUN/REPORT-ONLY: план мутаций ПУСТ (verify-only) — конфиги не пишутся, nginx не перезагружается",
            unit,
        )
    logger.info("[IMP:8][converge][%s] START: verify_vhosts — checking nginx vhost integrity", unit)

    node_yaml = Path(node_yaml_path)
    if not node_yaml.is_file():
        msg = f"node.yaml not found: {node_yaml_path}"
        logger.error("[IMP:10][converge][%s] FATAL: %s", unit, msg)
        report_add(unit, "fail", msg)
        set_exit(2)
        return {"unit": unit, "status": "fail", "detail": msg}

    # ── Get projects with domains from node.yaml ──
    projects = parse_projects_yaml(str(node_yaml))
    projects_with_domains = [p for p in projects if p.get("name") and p.get("domain")]

    # ── Determine nginx overlay directory ──
    overlay_dir = resolve_nginx_overlay(
        str(node_yaml), converge_node, base_dir=overlay_base if overlay_base else "/opt"
    )

    if not overlay_dir or not Path(overlay_dir).is_dir():
        logger.warning(
            "[IMP:8][converge][%s] WARN: nginx overlay directory not found at expected path — vhost verification limited",
            unit,
        )
        report_add(unit, "warn", "nginx overlay directory not found")

    vhost_errors = 0
    expected_domains: list[str] = []

    for proj in projects_with_domains:
        pname = proj.get("name", "")
        domain = proj.get("domain", "")
        if not pname or not domain:
            continue

        expected_domains.append(domain)

        # Check: vhost file exists
        if overlay_dir:
            vhost_file = Path(overlay_dir) / f"{domain}.conf"
            if vhost_file.is_file():
                # Check GENERATED marker (multi-line header: add-vhost.sh writes it on the
                # 1st line, vhost_renderer.py on the 2nd — DevPlan 153 T4)
                lines = [ln for ln in vhost_file.read_text().splitlines()[:10] if ln.strip()]
                marker_found = any("GENERATED by" in ln for ln in lines[:5])
                if marker_found:
                    logger.info("[IMP:7][converge][%s] OK: %s.conf has GENERATED marker", unit, domain)
                else:
                    logger.warning(
                        "[IMP:9][converge][%s] WARN: %s.conf exists but missing GENERATED marker — config",
                        unit,
                        domain,
                    )
                    report_add(unit, "warn", f"{domain}.conf: missing GENERATED marker")
            else:
                logger.error("[IMP:9][converge][%s] FAIL: Vhost file not found: %s/%s.conf", unit, overlay_dir, domain)
                report_add(unit, "fail", f"{domain}.conf not found")
                vhost_errors += 1
                set_exit(2)
        else:
            logger.error(
                "[IMP:9][converge][%s] FAIL: Vhost overlay directory not resolved — cannot verify %s.conf", unit, domain
            )
            report_add(unit, "fail", f"overlay dir not resolved for {domain}.conf")
            vhost_errors += 1
            set_exit(2)

    # ── Check for orphan vhosts ──
    if overlay_dir:
        detect_orphan_vhosts(overlay_dir, expected_domains, unit)

    # ── nginx -t validation ──
    run_nginx_test(unit)

    if not projects_with_domains:
        logger.info("[IMP:9][converge][%s] DONE: no domains to verify", unit)
        status = "skipped"
    elif vhost_errors == 0:
        logger.info("[IMP:9][converge][%s] DONE: %d vhost(s) verified — all OK", unit, len(projects_with_domains))
        status = "converged"
    else:
        logger.info(
            "[IMP:9][converge][%s] DONE: %d vhost(s), %d error(s)",
            unit,
            len(projects_with_domains),
            vhost_errors,
        )
        status = "fail"

    return {"unit": unit, "status": status, "detail": f"{len(projects_with_domains)} vhost(s), {vhost_errors} error(s)"}


# endregion FUNC_verify_vhosts


# region FUNC_resolve_nginx_overlay
## @purpose  Determine the nginx overlay directory for a given node
def resolve_nginx_overlay(node_yaml_path: str, converge_node: str, base_dir: str = "/opt") -> str | None:
    """Resolve nginx vhost directory from node.yaml context or node fallback."""
    try:
        from core.internal.shared.node_yaml import NodeYaml

        context_name = NodeYaml(node_yaml_path).get_context()
    except (ConfigNotFoundError, ConfigParseError):
        context_name = ""

    if context_name:
        candidate = f"{base_dir}/{context_name}/platform/modules/nginx"
        if Path(candidate).is_dir():
            return candidate
        logger.info("[IMP:7][resolve_nginx_overlay] Context overlay not found: %s", candidate)

    # Fallback: node-configs path
    candidate_node = f"{base_dir}/{converge_node}/overlays/nginx"
    if Path(candidate_node).is_dir():
        return candidate_node

    # Fallback: node-configs standard path
    candidate_nc = f"{base_dir}/node-configs/{converge_node}/overlays/nginx"
    if Path(candidate_nc).is_dir():
        return candidate_nc

    logger.warning("[IMP:8][resolve_nginx_overlay] No nginx overlay found for node=%s", converge_node)
    return None


# endregion FUNC_resolve_nginx_overlay


# region FUNC_detect_orphan_vhosts
## @purpose  Detect orphan vhost files with no matching project domain
def detect_orphan_vhosts(overlay_dir: str, expected_domains: list[str], unit: str) -> None:
    """Detect orphan vhost files — .conf files that don't match any project domain."""
    overlay_path = Path(overlay_dir)
    if not overlay_path.is_dir():
        return

    for vhost_file in overlay_path.glob("*.conf"):
        fname = vhost_file.name
        # Skip non-vhost files
        if fname in {
            "nginx.conf",
        }:
            continue

        domain_name = fname.removesuffix(".conf")
        if domain_name not in expected_domains:
            logger.warning(
                "[IMP:9][converge][%s] WARN: Orphan vhost detected — %s has no matching project in node.yaml",
                unit,
                fname,
            )
            report_add(unit, "warn", f"Orphan vhost: {fname}")


# endregion FUNC_detect_orphan_vhosts


# region FUNC_run_nginx_test
## @purpose  Run nginx -t via docker exec
def run_nginx_test(unit: str) -> None:
    """Run nginx -t syntax check via docker exec.

    If nginx container is not running, logs WARN and skips.
    """
    # First check if nginx container is running (W1: docker ps — shared/docker_ops)
    ps_r = docker_ops.docker_ps(format="{{.Names}}", timeout=DOCKER_TIMEOUT)
    running = [n.strip() for n in ps_r.stdout.splitlines() if n.strip()]

    if "nginx" not in running:
        logger.warning(
            "[IMP:8][converge][%s] WARN: nginx container not running — skipping nginx -t",
            unit,
        )
        report_add(unit, "warn", "nginx container not running — nginx -t skipped")
        return

    logger.info("[IMP:8][converge][%s] Running nginx -t...", unit)
    # W1: docker exec — shared/docker_ops (non-fatal)
    nginx_t_r = docker_ops.docker_exec("nginx", ["nginx", "-t"], timeout=DOCKER_TIMEOUT)

    if nginx_t_r.returncode == 0:
        logger.info("[IMP:9][converge][%s] OK: nginx -t passed", unit)
    else:
        logger.error(
            "[IMP:10][converge][%s] FAIL: nginx -t failed — nginx reload blocked: %s",
            unit,
            nginx_t_r.stderr.strip(),
        )
        report_add(unit, "fail", "nginx -t failed — reload blocked")
        set_exit(2)


# endregion FUNC_run_nginx_test
