"""
# GREP_SUMMARY: test_gen_env_platform, generate, validate_provides, argparse, platform-env, provides, profiles
# STRUCTURE: ▶ generate 1× (provides→PLATFORM_* vars) → ▶ argparse CLI args 1× → ⎋ LDD trajectory
# region MODULE_CONTRACT
## @purpose  Unit tests for gen_env_platform.py — generate(), validate_provides(), and CLI arg parsing.
##           No subprocess calls. Direct Python imports (strangler tier-1 Python module).
## @scope    Tests output structure contract (header, PLATFORM_DOMAIN, PLATFORM_PROVIDES,
##           PLATFORM_*_HOST/PORT/DSN/URL, PLATFORM_NO_PROXY) and argparse CLI argument parsing.
## @invariants
##   - All tests import the module directly via sys.path.insert
##   - Each test is decorated with @ldd_trajectory and asserts IMP:9 log presence
##   - tmp_path used for temp file creation
##   - No subprocess calls — tests call Python functions directly
## @rationale DevPlan 082 §9: Unit coverage for gen_env_platform.py per F3 (VerificationReport 082)
## @changes 2026-07-26 | Created (VerificationReport 082 F3)
# endregion MODULE_CONTRACT
"""

import logging
import sys
from pathlib import Path

import yaml

from tests._conftest.ldd import ldd_trajectory

logger = logging.getLogger(__name__)

# ── Import the module under test ──
_SCRIPT_DIR = Path(__file__).resolve().parent.parent.parent / "core" / "internal" / "scaffold"
sys.path.insert(0, str(_SCRIPT_DIR))
import contextlib

import gen_env_platform as gep

# ═══════════════════════════════════════════════════════════════════
# region Tests: generate output structure
# ═══════════════════════════════════════════════════════════════════


# 🧪 TRAP[TEST] · Regression · generate() output matches contract structure
# · Scenario: Minimal platform-env.yaml with postgres+redis provides → header, PLATFORM_* vars, NO_PROXY
# · Last fail: N/A (new test)
# · Remove if: generate() logic changes
@ldd_trajectory
def test_generate_output_matches_original(caplog):
    """generate() should produce output matching the .env.platform contract structure."""
    data = {
        "profiles": ["postgres", "redis"],
        "provides": {
            "postgres": {
                "host": "pgbouncer",
                "port": 6432,
                "dsn_template": "postgresql://${NAME}_user:***@pgbouncer:6432/${NAME}_db",
                "networks": ["shared-db-net"],
            },
            "redis": {
                "host": "redis",
                "port": 6379,
                "url_template": "redis://redis:6379/0",
                "networks": ["shared-cache-net"],
            },
        },
        "proxy": {
            "no_proxy_internal": "localhost,127.0.0.1,.local,postgres,pgbouncer,redis,clickhouse",
        },
    }

    lines = gep.generate(data, domain="test.local", project_name="myapp")

    # First line is the header
    assert lines[0] == "# GENERATED by ai-platform — DO NOT EDIT"

    # Contains PLATFORM_DOMAIN
    assert any("PLATFORM_DOMAIN=test.local" in line for line in lines)

    # Contains PLATFORM_PROVIDES
    assert any("PLATFORM_PROVIDES=" in line for line in lines)

    # Contains PLATFORM_*_HOST, PLATFORM_*_PORT, PLATFORM_*_DSN for each service
    assert any("PLATFORM_POSTGRES_HOST=pgbouncer" in line for line in lines)
    assert any("PLATFORM_POSTGRES_PORT=6432" in line for line in lines)
    assert any("PLATFORM_POSTGRES_DSN=postgresql://myapp_user:***@pgbouncer:6432/myapp_db" in line for line in lines)

    assert any("PLATFORM_REDIS_HOST=redis" in line for line in lines)
    assert any("PLATFORM_REDIS_PORT=6379" in line for line in lines)
    assert any("PLATFORM_REDIS_URL=redis://redis:6379/0" in line for line in lines)

    # Contains PLATFORM_NO_PROXY
    assert any("PLATFORM_NO_PROXY=" in line for line in lines)

    # Contains network variables
    assert any("PLATFORM_SHARED_DB_NET=shared-db-net" in line for line in lines)
    assert any("PLATFORM_SHARED_CACHE_NET=shared-cache-net" in line for line in lines)

    logger.critical(
        "[IMP:9][test] generate() produced %d lines with %d PLATFORM_* variables matching contract",
        len(lines),
        sum(1 for line in lines if line.startswith("PLATFORM_")),
    )


# endregion


# ═══════════════════════════════════════════════════════════════════
# region Tests: CLI argument parsing
# ═══════════════════════════════════════════════════════════════════


# 🧪 TRAP[TEST] · Regression · CLI --yaml, --domain, --name arguments parse correctly
# · Scenario: Various combinations of CLI args → correct values in parsed namespace
# · Last fail: N/A (new test)
# · Remove if: argparse setup in main() changes
@ldd_trajectory
def test_cli_args(caplog, monkeypatch, tmp_path):
    """CLI --yaml, --domain, --name arguments should parse correctly via argparse."""
    yaml_path = tmp_path / "platform-env.yaml"
    data = {
        "profiles": ["test"],
        "provides": {"test": {"host": "test-host"}},
        "proxy": {},
    }
    with open(str(yaml_path), "w") as f:
        yaml.dump(data, f)

    # Track what generate() receives from main()
    captured = {}

    def mock_generate(data, domain, project_name=""):
        captured["domain"] = domain
        captured["project_name"] = project_name
        return [
            "# GENERATED by ai-platform — DO NOT EDIT",
            f"PLATFORM_DOMAIN={domain}",
        ]

    monkeypatch.setattr(gep, "generate", mock_generate)

    # Test all args provided
    monkeypatch.setattr(
        sys,
        "argv",
        [
            "gen_env_platform.py",
            "--yaml",
            str(yaml_path),
            "--domain",
            "mydomain.com",
            "--name",
            "myapp",
        ],
    )

    with contextlib.suppress(SystemExit):
        gep.main()

    assert captured.get("domain") == "mydomain.com", f"Expected domain=mydomain.com, got {captured.get('domain')}"
    assert captured.get("project_name") == "myapp", f"Expected project_name=myapp, got {captured.get('project_name')}"

    logger.critical(
        "[IMP:9][test] CLI args parsed correctly: domain=%s, name=%s",
        captured.get("domain"),
        captured.get("project_name"),
    )


# endregion
