#!/usr/bin/env python3
# GREP_SUMMARY: security-updates unit-tests desired-config content-match noop package-install reboot-branches drift R5 LDD IMP:9
# STRUCTURE: ▶ config-content tests (auto-upgrades, 50unattended origins) → ◇ reboot on/off branches → ◇ ensure: noop/install/drift/write-fail → ◇ main exit codes → ⎋ LDD IMP:9 asserts
# region MODULE_CONTRACT
## @purpose  Unit tests for core/internal/bootstrap/security_updates.py (DevPlan 134 W1, L1).
##           Покрывают: желаемые конфиги (security-only origins), reboot-ветки (D2), content-match
##           no-op (инвариант 6), установку пакета, drift-перезапись (R5 negative), write-fail,
##           exit-коды main. LDD: IMP:9 траектория обязательна (Anti-Illusion Rule).
## @scope    Native pytest — прямые вызовы функций, tmp_path (Zero Hardcode Rule),
##           monkeypatch для файловых путей и apt-хелперов. БЕЗ subprocess.
## @rationale DevPlan 134 AC(1): каждая функция security_updates покрыта positive+negative.
## @changes 2026-08-04 | DevPlan 134 W1 — Created
# endregion MODULE_CONTRACT

import logging

import pytest

from core.internal.bootstrap import security_updates
from core.internal.bootstrap.lifecycle.helpers import system as helpers_system


@pytest.fixture()
def patch_paths(monkeypatch, tmp_path):
    """Redirect /etc apt paths to tmp_path (Zero Hardcode Rule)."""
    auto_file = tmp_path / "20auto-upgrades"
    unattended_file = tmp_path / "50unattended-upgrades"
    monkeypatch.setattr(security_updates, "AUTO_UPDATES_FILE", str(auto_file))
    monkeypatch.setattr(security_updates, "UNATTENDED_FILE", str(unattended_file))
    return auto_file, unattended_file


@pytest.fixture()
def pkg_installed(monkeypatch):
    """Package installed by default; install_apt_packages no-op."""
    monkeypatch.setattr(helpers_system, "is_pkg_installed", lambda pkg: True)
    monkeypatch.setattr(helpers_system, "install_apt_packages", lambda pkgs: None)
    return True


# region Tests: desired configs
class TestDesiredConfigs:
    """Content contracts of generated apt configs (S1 читает их в security_posture)."""

    def test_auto_upgrades_config_has_unattended_upgrade_directive(self):
        config = security_updates.desired_auto_upgrades_config()
        assert 'APT::Periodic::Unattended-Upgrade "1";' in config
        assert 'APT::Periodic::Update-Package-Lists "1";' in config
        assert "DO NOT EDIT MANUALLY" in config

    def test_unattended_config_security_only_origins(self):
        """Origins-Pattern — ТОЛЬКО security-источники (D1): -security/esm, НЕ -updates."""
        config = security_updates.desired_unattended_config(auto_reboot=True)
        assert "origin=Ubuntu,archive=${distro_codename}-security" in config
        assert "origin=UbuntuESM,archive=${distro_codename}-infra-security" in config
        assert "updates" not in config.replace("-security", "").replace(
            "Unattended-Upgrade::Automatic-Reboot", ""
        ).replace("Remove-Unused-Dependencies", "").replace(
            "// Generated by ai-platform security_updates.py (DevPlan 134) — DO NOT EDIT MANUALLY", ""
        )
        # Прямая проверка: никакой origin не содержит suite/archive ${distro_codename}-updates
        assert "-updates" not in config
        assert 'Unattended-Upgrade::AutoRemove "true";' in config

    def test_unattended_config_reboot_on_branch(self):
        """D2: auto_reboot=True → Automatic-Reboot true + 04:30 + WithUsers (live-restore)."""
        config = security_updates.desired_unattended_config(auto_reboot=True)
        assert 'Unattended-Upgrade::Automatic-Reboot "true";' in config
        assert 'Unattended-Upgrade::Automatic-Reboot-Time "04:30";' in config
        assert 'Unattended-Upgrade::Automatic-Reboot-WithUsers "true";' in config

    def test_unattended_config_reboot_off_branch(self):
        """D2: auto_reboot=False → reboot false, без WithUsers (SECURITY_AUTO_REBOOT=false)."""
        config = security_updates.desired_unattended_config(auto_reboot=False)
        assert 'Unattended-Upgrade::Automatic-Reboot "false";' in config
        assert "Automatic-Reboot-WithUsers" not in config
        assert "SECURITY_AUTO_REBOOT=false" in config


# endregion Tests: desired configs


# region Tests: ensure
class TestEnsure:
    """Idempotent ensure: no-op на совпадение, install при отсутствии, drift-перезапись (R5)."""

    def test_ensure_creates_configs_and_logs_imp9(self, patch_paths, pkg_installed, caplog):
        auto_file, unattended_file = patch_paths
        with caplog.at_level(logging.INFO):
            assert security_updates.ensure(auto_reboot=True) is True
        assert auto_file.exists()
        assert unattended_file.exists()
        assert auto_file.read_text() == security_updates.desired_auto_upgrades_config()
        assert unattended_file.read_text() == security_updates.desired_unattended_config(True)
        assert any("[IMP:9]" in r.message for r in caplog.records), "LDD: IMP:9 не найдено"

    def test_ensure_second_run_is_noop_content_stable(self, patch_paths, pkg_installed):
        """Инвариант 6: повторный вызов = no-op — содержимое идентично, install не вызывается."""
        auto_file, _ = patch_paths
        install_calls = []

        def _fake_install(pkgs):
            install_calls.append(pkgs)

        import core.internal.bootstrap.security_updates as su

        su.helpers_system.install_apt_packages = _fake_install  # type: ignore[assignment]
        assert su.ensure(auto_reboot=True) is True
        first_content = auto_file.read_text()
        assert su.ensure(auto_reboot=True) is True
        assert auto_file.read_text() == first_content
        assert install_calls == [], "повторный ensure не должен ставить пакет"

    def test_ensure_installs_package_when_missing(self, patch_paths, monkeypatch):
        monkeypatch.setattr(helpers_system, "is_pkg_installed", lambda pkg: False)
        installed = []
        monkeypatch.setattr(helpers_system, "install_apt_packages", lambda pkgs: installed.append(pkgs))
        assert security_updates.ensure(auto_reboot=True) is True
        assert installed == [[security_updates.SECURITY_PACKAGE]]

    def test_ensure_drift_rewrites_config(self, patch_paths, pkg_installed):
        """R5 negative: устаревший/чужой конфиг на диске → перезаписан желаемым."""
        auto_file, _ = patch_paths
        auto_file.write_text('APT::Periodic::Unattended-Upgrade "0";\nlegacy-garbage\n')
        assert security_updates.ensure(auto_reboot=True) is True
        assert auto_file.read_text() == security_updates.desired_auto_upgrades_config()

    def test_ensure_returns_false_on_write_error(self, patch_paths, pkg_installed, monkeypatch):
        def _boom(*args, **kwargs):
            raise OSError("read-only fs")

        monkeypatch.setattr(security_updates, "atomic_write_text", _boom)
        assert security_updates.ensure(auto_reboot=True) is False


# endregion Tests: ensure


# region Tests: main
class TestMain:
    """CLI-контракт: exit 0 на успех, 1 на fatal; --auto-reboot false → ветка reboot off."""

    def test_main_success_exit_0(self, patch_paths, pkg_installed):
        assert security_updates.main([]) == 0

    def test_main_auto_reboot_false_passes_false(self, patch_paths, pkg_installed, monkeypatch):
        captured = {}

        def _fake_ensure(auto_reboot):
            captured["auto_reboot"] = auto_reboot
            return True

        monkeypatch.setattr(security_updates, "ensure", _fake_ensure)
        assert security_updates.main(["--auto-reboot", "false"]) == 0
        assert captured["auto_reboot"] is False

    def test_main_fatal_exit_1(self, patch_paths, pkg_installed, monkeypatch, caplog):
        def _boom(auto_reboot):
            raise RuntimeError("apt repo unavailable")

        monkeypatch.setattr(security_updates, "ensure", _boom)
        with caplog.at_level(logging.INFO):
            assert security_updates.main([]) == 1
        assert any("[IMP:10]" in r.message for r in caplog.records)


# endregion Tests: main
