# GREP_SUMMARY: security-updates unit-tests desired-config content-match noop package-install reboot-branches drift R5 LDD IMP:9 DI path-params
# STRUCTURE: ▶ config-content tests (auto-upgrades, 50unattended origins) → ◇ reboot on/off branches → ◇ ensure: noop/install/drift/write-fail (DI path+callables) → ◇ main exit codes (DI ensure_fn/notify_fn) → ⎋ LDD IMP:9 asserts
# region MODULE_CONTRACT
## @purpose  Unit tests for core/internal/bootstrap/security_updates.py (DevPlan 134 W1, L1).
##           Покрывают: желаемые конфиги (security-only origins), reboot-ветки (D2), content-match
##           no-op (инвариант 6), установку пакета, drift-перезапись (R5 negative), write-fail,
##           exit-коды main. LDD: IMP:9 траектория обязательна (Anti-Illusion Rule).
## @scope    Native pytest — прямые вызовы функций, tmp_path (Zero Hardcode Rule),
##           DI (W-H DevPlan 163): пути конфигов и apt-хелперы — параметрами (0 патчей).
## @rationale DevPlan 134 AC(1): каждая функция security_updates покрыта positive+negative.
## @changes 2026-08-04 | DevPlan 134 W1 — Created
## @changes 2026-08-13 | DevPlan 163 W-H — DI-перевод: ensure(auto_updates_file/unattended_file/
##            pkg_installed_fn/install_pkgs_fn) + main(ensure_fn/notify_fn) — 15 патчей → 0
# endregion MODULE_CONTRACT

import logging

import pytest

from core.internal.bootstrap import security_updates

pytestmark = pytest.mark.static_audit
logger = logging.getLogger(__name__)


@pytest.fixture()
def patch_paths(tmp_path):
    """Redirect /etc apt paths to tmp_path (DI: передаются в ensure параметрами)."""
    auto_file = tmp_path / "20auto-upgrades"
    unattended_file = tmp_path / "50unattended-upgrades"
    return auto_file, unattended_file


# region Tests: desired configs
class TestDesiredConfigs:
    """Content contracts of generated apt configs (S1 читает их в security_posture)."""

    def test_auto_upgrades_config_has_unattended_upgrade_directive(self):
        config = security_updates.desired_auto_upgrades_config()
        assert 'APT::Periodic::Unattended-Upgrade "1";' in config
        assert 'APT::Periodic::Update-Package-Lists "1";' in config
        assert "DO NOT EDIT MANUALLY" in config

    def test_unattended_config_security_only_origins(self):
        """Origins-Pattern — ТОЛЬКО security-источники (D1): -security/esm, НЕ -updates."""
        config = security_updates.desired_unattended_config(auto_reboot=True)
        assert "origin=Ubuntu,archive=${distro_codename}-security" in config
        assert "origin=UbuntuESM,archive=${distro_codename}-infra-security" in config
        assert "updates" not in config.replace("-security", "").replace(
            "Unattended-Upgrade::Automatic-Reboot", ""
        ).replace("Remove-Unused-Dependencies", "").replace(
            "// Generated by ai-platform security_updates.py (DevPlan 134) — DO NOT EDIT MANUALLY", ""
        )
        # Прямая проверка: никакой origin не содержит suite/archive ${distro_codename}-updates
        assert "-updates" not in config
        assert 'Unattended-Upgrade::AutoRemove "true";' in config

    def test_unattended_config_reboot_on_branch(self):
        """D2: auto_reboot=True → Automatic-Reboot true + 04:30 + WithUsers (live-restore)."""
        config = security_updates.desired_unattended_config(auto_reboot=True)
        assert 'Unattended-Upgrade::Automatic-Reboot "true";' in config
        assert 'Unattended-Upgrade::Automatic-Reboot-Time "04:30";' in config
        assert 'Unattended-Upgrade::Automatic-Reboot-WithUsers "true";' in config

    def test_unattended_config_reboot_off_branch(self):
        """D2: auto_reboot=False → reboot false, без WithUsers (SECURITY_AUTO_REBOOT=false)."""
        config = security_updates.desired_unattended_config(auto_reboot=False)
        assert 'Unattended-Upgrade::Automatic-Reboot "false";' in config
        assert "Automatic-Reboot-WithUsers" not in config
        assert "SECURITY_AUTO_REBOOT=false" in config


# endregion Tests: desired configs


# region Tests: ensure
class TestEnsure:
    """Idempotent ensure: no-op на совпадение, install при отсутствии, drift-перезапись (R5)."""

    @staticmethod
    def _pkg_installed_true(_pkg: str) -> bool:
        return True

    @staticmethod
    def _pkg_install_noop(_pkgs: list[str]) -> None:
        return None

    def test_ensure_creates_configs_and_logs_imp9(self, patch_paths, caplog):
        auto_file, unattended_file = patch_paths
        with caplog.at_level(logging.INFO):
            assert (
                security_updates.ensure(
                    auto_reboot=True,
                    auto_updates_file=str(auto_file),
                    unattended_file=str(unattended_file),
                    pkg_installed_fn=self._pkg_installed_true,
                    install_pkgs_fn=self._pkg_install_noop,
                )
                is True
            )
        assert auto_file.exists()
        assert unattended_file.exists()
        assert auto_file.read_text() == security_updates.desired_auto_upgrades_config()
        assert unattended_file.read_text() == security_updates.desired_unattended_config(auto_reboot=True)
        assert any("[IMP:9]" in r.message for r in caplog.records), "LDD: IMP:9 не найдено"

    def test_ensure_second_run_is_noop_content_stable(self, patch_paths):
        """Инвариант 6: повторный вызов = no-op — содержимое идентично, install не вызывается."""
        auto_file, unattended_file = patch_paths
        install_calls: list = []

        assert (
            security_updates.ensure(
                auto_reboot=True,
                auto_updates_file=str(auto_file),
                unattended_file=str(unattended_file),
                pkg_installed_fn=self._pkg_installed_true,
                install_pkgs_fn=install_calls.append,
            )
            is True
        )
        first_content = auto_file.read_text()
        assert (
            security_updates.ensure(
                auto_reboot=True,
                auto_updates_file=str(auto_file),
                unattended_file=str(unattended_file),
                pkg_installed_fn=self._pkg_installed_true,
                install_pkgs_fn=install_calls.append,
            )
            is True
        )
        assert auto_file.read_text() == first_content
        assert install_calls == [], "повторный ensure не должен ставить пакет"

    def test_ensure_installs_package_when_missing(self, patch_paths):
        auto_file, unattended_file = patch_paths
        installed: list = []
        assert (
            security_updates.ensure(
                auto_reboot=True,
                auto_updates_file=str(auto_file),
                unattended_file=str(unattended_file),
                pkg_installed_fn=lambda _: False,
                install_pkgs_fn=installed.append,
            )
            is True
        )
        assert installed == [[security_updates.SECURITY_PACKAGE]]

    def test_ensure_drift_rewrites_config(self, patch_paths):
        """R5 negative: устаревший/чужой конфиг на диске → перезаписан желаемым."""
        auto_file, unattended_file = patch_paths
        auto_file.write_text('APT::Periodic::Unattended-Upgrade "0";\ngarbage\n')
        assert (
            security_updates.ensure(
                auto_reboot=True,
                auto_updates_file=str(auto_file),
                unattended_file=str(unattended_file),
                pkg_installed_fn=self._pkg_installed_true,
                install_pkgs_fn=self._pkg_install_noop,
            )
            is True
        )
        assert auto_file.read_text() == security_updates.desired_auto_upgrades_config()

    # GUARD-PRESERVE (168): security-updates guard — R5-negative write-error → ensure() False (никогда не raise), единственное покрытие write-fail ветки
    def test_ensure_returns_false_on_write_error(self, patch_paths):
        """R5 negative: запись в read-only директорию → ensure() False (никогда не raise)."""
        auto_file, _ = patch_paths
        ro_dir = auto_file.parent / "read-only"
        ro_dir.mkdir()
        ro_dir.chmod(0o500)
        try:
            assert (
                security_updates.ensure(
                    auto_reboot=True,
                    auto_updates_file=str(ro_dir / "20auto-upgrades"),
                    unattended_file=str(ro_dir / "50unattended-upgrades"),
                    pkg_installed_fn=self._pkg_installed_true,
                    install_pkgs_fn=self._pkg_install_noop,
                )
                is False
            )
        finally:
            ro_dir.chmod(0o700)


# endregion Tests: ensure


# region Tests: main
class TestMain:
    """CLI-контракт: exit 0 на успех, 1 на fatal; --auto-reboot false → ветка reboot off."""

    # GUARD-PRESERVE (168): security-updates guard — CLI exit 0 контракт main (fail-fast канон, DI ensure_fn), единственное покрытие success-ветки main
    def test_main_success_exit_0(self):
        assert (
            security_updates.main(
                [],
                ensure_fn=lambda _: True,
                notify_fn=lambda _: None,
            )
            == 0
        )

    def test_main_auto_reboot_false_passes_false(self):
        captured = {}

        def _fake_ensure(auto_reboot):
            captured["auto_reboot"] = auto_reboot
            return True

        assert (
            security_updates.main(
                ["--auto-reboot", "false"],
                ensure_fn=_fake_ensure,
                notify_fn=lambda _: None,
            )
            == 0
        )
        assert captured["auto_reboot"] is False

    def test_main_fatal_exit_1(self, caplog):
        def _boom(auto_reboot):
            msg = "apt repo unavailable"
            raise RuntimeError(msg)

        sent: list = []
        with caplog.at_level(logging.INFO):
            assert (
                security_updates.main(
                    [],
                    ensure_fn=_boom,
                    notify_fn=lambda reason: sent.append(reason) or True,
                )
                == 1
            )
        assert any("[IMP:10]" in r.message for r in caplog.records)
        assert sent, "162 W6-2: failure-путь обязан вызвать telegram-хук"

    def test_main_failure_calls_telegram_notifier(self, caplog):
        """162 W6-2: исключение в ensure → notify_fn вызывается с причиной, exit 1."""

        def _boom(auto_reboot):
            msg = "dpkg lock held"
            raise RuntimeError(msg)

        sent: list = []

        def _fake_send(reason):
            sent.append(reason)

        with caplog.at_level(logging.INFO):
            assert security_updates.main([], ensure_fn=_boom, notify_fn=_fake_send) == 1, (
                "исключение → exit 1 сохраняется"
            )
        assert sent, "OnError → notify_fn обязан вызываться (W6-2)"
        assert "dpkg lock held" in sent[0], "причина провала передаётся в notify_fn"
        logger.critical("[IMP:9][test] main failure → notify_fn с причиной — OK (W6-2)")

    def test_main_ensure_false_calls_telegram_notifier(self, caplog):
        """162 W6-2: ensure() → False (write/apt сбой) тоже не молчит — notify_fn, exit 1."""
        sent: list = []

        def _fake_send(reason):
            sent.append(reason)

        with caplog.at_level(logging.INFO):
            assert security_updates.main([], ensure_fn=lambda _: False, notify_fn=_fake_send) == 1
        assert sent, "ensure False → notify_fn обязан вызываться (W6-2)"
        assert "ensure returned False" in sent[0]
        logger.critical("[IMP:9][test] main ensure False → notify_fn с причиной — OK (W6-2)")

    def test_notify_config_failure_missing_env_non_fatal(self, caplog, monkeypatch):
        """162 W6-2: send_telegram без токена/чата → False (WARN) — хук non-fatal, exit 1 сохраняется."""
        monkeypatch.delenv("TELEGRAM_BOT_TOKEN", raising=False)
        monkeypatch.delenv("TELEGRAM_CHAT_ID", raising=False)
        with caplog.at_level(logging.INFO):
            assert security_updates.main([], ensure_fn=lambda _: False) == 1, "notifier failure не меняет exit-код"
        assert "Failure notification not delivered" in caplog.text
        logger.critical("[IMP:9][test] notifier missing env → WARN, exit 1 сохраняется — OK (W6-2)")


# endregion Tests: main
