"""
# GREP_SUMMARY: test_gen_env_platform, generate, validate_provides, argparse, platform-env, provides, profiles, credentials, password-injection, DSN
# STRUCTURE: ▶ generate 1× (provides→PLATFORM_* vars) → ▶ password-injection (DSN *** → реальный пароль) ×3 → ▶ argparse CLI args 2× → ⎋ LDD trajectory
# region MODULE_CONTRACT
## @purpose  Unit tests for gen_env_platform.py — generate(), validate_provides(), CLI arg parsing,
##           and DevPlan 133 W2.3 password-injection (credentials → DSN '***' → реальный пароль).
##           No subprocess calls. Direct Python imports (strangler tier-1 Python module).
## @scope    Tests output structure contract (header, PLATFORM_DOMAIN, PLATFORM_PROVIDES,
##           PLATFORM_*_HOST/PORT/DSN/URL, PLATFORM_NO_PROXY), CLI argument parsing,
##           and credentials injection (DSN with *** / with password / without file).
## @invariants
##   - All tests import the module directly via sys.path.insert
##   - Each test is decorated with @ldd_trajectory and asserts IMP:9 log presence
##   - tmp_path used for temp file creation
##   - No subprocess calls — tests call Python functions directly
## @rationale DevPlan 082 §9: Unit coverage for gen_env_platform.py per F3 (VerificationReport 082).
##            DevPlan 133 W2.4: password-injection coverage (AC 4 — .env.platform (пере)генерация
##            подставляет реальный пароль роли в DSN при наличии .platform-db.env).
## @changes 2026-07-26 | Created (VerificationReport 082 F3)
## @changes 2026-08-03 | DevPlan 133 W2 — +password-injection tests (credentials param)
# endregion MODULE_CONTRACT
"""

import logging
import sys
from pathlib import Path

import yaml

from tests._conftest.ldd import ldd_trajectory

logger = logging.getLogger(__name__)

# ── Import the module under test ──
_SCRIPT_DIR = Path(__file__).resolve().parent.parent.parent / "core" / "internal" / "scaffold"
sys.path.insert(0, str(_SCRIPT_DIR))

import gen_env_platform as gep
import pytest

pytestmark = pytest.mark.static_audit

# ═══════════════════════════════════════════════════════════════════
# region Tests: generate output structure
# ═══════════════════════════════════════════════════════════════════


# 🧪 TRAP[TEST] · Regression · generate() output matches contract structure
# · Scenario: Minimal platform-env.yaml with postgres+redis provides → header, PLATFORM_* vars, NO_PROXY
# · Last fail: N/A (new test)
# · Remove if: generate() logic changes
@ldd_trajectory
def test_generate_output_matches_original(caplog):
    """generate() should produce output matching the .env.platform contract structure."""
    data = {
        "profiles": ["postgres", "redis"],
        "provides": {
            "postgres": {
                "host": "pgbouncer",
                "port": 6432,
                "dsn_template": "postgresql://${NAME}_user:***@pgbouncer:6432/${NAME}_db",
                "networks": ["shared-db-net"],
            },
            "redis": {
                "host": "redis",
                "port": 6379,
                "url_template": "redis://redis:6379/0",
                "networks": ["shared-cache-net"],
            },
        },
        "proxy": {
            "no_proxy_internal": "localhost,127.0.0.1,.local,postgres,pgbouncer,redis,clickhouse",
        },
    }

    lines = gep.generate(data, domain="test.local", project_name="myapp")

    # First line is the header
    assert lines[0] == "# GENERATED by ai-platform — DO NOT EDIT"

    # Contains PLATFORM_DOMAIN
    assert any("PLATFORM_DOMAIN=test.local" in line for line in lines)

    # Contains PLATFORM_PROVIDES
    assert any("PLATFORM_PROVIDES=" in line for line in lines)

    # Contains PLATFORM_*_HOST, PLATFORM_*_PORT, PLATFORM_*_DSN for each service
    assert any("PLATFORM_POSTGRES_HOST=pgbouncer" in line for line in lines)
    assert any("PLATFORM_POSTGRES_PORT=6432" in line for line in lines)
    assert any("PLATFORM_POSTGRES_DSN=postgresql://myapp_user:***@pgbouncer:6432/myapp_db" in line for line in lines)

    assert any("PLATFORM_REDIS_HOST=redis" in line for line in lines)
    assert any("PLATFORM_REDIS_PORT=6379" in line for line in lines)
    assert any("PLATFORM_REDIS_URL=redis://redis:6379/0" in line for line in lines)

    # Contains PLATFORM_NO_PROXY
    assert any("PLATFORM_NO_PROXY=" in line for line in lines)

    # Contains network variables
    assert any("PLATFORM_SHARED_DB_NET=shared-db-net" in line for line in lines)
    assert any("PLATFORM_SHARED_CACHE_NET=shared-cache-net" in line for line in lines)

    logger.critical(
        "[IMP:9][test] generate() produced %d lines with %d PLATFORM_* variables matching contract",
        len(lines),
        sum(1 for line in lines if line.startswith("PLATFORM_")),
    )


# endregion Tests: generate output structure


# ═══════════════════════════════════════════════════════════════════
# region Tests: password-injection (DevPlan 133 W2.3)
# ═══════════════════════════════════════════════════════════════════

_POSTGRES_DSN_DATA = {
    "profiles": ["postgres"],
    "provides": {
        "postgres": {
            "host": "pgbouncer",
            "port": 6432,
            "dsn_template": "postgresql://${NAME}_user:***@pgbouncer:6432/${NAME}_db",
            "networks": ["shared-db-net"],
        },
    },
    "proxy": {},
}


# 🧪 TRAP[TEST] · Regression · DSN with '***' placeholder without credentials (backward compat)
# · Scenario: no credentials → DSN keeps '***' exactly as before (tronyx-site compat)
# · Last fail: N/A (new test)
# · Remove if: password-injection logic changes
@ldd_trajectory
def test_dsn_without_credentials_keeps_placeholder(caplog):
    """Without credentials → DSN unchanged (*** placeholder, backward compatibility)."""
    lines = gep.generate(_POSTGRES_DSN_DATA, domain="test.local", project_name="myapp")
    dsn = next(line for line in lines if line.startswith("PLATFORM_POSTGRES_DSN="))
    assert dsn == "PLATFORM_POSTGRES_DSN=postgresql://myapp_user:***@pgbouncer:6432/myapp_db"
    assert "***" in dsn

    logger.critical("[IMP:9][test] no-credentials OK — DSN keeps *** placeholder")


# 🧪 TRAP[TEST] · Regression · DSN with credentials → real password injected (*** replaced)
# · Scenario: credentials dict (PLATFORM_POSTGRES_*) → password replaces '***', user/db substituted
# · Last fail: 2026-08-03 — .env.platform на ноде содержал *** → приложения не могли подключиться
# · Remove if: password-injection logic changes
@ldd_trajectory
def test_dsn_with_credentials_injects_password(caplog):
    """With credentials → real password replaces '***', actual role/db substituted in DSN."""
    creds = {
        "PLATFORM_POSTGRES_DB": "myapp_db",
        "PLATFORM_POSTGRES_USER": "myapp_user",
        "PLATFORM_POSTGRES_PASSWORD": "real-secret-password",
    }
    lines = gep.generate(_POSTGRES_DSN_DATA, domain="test.local", project_name="myapp", credentials=creds)
    dsn = next(line for line in lines if line.startswith("PLATFORM_POSTGRES_DSN="))
    assert dsn == "PLATFORM_POSTGRES_DSN=postgresql://myapp_user:real-secret-password@pgbouncer:6432/myapp_db"
    assert "***" not in dsn

    logger.critical("[IMP:9][test] credentials OK — password injected into DSN, *** removed")


# 🧪 TRAP[TEST] · Regression · credentials file absent → load_credentials returns {} (no crash)
# · Scenario: load_credentials() with missing .platform-db.env → {} → DSN unchanged
# · Last fail: N/A (new test)
# · Remove if: load_credentials() logic changes
@ldd_trajectory
def test_load_credentials_missing_file_returns_empty(caplog, tmp_path):
    """load_credentials() with no credentials file → {} (graceful, no crash)."""
    creds = gep.load_credentials(project_dir=str(tmp_path))
    assert creds == {}

    logger.critical("[IMP:9][test] load_credentials missing-file OK — returned {}")


# 🧪 TRAP[TEST] · Regression · credentials file present → load_credentials parses it
# · Scenario: .platform-db.env in project dir → parsed dict with all 3 keys
# · Last fail: N/A (new test)
# · Remove if: load_credentials() logic changes
@ldd_trajectory
def test_load_credentials_parses_platform_db_env(caplog, tmp_path):
    """load_credentials() parses .platform-db.env from project dir."""
    (tmp_path / ".platform-db.env").write_text(
        "PLATFORM_POSTGRES_DB=myapp_db\nPLATFORM_POSTGRES_USER=myapp_user\nPLATFORM_POSTGRES_PASSWORD=secret-123\n"
    )
    creds = gep.load_credentials(project_dir=str(tmp_path))
    assert creds["PLATFORM_POSTGRES_DB"] == "myapp_db"
    assert creds["PLATFORM_POSTGRES_USER"] == "myapp_user"
    assert creds["PLATFORM_POSTGRES_PASSWORD"] == "secret-123"

    logger.critical("[IMP:9][test] load_credentials parse OK — 3 keys from .platform-db.env")


# endregion Tests: password-injection (DevPlan 133 W2.3)


# ═══════════════════════════════════════════════════════════════════
# region Tests: CLI argument parsing
# ═══════════════════════════════════════════════════════════════════


# 🧪 TRAP[TEST] · Regression · CLI --yaml, --domain, --name arguments parse correctly
# · Scenario: main(argv) с --yaml/--domain/--name/--output → реальный generate: domain и
# ·   project_name (${NAME}) в выходном файле; credentials=None → *** сохранён (167 D4, 0 патчей)
# · Last fail: N/A (new test)
# · Remove if: argparse setup in main() changes
@ldd_trajectory
def test_cli_args(caplog, tmp_path):
    """CLI --yaml, --domain, --name flow into generate() via реальный main(argv) (0 monkeypatch)."""
    yaml_path = tmp_path / "platform-env.yaml"
    data = {
        "profiles": ["test"],
        "provides": {
            "test": {"host": "test-host", "dsn_template": "postgresql://${NAME}_user:***@test-host:6432/${NAME}_db"}
        },
        "proxy": {},
    }
    with Path(str(yaml_path)).open("w", encoding="utf-8") as f:
        yaml.dump(data, f)

    # DI (167 D4): main(argv=[...]) — argv-инъекция вместо monkeypatch sys.argv + gep.generate
    out_file = tmp_path / "out.env"
    rc = gep.main(["--yaml", str(yaml_path), "--domain", "mydomain.com", "--name", "myapp", "--output", str(out_file)])

    assert rc == 0, f"main должен вернуть 0, got {rc}"
    content = out_file.read_text(encoding="utf-8")
    assert "PLATFORM_DOMAIN=mydomain.com" in content, f"domain должен пройти в generate: {content}"
    assert "PLATFORM_TEST_DSN=postgresql://myapp_user:***@test-host:6432/myapp_db" in content, (
        "project_name должен пройти в generate (${NAME} substitution); credentials=None → *** сохранён"
    )

    logger.critical(
        "[IMP:9][test] CLI args parsed correctly: domain=%s, name=%s",
        "mydomain.com",
        "myapp",
    )


# 🧪 TRAP[TEST] · Regression · CLI --project-dir resolves yaml/name/output and injects credentials
# · Scenario: project dir with ai-platform.yaml + .platform-db.env → output written with real password
# · Last fail: N/A (new test)
# · Remove if: --project-dir CLI resolution logic changes
@ldd_trajectory
def test_cli_project_dir_writes_env_with_credentials(caplog, tmp_path):
    """CLI --project-dir: auto-resolve yaml/name/domain/output + credentials injection (main(argv) DI)."""
    yaml_path = tmp_path / "platform-env.yaml"
    with Path(str(yaml_path)).open("w", encoding="utf-8") as f:
        yaml.dump(_POSTGRES_DSN_DATA, f)
    proj_dir = tmp_path / "proj"
    proj_dir.mkdir()
    (proj_dir / "ai-platform.yaml").write_text("name: myapp\ntarget_node: test-node\n")
    (proj_dir / ".platform-db.env").write_text(
        "PLATFORM_POSTGRES_DB=myapp_db\nPLATFORM_POSTGRES_USER=myapp_user\nPLATFORM_POSTGRES_PASSWORD=cli-secret\n"
    )

    # DI (167 D4): argv-инъекция вместо monkeypatch sys.argv
    rc = gep.main(["--project-dir", str(proj_dir)])

    env_file = proj_dir / ".env.platform"
    assert rc == 0
    assert env_file.is_file()
    content = env_file.read_text()
    assert "PLATFORM_POSTGRES_DSN=postgresql://myapp_user:cli-secret@pgbouncer:6432/myapp_db" in content
    assert "PLATFORM_DOMAIN=ai-platform.local" in content

    logger.critical("[IMP:9][test] CLI --project-dir OK — .env.platform written with injected password")


# endregion Tests: CLI argument parsing


# ═══════════════════════════════════════════════════════════════════
# region Tests: DR-H3 credentialed PLATFORM_REDIS_URL
# ═══════════════════════════════════════════════════════════════════


# 🧪 TRAP[TEST] · Regression · DR-H3 fix (аудит DevPlan 010)
# · Scenario: redis requirepass обязателен (${REDIS_PASSWORD:?}) — credential-free URL = NOAUTH
# · Last fail: PLATFORM_REDIS_URL=redis://redis:6379/0 без пароля
# · Remove if: redis перейдёт в no-auth режим (dev-only)
@ldd_trajectory
def test_redis_url_credentialed_from_credentials_dict(caplog, monkeypatch):
    """${REDIS_PASSWORD} в шаблоне → подстановка из credentials dict (приоритет над env)."""
    monkeypatch.delenv("REDIS_PASSWORD", raising=False)
    data = {
        "profiles": ["redis"],
        "provides": {
            "redis": {
                "host": "redis",
                "port": 6379,
                "url_template": "redis://:${REDIS_PASSWORD}@redis:6379/0",
                "networks": ["shared-cache-net"],
            },
        },
    }

    lines = gep.generate(
        data, domain="test.local", project_name="myapp", credentials={"REDIS_PASSWORD": "pw-from-dict"}
    )

    print("--- LDD TRAJECTORY ---")
    for line in lines:
        if "REDIS" in line and "PASSWORD" not in line:
            print(line)
    print("--- END LDD TRAJECTORY ---")

    # [IMP:9] бизнес-инвариант: URL креденцированный, пароль из dict, env не использован
    url_line = next(line for line in lines if line.startswith("PLATFORM_REDIS_URL="))
    assert url_line == "PLATFORM_REDIS_URL=redis://:pw-from-dict@redis:6379/0"
    assert "${REDIS_PASSWORD}" not in url_line, "плейсхолдер остался — подстановка не выполнена"


@ldd_trajectory
def test_redis_url_credentialed_fallback_env(monkeypatch):
    """Нет ключа в credentials → fallback на env REDIS_PASSWORD."""
    monkeypatch.setenv("REDIS_PASSWORD", "pw-from-env")
    data = {
        "profiles": ["redis"],
        "provides": {
            "redis": {
                "host": "redis",
                "port": 6379,
                "url_template": "redis://:${REDIS_PASSWORD}@redis:6379/0",
                "networks": ["shared-cache-net"],
            },
        },
    }

    lines = gep.generate(data, domain="test.local", project_name="myapp")

    assert any("PLATFORM_REDIS_URL=redis://:pw-from-env@redis:6379/0" in line for line in lines)


def test_redis_url_placeholder_without_source_warns(caplog, monkeypatch):
    """Ни credentials, ни env → литерал-плейсхолдер + IMP:7 warning (loud NOAUTH сигнал)."""
    monkeypatch.delenv("REDIS_PASSWORD", raising=False)
    caplog.set_level(logging.WARNING)
    data = {
        "profiles": ["redis"],
        "provides": {
            "redis": {
                "host": "redis",
                "port": 6379,
                "url_template": "redis://:${REDIS_PASSWORD}@redis:6379/0",
                "networks": ["shared-cache-net"],
            },
        },
    }

    lines = gep.generate(data, domain="test.local", project_name="myapp")

    assert any("PLATFORM_REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379/0" in line for line in lines)
    assert any("${REDIS_PASSWORD} placeholder has no source" in r.getMessage() for r in caplog.records), (
        "нет loud-warning о NOAUTH — silent-деградация запрещена (DR-H3)"
    )


def test_redis_url_without_placeholder_untouched():
    """Шаблон без ${REDIS_PASSWORD} не трогается (байт-совместимость легаси)."""
    data = {
        "profiles": ["redis"],
        "provides": {
            "redis": {
                "host": "redis",
                "port": 6379,
                "url_template": "redis://redis:6379/0",
                "networks": ["shared-cache-net"],
            },
        },
    }

    lines = gep.generate(data, domain="test.local", project_name="myapp", credentials={"REDIS_PASSWORD": "x"})

    assert any("PLATFORM_REDIS_URL=redis://redis:6379/0" in line for line in lines)


def test_sot_platform_infra_redis_template_is_credentialed():
    """SoT core/platform-infra.yaml: redis url_template содержит ${REDIS_PASSWORD} (audit gap Row15).

    Раньше SoT эмитил credential-free URL при обязательном requirepass — контракт-vs-код разрыв.
    """
    import yaml as _yaml

    sot_path = Path(__file__).resolve().parent.parent.parent / "core" / "platform-infra.yaml"
    with sot_path.open(encoding="utf-8") as fh:
        data = _yaml.safe_load(fh)
    tmpl = str(data["provides"]["redis"]["url_template"])

    assert "${REDIS_PASSWORD}" in tmpl, f"SoT url_template credential-free (DR-H3 regression): {tmpl}"
    logger.critical("[IMP:9][test] SoT redis url_template is credentialed (%s...)", tmpl[:24])


# endregion Tests: DR-H3 credentialed PLATFORM_REDIS_URL
