# GREP_SUMMARY: env_defaults_generated, ci-defaults, constants, generated
# STRUCTURE: ┌ci_defaults┐ → ○ sorted keys → ⊕ _PREFIX_* constants → ⎋ test helpers
# region MODULE_CONTRACT
"""## @purpose  AUTO-GENERATED CI default constants for test helpers. Source: core/secret-definitions.yaml ci_default fields.
## @scope     Consumed by test helpers to provide default values for all platform secrets.
## @invariants  Each constant is named _{SECRET_NAME}. Values are CI/test-only, never production.
"""
# endregion MODULE_CONTRACT
#
# GENERATED by generate_platform_env.py — DO NOT EDIT
# Changes will be overwritten on next generation.
#

from __future__ import annotations

_AGE_SECRET_KEY: str = "AGE-SECRET-KEY-TEST1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZ"
_API_SERVER_KEY: str = "test-api-server-key-for-ci-only"
_CLICKHOUSE_PASSWORD: str = "test-clickhouse-pwd-not-for-prod"
_GF_SECURITY_ADMIN_PASSWORD: str = "testpass"
_GHCR_PULL_TOKEN: str = "ghp_test-token-for-ci-only"
_HERMES_DASHBOARD_PASSWORD: str = "test-db-pwd"
_LANGFUSE_INIT_ORG_ID: str = "ci-test-org"
_LANGFUSE_INIT_PROJECT_ID: str = "ci-test-project"
_LANGFUSE_INIT_USER_PASSWORD: str = "ci-test-langfuse-pwd"
_LANGFUSE_PUBLIC_KEY: str = "ci-test-public-key"
_LANGFUSE_SECRET_KEY: str = "ci-test-secret-key"
_LITELLM_MASTER_KEY: str = "sk-ci-test-master-key"
_MINIO_ROOT_PASSWORD: str = "minioadmin"
_MINIO_ROOT_USER: str = "minioadmin"
_NEXTAUTH_SECRET: str = "ci-test-nextauth-secret-32-chars-min!!"
_PLATFORM_MASTER_EMAIL: str = "admin@test.local"
_PLATFORM_MASTER_PASSWORD: str = "test-master-password"
_POSTGRES_PASSWORD: str = "test-pg-pwd"
_POSTGRES_USER: str = "postgres"
_S3_ACCESS_KEY: str = "test-access-key"
_S3_BUCKET: str = "test-bucket"
_S3_SECRET_KEY: str = "test-secret-key"
_SALT: str = "ci-test-salt-value"
_TELEGRAM_BOT_TOKEN: str = "1234567890:test-telegram-bot-token-for-ci"
_WEBNAMES_API_KEY: str = "*test-webnames-api-key"

__all__ = [
    "_AGE_SECRET_KEY",
    "_API_SERVER_KEY",
    "_CLICKHOUSE_PASSWORD",
    "_GF_SECURITY_ADMIN_PASSWORD",
    "_GHCR_PULL_TOKEN",
    "_HERMES_DASHBOARD_PASSWORD",
    "_LANGFUSE_INIT_ORG_ID",
    "_LANGFUSE_INIT_PROJECT_ID",
    "_LANGFUSE_INIT_USER_PASSWORD",
    "_LANGFUSE_PUBLIC_KEY",
    "_LANGFUSE_SECRET_KEY",
    "_LITELLM_MASTER_KEY",
    "_MINIO_ROOT_PASSWORD",
    "_MINIO_ROOT_USER",
    "_NEXTAUTH_SECRET",
    "_PLATFORM_MASTER_EMAIL",
    "_PLATFORM_MASTER_PASSWORD",
    "_POSTGRES_PASSWORD",
    "_POSTGRES_USER",
    "_S3_ACCESS_KEY",
    "_S3_BUCKET",
    "_S3_SECRET_KEY",
    "_SALT",
    "_TELEGRAM_BOT_TOKEN",
    "_WEBNAMES_API_KEY",
]
